// The bound operations have to return the DATA, and only a compiler can say so.
//
// The wrapper's central claim is that a consumer writes
// `await cafaye.identity.getCurrentUser()` and gets a `User` — not the generated
// `{ data, error, request?, response? }` envelope, not a `User | undefined`, and
// certainly not an `any` that quietly hides both. That is a claim about TYPES,
// and no amount of runtime testing checks a type: a runtime test would pass
// happily against a signature that returns `any`.
//
// The generated signature makes this real work rather than a formality. Every
// operation returns
//
//     Promise<({ data: T; error: undefined } | { data: undefined; error: E })
//             & { request?: Request; response?: Response }>
//
// — a two-arm union intersected with an object whose `request` and `response` are
// both optional, because the transport can fail before a request exists. Getting
// a single non-optional value out of that is what `BoundOperation` in
// `src/cafaye/class.ts` is for, and the only honest way to know it works is to
// compile a file that uses the result.
//
// HOW IT RUNS
//
// The probe is written inside the repository, compiled with the project's own
// pinned `tsc` and the same strictness `bin/prime` uses, and deleted in a
// `finally`. Inside the repository rather than in a temp directory, because
// `cafaye-ts/...` has to resolve — Node and TypeScript both support a package
// referring to itself by name through its own `exports` map, and that is exactly
// the resolution a consumer performs. The same argument, and the same mechanism,
// as `test/readme-examples.test.mjs`.
//
// It imports through the PACKAGE NAME rather than through `src/`, deliberately.
// Compiling against `dist/` means the probe checks the declarations a consumer
// actually installs, which is a stronger claim than checking the source: a
// `private` modifier or an inferred return type that does not survive declaration
// emit shows up here and nowhere else.
//
// Every assertion in the probe is an assignment. If a conditional type stops
// distributing, or `DataOf` starts producing `T | undefined`, or an operation
// that takes no options stops being callable with none, the file fails to
// compile and this test fails with the compiler's own message.

import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { describe, it } from 'node:test';
import { promisify } from 'node:util';

import { REPO_ROOT } from '../scripts/lib/specs.mjs';

const execFileAsync = promisify(execFile);

const PROBE = `
// Generated by test/wrapper-types.test.mjs. Not committed; deleted in a finally.
import {
  Cafaye,
  CafayeNotFoundError,
  CafayeValidationError,
  isCafayeError,
} from 'cafaye-ts';
import type { Problem } from 'cafaye-ts/services/identity';

const cafaye = new Cafaye({ baseUrl: 'https://cafaye.example.com' });

// A 200 with no error arm: the data, non-optional. The generated signature makes
// this \`User | undefined\` because of the union's second arm, and the whole
// reason BoundOperation exists is that a caller should not have to narrow it.
export async function currentUser() {
  const user = await cafaye.identity.getCurrentUser();
  const email: string = user.email;
  const id: string = user.id;
  return { email, id };
}

// Required path parameters stay required, and typed from the document. The
// parameter is \`{ id }\` because billing's document says \`/v1/customers/{id}\` —
// written as anything else this line fails, which is the point: the wrapper's
// types come from the documents, so a wrong path key cannot compile.
export async function oneCustomer(id: string) {
  return await cafaye.billing.getCustomer({ path: { id } });
}

// An operation that takes no options at all is still callable with none — and
// that is a real case in the fleet, not a hypothetical: \`getCurrentUser\` is
// \`(options?: …)\` in the generated transport. If the conditional type deciding
// optionality were wrong, this is the line that fails, and it fails as an arity
// error rather than as \`undefined\`.
export async function me() {
  return await cafaye.identity.getCurrentUser();
}

// muse's one operation requires a body, and the body is typed from muse's
// document: \`role\` is the union \`'system' | 'user' | 'assistant'\`, not \`string\`.
// The \`as const\` below is what makes this compile, and the fact that it only
// compiles with them is the property being checked — a wrapper whose body
// parameters were \`any\` would accept \`{ role: 'wizard' }\` and bill a request
// for it.
export async function completion(body: {
  model: string;
  messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }>;
}) {
  return await cafaye.muse.routeCompletion({ body });
}

// A body is still a body, and a per-call header still works — \`Idempotency-Key\`
// is a header in core's conventions, so a caller must be able to send one.
export async function withHeader(headers: Record<string, string>) {
  return await cafaye.courier.listWebhookEndpoints({ headers });
}

// A validation failure narrows, and its per-field failures are reachable without
// a guard, because core says \`errors[]\` appears only on a 422 and the class
// reflects that.
export async function register(body: { email: string; password: string }) {
  try {
    return await cafaye.identity.registerUser({ body });
  } catch (error) {
    if (error instanceof CafayeValidationError) {
      const fields: readonly { field: string; code: string }[] = error.errors;
      return { first: fields[0]?.field ?? '' };
    }
    if (error instanceof CafayeNotFoundError) {
      return { trace: error.traceId };
    }
    if (isCafayeError(error)) {
      // The branch every cafaye failure takes, including ones with no class of
      // their own: \`kind\` and \`status\` are on the base, so this compiles.
      const kind: 'problem' | 'protocol' | 'network' | 'configuration' = error.kind;
      const status: number | null = error.status;
      return { kind, status };
    }
    throw error;
  }
}

// The generated problem type is still reachable without the wrapper, which is
// what keeps the six documents' types the source of truth.
export function describe(problem: Problem): string {
  return \`\${problem.code} on \${problem.instance}\`;
}

// All six surfaces exist, and each keeps the generated return type.
export const surfaces = [
  cafaye.identity,
  cafaye.billing,
  cafaye.courier,
  cafaye.darkroom,
  cafaye.muse,
  cafaye.pantry,
];

// The base URL is a record keyed by service name, and it is readable.
export function where(): string {
  return cafaye.baseUrls.identity;
}

// A credential is replaceable without rebuilding the client, and the kind is
// queryable while the value is not.
export function rotate(token: string): 'apiToken' | 'jwt' | 'session' | null {
  cafaye.setCredentials({ token });
  return cafaye.credentialKind;
}

// The escape hatch keeps each service's own generated client type.
export function rawBaseUrl(): string | undefined {
  return cafaye.rawClient('courier').getConfig().baseUrl;
}

// \`serviceNames\` is the same six the namespaces are, so a consumer enumerating
// the fleet and a consumer indexing it by name cannot disagree.
export function isKnown(name: string): boolean {
  return (cafaye.constructor as unknown) === Cafaye && name.length > 0;
}
`;

describe('the bound operations return their data, and the compiler says so', () => {
  it('compiles a probe that uses the wrapper the way a consumer would', async () => {
    const probe = path.join(REPO_ROOT, 'wrapper-types.probe.ts');
    try {
      await writeFile(probe, PROBE, 'utf8');
      await execFileAsync(
        process.execPath,
        [
          path.join(REPO_ROOT, 'node_modules', 'typescript', 'bin', 'tsc'),
          '--noEmit',
          // The same strictness `bin/prime` uses, so a probe that passes here
          // passes the gate's own typecheck. `noUncheckedIndexedAccess` and
          // `exactOptionalPropertyTypes` are the two that would catch a wrapper
          // quietly handing back `T | undefined`.
          '--strict',
          '--noUncheckedIndexedAccess',
          '--module', 'nodenext',
          '--moduleResolution', 'nodenext',
          '--target', 'es2023',
          '--lib', 'es2023,dom',
          '--skipLibCheck',
          probe,
        ],
        { cwd: REPO_ROOT, maxBuffer: 16 * 1024 * 1024 },
      );
    } catch (error) {
      assert.fail(
        'the wrapper\'s public types do not support the way a consumer uses them:\n\n' +
          `${error.stdout || ''}${error.stderr || ''}\n\n` +
          'Every failure above is a promise the README makes that the types do not keep — a ' +
          'bound operation that returns an envelope, an optional result, or a parameter that ' +
          'has become required or optional. Fix `BoundOperation` in src/cafaye/class.ts; do ' +
          'not loosen the compiler settings here.',
      );
    } finally {
      await rm(probe, { force: true });
    }
  });
});
