/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/courier.yaml
//         courier, document version 1.2.0,
//         vendored from git@github.com:cafaye/courier.git
//         at commit 59247b6c65fd86a331a4f4bdcaf180ee1730687f
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export { createWebhookEndpoint, deleteWebhookEndpoint, getNotificationPreferences, getWebhookEndpoint, listWebhookEndpoints, type Options, testWebhookEndpoint, updateNotificationPreferences, updateWebhookEndpoint } from './sdk.gen.js';
export type { ClientOptions, CreateWebhookEndpointData, CreateWebhookEndpointError, CreateWebhookEndpointErrors, CreateWebhookEndpointResponse, CreateWebhookEndpointResponses, Cursor, DeleteWebhookEndpointData, DeleteWebhookEndpointError, DeleteWebhookEndpointErrors, DeleteWebhookEndpointResponse, DeleteWebhookEndpointResponses, EndpointId, GetNotificationPreferencesData, GetNotificationPreferencesError, GetNotificationPreferencesErrors, GetNotificationPreferencesResponse, GetNotificationPreferencesResponses, GetWebhookEndpointData, GetWebhookEndpointError, GetWebhookEndpointErrors, GetWebhookEndpointResponse, GetWebhookEndpointResponses, Limit, ListWebhookEndpointsData, ListWebhookEndpointsError, ListWebhookEndpointsErrors, ListWebhookEndpointsResponse, ListWebhookEndpointsResponses, NotificationPreference, NotificationPreferences, NotificationType, Problem, TestWebhookEndpointData, TestWebhookEndpointError, TestWebhookEndpointErrors, TestWebhookEndpointResponse, TestWebhookEndpointResponses, UpdateNotificationPreferencesData, UpdateNotificationPreferencesError, UpdateNotificationPreferencesErrors, UpdateNotificationPreferencesResponse, UpdateNotificationPreferencesResponses, UpdateWebhookEndpointData, UpdateWebhookEndpointError, UpdateWebhookEndpointErrors, UpdateWebhookEndpointResponse, UpdateWebhookEndpointResponses, UserId, WebhookEndpoint, WebhookEndpointPage, WebhookEndpointStatus } from './types.gen.js';
