/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/courier.yaml
//         courier, document version 2.2.0,
//         vendored from git@github.com:cafaye/courier.git
//         at commit 467cd3efb849a339b3dae9eadb3c6b9882fbc1b9
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CreateWebhookEndpointData, CreateWebhookEndpointErrors, CreateWebhookEndpointResponses, DeleteWebhookEndpointData, DeleteWebhookEndpointErrors, DeleteWebhookEndpointResponses, GetNotificationPreferencesData, GetNotificationPreferencesErrors, GetNotificationPreferencesResponses, GetWebhookEndpointData, GetWebhookEndpointErrors, GetWebhookEndpointResponses, ListWebhookEndpointsData, ListWebhookEndpointsErrors, ListWebhookEndpointsResponses, ReceiveResendReportData, ReceiveResendReportErrors, ReceiveResendReportResponses, SendMessageData, SendMessageErrors, SendMessageResponses, TestWebhookEndpointData, TestWebhookEndpointErrors, TestWebhookEndpointResponses, UpdateNotificationPreferencesData, UpdateNotificationPreferencesErrors, UpdateNotificationPreferencesResponses, UpdateWebhookEndpointData, UpdateWebhookEndpointErrors, UpdateWebhookEndpointResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * One provider report about one or more recipients
 *
 * Delivers one Resend deliverability report, and answers what courier did
 * with it. This is the door `Courier.Suppressions` was written for: until it
 * existed, `email_suppressions` was written by nothing but tests, a customer's
 * hard-bounced address went on being mailed forever, and a sending domain's
 * reputation died of a cause no dashboard names.
 *
 * ## Who this is for
 *
 * **Resend, not a customer.** It is authenticated by the Svix signature on
 * the request, never by a bearer token, and it is deliberately outside `/v1`
 * for the same reason: `/v1` is this service's contract with a tenant.
 *
 * ## What a 200 means, and what it counts
 *
 * The signature verified, courier read the report, and the counts say what
 * happened to each recipient. There is no status for "courier read it and did
 * nothing", so the counts carry that distinction:
 *
 * | `data` field | meaning |
 * | --- | --- |
 * | `received` | reports the payload contained — one per **recipient**, so a broadcast to five addresses is 5 |
 * | `recorded` | suppression rows newly written, which is what stops courier mailing that mailbox |
 * | `duplicates` | reports courier already held, written by a redelivery |
 * | `ignored` | temporary failures, which courier deliberately records nothing about |
 * | `events` | `courier.email.bounced` / `.complained` rows published |
 *
 * `recorded` and `events` are the same number in every case except one, and
 * the difference is deliberate: a report whose `Message-ID` names a send
 * courier made publishes an event, and one that names nothing courier
 * recognises records the suppression and publishes no event. **The
 * suppression is the load-bearing half** — the address is not going to be
 * mailed again whatever courier can say about which message it was — so the
 * row is written and the missing event is a log line, not a rollback that
 * would throw the row away with it.
 *
 * ## A redelivery is a 200, and this operation takes no `Idempotency-Key`
 *
 * A provider retries a webhook it got no answer for. That is **normal**:
 * delivery is at-least-once. A second delivery of the same report is answered
 * `200` with `data.duplicates` above zero and **writes nothing** — the row and
 * its event are both already there.
 *
 * The deduplication is `email_suppressions`'s unique index on
 * `(provider, provider_event_id)`, and the key is derived from the report's
 * own **content** rather than from the `webhook-id` header. That is the one
 * place this departs from the reference implementation's advice, and the
 * reason is a broadcast: one delivery carries one `webhook-id` and a `to` of
 * every address it reached, so keying on the header would collapse five
 * bounced addresses into one suppression and go on mailing four of them for
 * ever. The content-derived key records one row per address and a redelivery
 * is still one row per address.
 *
 * `Idempotency-Key` is absent, and the reason is that the header a provider
 * sends is one no provider sends: the retry identity here is the Svix
 * signature, and the storage that makes it free is the unique index above.
 *
 * ## The order, and what it means for the statuses
 *
 * The signature is checked **before the body is parsed**, and nothing
 * upstream decodes it either — this operation's body is deliberately left
 * unparsed by the endpoint's `Plug.Parsers` so the bytes that arrive are the
 * bytes that were signed. Spec §Signature scheme names parse-then-re-
 * serialize as "a very common failure mode" of verification.
 *
 * Two statuses follow from that order, and both are worth a client reading
 * twice:
 *
 * * **An unsigned request is a 401, whatever its body.** A forged request
 * is told nothing about whether its payload parsed, because courier never
 * looked.
 * * **The 400 is reachable only with a valid signature.** A body that is not
 * JSON, *signed correctly*, is a 400 — there is no field to name and
 * nothing to correct, which is core's own line for 400 against 422. The
 * same body unsigned is a 401.
 *
 * ## Refusals that are courier's own, not the provider's
 *
 * `500` means **courier** is misconfigured — no signing secret, or one it
 * cannot decode. It is deliberately not a 401: a route answering 401 to its
 * own misconfiguration is indistinguishable from one under attack, and the
 * operator's first question would be the wrong one. `503` means the report
 * could not be written; the transaction unwound, so nothing is half-recorded
 * and the retry is safe.
 *
 * ## What a caller cannot see
 *
 * **No response on this operation carries an email address.** Not the counts,
 * not a 422's `detail`, not a value echoed back from the payload. The
 * suppression table has no `account_id` and is not exposed through any route,
 * so an address in a response would be a way to ask courier questions about
 * mailboxes it holds — the same posture as the 409 on `sendMessage`, which
 * does not echo one either. The address appears in courier's **logs**, where
 * `Courier.Inbound.Resend`'s refusals put it.
 *
 */
export const receiveResendReport = <ThrowOnError extends boolean = false>(options: Options<ReceiveResendReportData, ThrowOnError>): RequestResult<ReceiveResendReportResponses, ReceiveResendReportErrors, ThrowOnError> => (options.client ?? client).post<ReceiveResendReportResponses, ReceiveResendReportErrors, ThrowOnError>({
    security: [{ name: 'svix-signature', type: 'apiKey' }],
    url: '/inbound/resend',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send one transactional message
 *
 * Sends one of courier's transactional messages and answers with what
 * happened. This is the operation the platform's password reset, email
 * verification, email change and team invitation flows call; until it
 * existed those endpoints were reachable-looking and none of them could
 * complete.
 *
 * ## What a 200 means, precisely
 *
 * **The provider accepted the message for delivery, and courier wrote the
 * `courier.email.delivered` outbox row in the same transaction.** It does
 * **not** mean the mail arrived. A submission protocol's whole reply is
 * "accepted for delivery"; courier has no delivery receipt and will not
 * imply one it does not hold. `data.status` therefore reads `accepted` and
 * never `delivered` — a field reading `delivered` would be courier claiming
 * a fact about somebody else's inbox that courier cannot know yet.
 *
 * The send is **synchronous**: the preference check, the suppression check,
 * the provider's dial and the outbox row all happen inside the request, so
 * this response is the real outcome rather than a receipt for an intention.
 * The consequence is that a 409 below is a refusal the caller can act on,
 * which a queued contract could not give them — the answer would arrive after
 * the response, and a caller who cannot tell "suppressed" from "sent" retries
 * forever.
 *
 * ## Three refusals, told apart by status and `code`
 *
 * A client branches on `code` and not on `detail`, so the three outcomes
 * below are distinguishable without parsing prose:
 *
 * | outcome | status | `code` | retry? |
 * | --- | --- | --- | --- |
 * | accepted for delivery | 200 | — | — |
 * | the recipient's mailbox is suppressed | 409 | `conflict` | **no** |
 * | the request is wrong, or the user declined this type | 422 | `validation_failed` | after fixing it |
 * | the provider refused, or courier cannot deliver | 503 | `unavailable` | yes, same key |
 *
 * **A suppressed mailbox is a 409, not a 422**, and the reason is that it is
 * not a property of the request. A hard bounce and a spam complaint are
 * facts about a *mailbox*, recorded by a provider and not chosen by this
 * caller, and courier's suppression list is not exposed through any route —
 * so this response is the only place the fact can surface. 409 `conflict` is
 * core's own code for a request colliding with the current state of a
 * resource, and it is the status that tells a generated client not to try
 * again. A 422 would tell the caller to change a request that cannot be
 * changed.
 *
 * **A declined preference is a 422**, the opposite answer on purpose. The
 * user declining is visible through `GET /v1/notification_preferences/{user_id}`,
 * it is changeable through the `PUT` beside it, and `errors[]` — which core
 * reserves for 422 and nothing else — can name `type` as the field at
 * fault.
 *
 * **A provider refusal is a 503 and not a 500**, because courier is fine and
 * its dependency is not. Nothing was sent and no row was written, so the
 * retry is safe; and a failed request **releases** its `Idempotency-Key`
 * rather than storing the failure, so a retry is not locked out for 24 hours.
 *
 * ## Authentication
 *
 * Required, and not as a formality: an unauthenticated `POST` to a mail
 * egress is an open relay, and it is the one surface where that would be
 * true rather than theoretical. courier does not guess an account for an
 * anonymous caller, and a deployment without identity's JWT verifier locks
 * this route rather than serving it. The account comes from the principal
 * and **never from the body** — a body carrying `account_id` is a 422 naming
 * that field.
 *
 * ## Why there is no `from`, and no `text`/`html`
 *
 * Both are deliberate refusals of the obvious design, and the argument is
 * the same: courier sends *transactional* mail it renders from its own
 * templates, and a caller that could choose the sender would be a phishing
 * relay wearing the platform's sending domain — a cost borne by every other
 * tenant. So the sender and the subjects are configuration
 * (`COURIER_MAIL_*`), a body carrying `from` is a 422, and the bodies come
 * from templates keyed on `type`. What remains of "at least one of
 * text/html" is a check on the **rendered** message rather than on the
 * request: courier refuses to send a message with neither body, because
 * `Swoosh` would accept it and answer a provider-shaped id, and a bodiless
 * mail reported as delivered is the exact silent default this service has
 * spent two packets refusing.
 *
 * ## Idempotency
 *
 * Send `Idempotency-Key` and a retry with the same key and the same body
 * returns the first response byte for byte with `Idempotency-Replayed:
 * true`, having sent **one** mail. Omit it and a retry sends a second mail:
 * a send is not idempotent by HTTP's definition, and that is the caller's
 * own problem rather than something courier hides. The header is documented
 * here because silence about it would be the worse answer.
 *
 * ## What a caller cannot see
 *
 * The suppression list is never exposed through a route. A 409 says a
 * mailbox cannot be written to and does **not** echo the address back, and
 * `email_suppressions` carries no `account_id` — so the refusal is a fact
 * about a mailbox rather than about another tenant's data, and it is the
 * same posture the send path takes when it answers "no mail went out" rather
 * than "here is a list".
 *
 */
export const sendMessage = <ThrowOnError extends boolean = false>(options: Options<SendMessageData, ThrowOnError>): RequestResult<SendMessageResponses, SendMessageErrors, ThrowOnError> => (options.client ?? client).post<SendMessageResponses, SendMessageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * What this user has been asked to receive
 *
 * Every notification type courier sends, with this user's stored answers
 * filled in and the defaults used where there are none. A `GET` never writes.
 *
 * **An unwritten user is a 200, not a 404.** identity owns the user table.
 * courier is asked about a user id and answers with that user's
 * preferences, which for a user who has never touched the settings is
 * three types, all on. A 404 would be courier claiming to know something
 * about the requester it does not know.
 *
 * **A user whose preferences belong to another account is a 404**, and
 * that is the one case where the previous sentence does not apply: there is
 * a resource, it is not the caller's, and a 403 would confirm it exists.
 * The 404 appears only once somebody has written preferences for that user
 * id — see this document's header for why the account is recorded rather
 * than asked of identity, and what that means for who owns an unwritten
 * user id.
 *
 */
export const getNotificationPreferences = <ThrowOnError extends boolean = false>(options: Options<GetNotificationPreferencesData, ThrowOnError>): RequestResult<GetNotificationPreferencesResponses, GetNotificationPreferencesErrors, ThrowOnError> => (options.client ?? client).get<GetNotificationPreferencesResponses, GetNotificationPreferencesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/notification_preferences/{user_id}',
    ...options
});

/**
 * Apply a batch of preferences
 *
 * Stores a batch and answers with the state the user now has — the same
 * shape a `GET` returns, so a settings page does not have to follow a write
 * with a read to render.
 *
 * **A rejected batch writes nothing.** The entries are validated together
 * before any of them is stored, so a typo in the third entry cannot leave
 * the first two applied and the user looking at a half-saved settings page.
 * Applying the same batch twice is the same answer: this operation is
 * idempotent by construction, because it stores the state it is given rather
 * than accumulating deltas.
 *
 * `user_id` comes from the path and is never read from the body. A body
 * that names a different user cannot write that user's preferences.
 *
 * `account_id` cannot be named by a request at all: it is not a field of a
 * preference entry, so an entry carrying one is a 422 naming
 * `preferences[0].account_id`, and one beside the batch names nothing this
 * operation reads.
 *
 */
export const updateNotificationPreferences = <ThrowOnError extends boolean = false>(options: Options<UpdateNotificationPreferencesData, ThrowOnError>): RequestResult<UpdateNotificationPreferencesResponses, UpdateNotificationPreferencesErrors, ThrowOnError> => (options.client ?? client).put<UpdateNotificationPreferencesResponses, UpdateNotificationPreferencesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/notification_preferences/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the caller's webhook endpoints
 *
 * Cursor-paginated, oldest first. Disabled endpoints are included:
 * disabling is not deleting, and the row carries the failure count and the
 * reason delivery stopped.
 *
 */
export const listWebhookEndpoints = <ThrowOnError extends boolean = false>(options?: Options<ListWebhookEndpointsData, ThrowOnError>): RequestResult<ListWebhookEndpointsResponses, ListWebhookEndpointsErrors, ThrowOnError> => (options?.client ?? client).get<ListWebhookEndpointsResponses, ListWebhookEndpointsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints',
    ...options
});

/**
 * Register a webhook endpoint
 *
 * The signing secret is returned **once**, in this response, and cannot be
 * retrieved afterwards. Store it before leaving the response. A url courier
 * will not send to is refused with a 422 whose `errors[0].code` names the
 * class — `blocked_scheme`, `blocked_host`, `blocked_address`,
 * `dns_failure` — because a well-formed url that resolves to a private
 * address is a different problem from a typo and the customer needs to be
 * told which one they have.
 *
 */
export const createWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<CreateWebhookEndpointData, ThrowOnError>): RequestResult<CreateWebhookEndpointResponses, CreateWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).post<CreateWebhookEndpointResponses, CreateWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a webhook endpoint
 */
export const deleteWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<DeleteWebhookEndpointData, ThrowOnError>): RequestResult<DeleteWebhookEndpointResponses, DeleteWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).delete<DeleteWebhookEndpointResponses, DeleteWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}',
    ...options
});

/**
 * Fetch one webhook endpoint
 */
export const getWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<GetWebhookEndpointData, ThrowOnError>): RequestResult<GetWebhookEndpointResponses, GetWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).get<GetWebhookEndpointResponses, GetWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}',
    ...options
});

/**
 * Change a webhook endpoint
 *
 * A new `url` is a new destination and passes the same checks as a create.
 * Fields that are not named are left alone, and the signing secret never
 * changes here: a customer who edits a description must not have every
 * delivery start failing verification for a day.
 *
 */
export const updateWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<UpdateWebhookEndpointData, ThrowOnError>): RequestResult<UpdateWebhookEndpointResponses, UpdateWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).patch<UpdateWebhookEndpointResponses, UpdateWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send a signed test payload to the endpoint
 *
 * Sends a signed `ping` and reports what the receiver answered. The response
 * is `200` whether or not the endpoint accepted it: the caller's request
 * was well-formed and courier did what it was asked, which is a different
 * fact from courier being unable to test. Read `data.delivered`.
 *
 * This is not a delivery. It writes no `webhook_deliveries` row, counts no
 * attempt, and does not move the endpoint's circuit breaker — a customer
 * testing their own endpoint and getting a 500 has learned something true,
 * and charging their circuit for asking would punish them for using the
 * diagnostic.
 *
 * `Idempotency-Key` applies here too, and it matters more than it looks: a
 * retried ping with the same key is answered from the stored response, so
 * the customer's endpoint receives **one** signed request rather than two. A
 * test endpoint that receives duplicates is a support question.
 *
 */
export const testWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<TestWebhookEndpointData, ThrowOnError>): RequestResult<TestWebhookEndpointResponses, TestWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).post<TestWebhookEndpointResponses, TestWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}/test',
    ...options
});
