/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/courier.yaml
//         courier, document version 1.2.0,
//         vendored from git@github.com:cafaye/courier.git
//         at commit 59247b6c65fd86a331a4f4bdcaf180ee1730687f
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CreateWebhookEndpointData, CreateWebhookEndpointErrors, CreateWebhookEndpointResponses, DeleteWebhookEndpointData, DeleteWebhookEndpointErrors, DeleteWebhookEndpointResponses, GetNotificationPreferencesData, GetNotificationPreferencesErrors, GetNotificationPreferencesResponses, GetWebhookEndpointData, GetWebhookEndpointErrors, GetWebhookEndpointResponses, ListWebhookEndpointsData, ListWebhookEndpointsErrors, ListWebhookEndpointsResponses, TestWebhookEndpointData, TestWebhookEndpointErrors, TestWebhookEndpointResponses, UpdateNotificationPreferencesData, UpdateNotificationPreferencesErrors, UpdateNotificationPreferencesResponses, UpdateWebhookEndpointData, UpdateWebhookEndpointErrors, UpdateWebhookEndpointResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * What this user has been asked to receive
 *
 * Every notification type courier sends, with this user's stored answers
 * filled in and the defaults used where there are none. A `GET` never writes.
 *
 * **An unknown user is a 200, not a 404.** identity owns the user table.
 * courier is asked about a user id and answers with that user's
 * preferences, which for a user who has never touched the settings is
 * three types, all on. A 404 would be courier claiming to know something
 * about the requester it does not know.
 *
 * Served without authentication — see this document's header, which records
 * the gap and why it is not quietly written over here.
 *
 */
export const getNotificationPreferences = <ThrowOnError extends boolean = false>(options: Options<GetNotificationPreferencesData, ThrowOnError>): RequestResult<GetNotificationPreferencesResponses, GetNotificationPreferencesErrors, ThrowOnError> => (options.client ?? client).get<GetNotificationPreferencesResponses, GetNotificationPreferencesErrors, ThrowOnError>({ url: '/v1/notification_preferences/{user_id}', ...options });

/**
 * Apply a batch of preferences
 *
 * Stores a batch and answers with the state the user now has — the same
 * shape a `GET` returns, so a settings page does not have to follow a write
 * with a read to render.
 *
 * **A rejected batch writes nothing.** The entries are validated together
 * before any of them is stored, so a typo in the third entry cannot leave
 * the first two applied and the user looking at a half-saved settings page.
 * Applying the same batch twice is the same answer: this operation is
 * idempotent by construction, because it stores the state it is given rather
 * than accumulating deltas.
 *
 * `user_id` comes from the path and is never read from the body. A body
 * that names a different user cannot write that user's preferences.
 *
 * Served without authentication — see this document's header.
 *
 */
export const updateNotificationPreferences = <ThrowOnError extends boolean = false>(options: Options<UpdateNotificationPreferencesData, ThrowOnError>): RequestResult<UpdateNotificationPreferencesResponses, UpdateNotificationPreferencesErrors, ThrowOnError> => (options.client ?? client).put<UpdateNotificationPreferencesResponses, UpdateNotificationPreferencesErrors, ThrowOnError>({
    url: '/v1/notification_preferences/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the caller's webhook endpoints
 *
 * Cursor-paginated, oldest first. Disabled endpoints are included:
 * disabling is not deleting, and the row carries the failure count and the
 * reason delivery stopped.
 *
 */
export const listWebhookEndpoints = <ThrowOnError extends boolean = false>(options?: Options<ListWebhookEndpointsData, ThrowOnError>): RequestResult<ListWebhookEndpointsResponses, ListWebhookEndpointsErrors, ThrowOnError> => (options?.client ?? client).get<ListWebhookEndpointsResponses, ListWebhookEndpointsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints',
    ...options
});

/**
 * Register a webhook endpoint
 *
 * The signing secret is returned **once**, in this response, and cannot be
 * retrieved afterwards. Store it before leaving the response. A url courier
 * will not send to is refused with a 422 whose `errors[0].code` names the
 * class — `blocked_scheme`, `blocked_host`, `blocked_address`,
 * `dns_failure` — because a well-formed url that resolves to a private
 * address is a different problem from a typo and the customer needs to be
 * told which one they have.
 *
 */
export const createWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<CreateWebhookEndpointData, ThrowOnError>): RequestResult<CreateWebhookEndpointResponses, CreateWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).post<CreateWebhookEndpointResponses, CreateWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a webhook endpoint
 */
export const deleteWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<DeleteWebhookEndpointData, ThrowOnError>): RequestResult<DeleteWebhookEndpointResponses, DeleteWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).delete<DeleteWebhookEndpointResponses, DeleteWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}',
    ...options
});

/**
 * Fetch one webhook endpoint
 */
export const getWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<GetWebhookEndpointData, ThrowOnError>): RequestResult<GetWebhookEndpointResponses, GetWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).get<GetWebhookEndpointResponses, GetWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}',
    ...options
});

/**
 * Change a webhook endpoint
 *
 * A new `url` is a new destination and passes the same checks as a create.
 * Fields that are not named are left alone, and the signing secret never
 * changes here: a customer who edits a description must not have every
 * delivery start failing verification for a day.
 *
 */
export const updateWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<UpdateWebhookEndpointData, ThrowOnError>): RequestResult<UpdateWebhookEndpointResponses, UpdateWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).patch<UpdateWebhookEndpointResponses, UpdateWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send a signed test payload to the endpoint
 *
 * Sends a signed `ping` and reports what the receiver answered. The response
 * is `200` whether or not the endpoint accepted it: the caller's request
 * was well-formed and courier did what it was asked, which is a different
 * fact from courier being unable to test. Read `data.delivered`.
 *
 * This is not a delivery. It writes no `webhook_deliveries` row, counts no
 * attempt, and does not move the endpoint's circuit breaker — a customer
 * testing their own endpoint and getting a 500 has learned something true,
 * and charging their circuit for asking would punish them for using the
 * diagnostic.
 *
 */
export const testWebhookEndpoint = <ThrowOnError extends boolean = false>(options: Options<TestWebhookEndpointData, ThrowOnError>): RequestResult<TestWebhookEndpointResponses, TestWebhookEndpointErrors, ThrowOnError> => (options.client ?? client).post<TestWebhookEndpointResponses, TestWebhookEndpointErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/webhook_endpoints/{id}/test',
    ...options
});
