/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/courier.yaml
//         courier, document version 1.2.0,
//         vendored from git@github.com:cafaye/courier.git
//         at commit 59247b6c65fd86a331a4f4bdcaf180ee1730687f
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export type ClientOptions = {
    baseUrl: 'https://courier.cafaye.com' | 'http://localhost:4000' | (string & {});
};

/**
 * Every notification type courier sends. A type outside this list is a 422
 * naming `preferences[0].notification_type`, because a preference for
 * something courier will never send is a setting page that lies to the user.
 *
 */
export type NotificationType = 'welcome' | 'password_reset' | 'team_invitation';

export type NotificationPreference = {
    notification_type: NotificationType;
    /**
     * Whether courier will send this type to this user by email. Defaults
     * to true: silence is not consent.
     *
     */
    email_enabled: boolean;
    /**
     * Stored and returned so the answer is complete, but nothing sends push
     * — a `true` here does not mean courier will send a push.
     *
     */
    push_enabled: boolean;
};

export type NotificationPreferences = {
    /**
     * The user these preferences are for, as the path named them.
     */
    user_id: string;
    /**
     * Every notification type, always all of them and never a subset: a
     * settings page should not have to guess what it has not been told.
     *
     */
    preferences: Array<NotificationPreference>;
};

/**
 * `disabled` is two things wearing one column: the customer turned it off,
 * or courier's circuit breaker tripped. `disabled_reason` tells them apart,
 * and is courier's to clear.
 *
 */
export type WebhookEndpointStatus = 'enabled' | 'disabled';

export type WebhookEndpoint = {
    id: string;
    /**
     * The owning account. Always the caller's.
     */
    account_id: string;
    url: string;
    description?: string;
    status: WebhookEndpointStatus;
    /**
     * Failures since the last success. At the circuit threshold courier
     * disables the endpoint and records why.
     *
     */
    consecutive_failures: number;
    /**
     * Why delivery stopped, when courier is the one who stopped it. Null for
     * an endpoint the customer disabled, and null again once they re-enable
     * one courier had tripped.
     *
     */
    disabled_reason?: string;
};

export type WebhookEndpointPage = {
    data: Array<WebhookEndpoint>;
    page: {
        has_more: boolean;
        /**
         * Null on the last page.
         */
        next_cursor: string;
    };
};

/**
 * RFC 9457, with courier's extensions. Every non-2xx.
 */
export type Problem = {
    /**
     * `https://errors.cafaye.com/<code>`. The machine-readable contract.
     */
    type: string;
    title: string;
    status: number;
    /**
     * Specific to this occurrence. Not parsed by clients.
     */
    detail: string;
    /**
     * The path the request was made to.
     */
    instance?: string;
    /**
     * The last segment of `type`, in snake_case.
     */
    code: string;
    /**
     * Matches the `X-Trace-Id` response header. Support starts here.
     */
    trace_id: string;
    /**
     * Present only on a 422.
     */
    errors?: Array<{
        /**
         * The path in the *request*, which is what the caller can fix.
         */
        field: string;
        code: 'invalid_format' | 'taken' | 'blocked_scheme' | 'blocked_host' | 'blocked_address' | 'dns_failure';
    }>;
};

/**
 * A uuid from identity. courier does not own users and holds no foreign key
 * to them, so this is checked for *shape* and nothing else: a non-uuid is a
 * 422 before the body is looked at, and a well-formed id courier has never
 * seen is a 200 with the defaults.
 *
 */
export type UserId = string;

/**
 * The endpoint's uuid.
 */
export type EndpointId = string;

/**
 * Page size. Defaults to 25, capped at 100.
 */
export type Limit = number;

/**
 * The opaque cursor from a previous page's `page.next_cursor`. Clients must
 * not parse it; courier's encoding may change without notice. A cursor
 * courier did not issue is a 422.
 *
 */
export type Cursor = string;

export type GetNotificationPreferencesData = {
    body?: never;
    path: {
        /**
         * A uuid from identity. courier does not own users and holds no foreign key
         * to them, so this is checked for *shape* and nothing else: a non-uuid is a
         * 422 before the body is looked at, and a well-formed id courier has never
         * seen is a 200 with the defaults.
         *
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/notification_preferences/{user_id}';
};

export type GetNotificationPreferencesErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     */
    400: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     */
    422: Problem;
};

export type GetNotificationPreferencesError = GetNotificationPreferencesErrors[keyof GetNotificationPreferencesErrors];

export type GetNotificationPreferencesResponses = {
    /**
     * Every notification type, with this user's answers
     */
    200: {
        data: NotificationPreferences;
    };
};

export type GetNotificationPreferencesResponse = GetNotificationPreferencesResponses[keyof GetNotificationPreferencesResponses];

export type UpdateNotificationPreferencesData = {
    body: {
        /**
         * The entries to store. A type or channel not named here is left
         * alone, so a client that knows about one setting can send one
         * entry without overwriting the rest.
         *
         */
        preferences: Array<{
            notification_type: NotificationType;
            email_enabled?: boolean;
            /**
             * Stored and returned because the API is the user's
             * settings, but nothing sends push, so a `true` here does
             * not mean courier will send a push.
             *
             */
            push_enabled?: boolean;
        }>;
    };
    path: {
        /**
         * A uuid from identity. courier does not own users and holds no foreign key
         * to them, so this is checked for *shape* and nothing else: a non-uuid is a
         * 422 before the body is looked at, and a well-formed id courier has never
         * seen is a 200 with the defaults.
         *
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/notification_preferences/{user_id}';
};

export type UpdateNotificationPreferencesErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     */
    400: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     */
    422: Problem;
};

export type UpdateNotificationPreferencesError = UpdateNotificationPreferencesErrors[keyof UpdateNotificationPreferencesErrors];

export type UpdateNotificationPreferencesResponses = {
    /**
     * The stored state, the same shape a `GET` returns
     */
    200: {
        data: NotificationPreferences;
    };
};

export type UpdateNotificationPreferencesResponse = UpdateNotificationPreferencesResponses[keyof UpdateNotificationPreferencesResponses];

export type ListWebhookEndpointsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page size. Defaults to 25, capped at 100.
         */
        limit?: number;
        /**
         * The opaque cursor from a previous page's `page.next_cursor`. Clients must
         * not parse it; courier's encoding may change without notice. A cursor
         * courier did not issue is a 422.
         *
         */
        cursor?: string;
    };
    url: '/v1/webhook_endpoints';
};

export type ListWebhookEndpointsErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     */
    401: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     */
    422: Problem;
};

export type ListWebhookEndpointsError = ListWebhookEndpointsErrors[keyof ListWebhookEndpointsErrors];

export type ListWebhookEndpointsResponses = {
    /**
     * One page of endpoints
     */
    200: WebhookEndpointPage;
};

export type ListWebhookEndpointsResponse = ListWebhookEndpointsResponses[keyof ListWebhookEndpointsResponses];

export type CreateWebhookEndpointData = {
    body: {
        /**
         * An absolute http(s) URL. `file:`, `ftp:`, `gopher:`, `data:`
         * and `javascript:` are refused, as are loopback, link-local
         * (including `169.254.169.254`), RFC1918 and unique-local
         * addresses — by literal address *and* by what the host
         * resolves to.
         *
         */
        url: string;
        description?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/webhook_endpoints';
};

export type CreateWebhookEndpointErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     */
    401: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     */
    422: Problem;
};

export type CreateWebhookEndpointError = CreateWebhookEndpointErrors[keyof CreateWebhookEndpointErrors];

export type CreateWebhookEndpointResponses = {
    /**
     * Registered, with the signing secret
     */
    201: {
        data: WebhookEndpoint & {
            /**
             * The Standard Webhooks signing secret, base64
             * encoded behind the `whsec_` prefix. Shown once.
             *
             */
            secret: string;
        };
    };
};

export type CreateWebhookEndpointResponse = CreateWebhookEndpointResponses[keyof CreateWebhookEndpointResponses];

export type DeleteWebhookEndpointData = {
    body?: never;
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}';
};

export type DeleteWebhookEndpointErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
};

export type DeleteWebhookEndpointError = DeleteWebhookEndpointErrors[keyof DeleteWebhookEndpointErrors];

export type DeleteWebhookEndpointResponses = {
    /**
     * Removed. No body.
     */
    204: void;
};

export type DeleteWebhookEndpointResponse = DeleteWebhookEndpointResponses[keyof DeleteWebhookEndpointResponses];

export type GetWebhookEndpointData = {
    body?: never;
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}';
};

export type GetWebhookEndpointErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
};

export type GetWebhookEndpointError = GetWebhookEndpointErrors[keyof GetWebhookEndpointErrors];

export type GetWebhookEndpointResponses = {
    /**
     * The endpoint
     */
    200: {
        data: WebhookEndpoint;
    };
};

export type GetWebhookEndpointResponse = GetWebhookEndpointResponses[keyof GetWebhookEndpointResponses];

export type UpdateWebhookEndpointData = {
    body: {
        url?: string;
        description?: string;
        status?: WebhookEndpointStatus;
    };
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}';
};

export type UpdateWebhookEndpointErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     */
    422: Problem;
};

export type UpdateWebhookEndpointError = UpdateWebhookEndpointErrors[keyof UpdateWebhookEndpointErrors];

export type UpdateWebhookEndpointResponses = {
    /**
     * The endpoint as it now is
     */
    200: {
        data: WebhookEndpoint;
    };
};

export type UpdateWebhookEndpointResponse = UpdateWebhookEndpointResponses[keyof UpdateWebhookEndpointResponses];

export type TestWebhookEndpointData = {
    body?: never;
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}/test';
};

export type TestWebhookEndpointErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
};

export type TestWebhookEndpointError = TestWebhookEndpointErrors[keyof TestWebhookEndpointErrors];

export type TestWebhookEndpointResponses = {
    /**
     * The ping was sent; `delivered` says whether it was accepted
     */
    200: {
        data: {
            /**
             * Whether the receiver answered 2xx.
             */
            delivered: boolean;
            /**
             * The receiver's status, or null if nothing answered.
             */
            status_code: number;
            /**
             * How long the attempt took.
             */
            duration_ms: number;
        };
    };
};

export type TestWebhookEndpointResponse = TestWebhookEndpointResponses[keyof TestWebhookEndpointResponses];
