/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/courier.yaml
//         courier, document version 2.2.0,
//         vendored from git@github.com:cafaye/courier.git
//         at commit 467cd3efb849a339b3dae9eadb3c6b9882fbc1b9
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export type ClientOptions = {
    baseUrl: 'https://courier.cafaye.com' | 'http://localhost:4000' | (string & {});
};

/**
 * What to send, to whom, and who it is about.
 *
 * **The vocabulary is closed.** An unknown field is a 422 naming it, rather
 * than a field courier silently discards — a misspelled `emai_enabled` that
 * was ignored would leave a caller believing a setting had taken effect.
 * `account_id` is in that set: the account is the principal's and never the
 * body's.
 *
 */
export type SendMessageRequest = {
    type: NotificationType;
    /**
     * The user this send is about, and the key the recipient's preferences
     * are read by. Checked for shape only — courier holds no foreign key to
     * identity's users. A non-uuid is a 422: it could key no preference and
     * attribute no event.
     *
     */
    user_id: string;
    /**
     * The recipient. courier's payload calls this field `email` because that
     * is what the platform's event payloads carry; over HTTP it is `to`,
     * which is the mail vocabulary.
     *
     * This address is checked against courier's suppression list before
     * anything is sent, so a mailbox that hard-bounced or reported a previous
     * message as spam is a **409 `conflict`** — see the operation.
     *
     */
    to: string;
    /**
     * The recipient's display name, used in the greeting. Optional; courier
     * falls back to a bare greeting when it is absent.
     *
     */
    name?: string;
    /**
     * The link the message carries — the reset link, the invitation link,
     * the confirmation link. Required by `password_reset` and
     * `team_invitation` and unused by `welcome`, which is why its absence is
     * a 422 naming `url` rather than a silently linkless mail.
     *
     */
    url?: string;
    /**
     * Required by `team_invitation` only.
     */
    account_name?: string;
    /**
     * Required by `team_invitation` only.
     */
    invited_by?: string;
    /**
     * The role offered by a `team_invitation`. Optional and unvalidated
     * against any list — courier has no role vocabulary of its own, and
     * inventing one would put a second source of truth next to identity's.
     *
     */
    role?: string;
};

export type SendMessageResult = {
    /**
     * courier's id for this message, and the one on the wire as the
     * `Message-ID` header. A bounce or a complaint quoting it can be tied
     * back to this send, which is the entire reason it is returned.
     *
     */
    message_id: string;
    /**
     * The `courier.email.delivered` outbox row written in the same
     * transaction as the send, so a caller can correlate its own send with
     * the event every subscriber on the bus sees.
     *
     */
    event_id: string;
    notification_type: NotificationType;
    /**
     * The user this send was about, as the body named them.
     */
    user_id: string;
    /**
     * Always `accepted`, and never `delivered`. A submission protocol's whole
     * reply is "accepted for delivery"; courier has no delivery receipt and
     * will not imply one it does not hold. A client that needs to know the
     * mail arrived has to wait for the bounce, not read this field.
     *
     */
    status: 'accepted';
};

/**
 * What one delivery did, counted per **recipient** rather than per request.
 *
 * There is no status for "courier read this report and had no opinion on it",
 * so the counts carry that distinction instead: an event type courier has read
 * and does nothing about answers `200` with all five at zero, and a provider
 * that is told so by a `2xx` stops retrying it. A soft bounce answers `200`
 * with `ignored` above zero and `recorded` at zero.
 *
 * These are **counts and nothing else**. No address, no identifier, no part of
 * the payload: the suppression table has no `account_id` and is not exposed
 * through any route, so a value in here would be a way to ask courier questions
 * about mailboxes it holds.
 *
 */
export type InboundReportCounts = {
    /**
     * Reports the payload contained, one per recipient. A broadcast to five
     * addresses is `5`, because the unit courier acts on is one address.
     *
     */
    received: number;
    /**
     * Suppression rows newly written. This is the number that stops courier
     * mailing that mailbox.
     *
     */
    recorded: number;
    /**
     * Reports courier already held. A redelivery is a normal event and is
     * answered `200`, never a `409` — a provider retrying a report courier has
     * has done nothing wrong.
     *
     */
    duplicates: number;
    /**
     * Temporary failures (RFC 5321 §4.2.2 — mailbox full, greylisted). courier
     * records **nothing** about these on purpose: suppressing on one is how a
     * suppression list starts eating live addresses.
     *
     */
    ignored: number;
    /**
     * `courier.email.bounced` / `courier.email.complained` outbox rows
     * written, in the same transaction as the suppression. Equal to `recorded`
     * except when a report's `Message-ID` names no send courier made, in which
     * case the suppression is recorded and no event is published.
     *
     */
    events: number;
};

/**
 * One Resend deliverability report, as documented at
 * <https://resend.com/docs/webhooks/emails/bounced> and its siblings.
 *
 * **This is the provider's schema, not courier's.** courier does not validate
 * it and does not accept fields it does not read — the opposite of
 * `sendMessage`, whose vocabulary is closed and refuses an unknown field. The
 * asymmetry is the point: `sendMessage`'s body is written by a caller who
 * cannot fix a typo after the fact, whereas this body is written by a provider
 * whose schema courier does not control, and refusing a field courier simply
 * has no use for would turn a provider's harmless addition into a delivery
 * courier rejects.
 *
 * courier **reads** a closed subset of it, and an event type it has not read
 * is a `422` rather than a silent no-op — so a provider that adds one produces
 * a log line instead of courier quietly recording nothing. That is the
 * fail-closed choice, and it costs a retry loop on a change courier cannot
 * make sense of; the alternative is silence about a change somebody needed to
 * see.
 *
 */
export type ResendReport = {
    /**
     * The event. `email.bounced` and `email.complained` are the two courier
     * acts on; `email.delivery_delayed` and the other deliverability events
     * are understood and have no opinion; a type courier has not read is a
     * `422` naming this field.
     *
     */
    type: string;
    /**
     * When the **report** happened, RFC 3339. Read at the top level rather than
     * from `data`, because `data.created_at` is when the email was sent — hours
     * earlier, and the wrong answer to "when did this address bounce".
     *
     */
    created_at: string;
    data: {
        /**
         * The provider's id for the message. **A broadcast shares one of these
         * across every recipient**, which is why courier's deduplication key
         * also carries the address.
         *
         */
        email_id?: string;
        /**
         * The `Message-ID` courier wrote when it sent the message, quoted back
         * as the provider received it. It is how courier ties the report to the
         * send — and therefore to the `user_id` and notification type an event
         * about it has to carry.
         *
         * Optional, and a report without one is not an error: the suppression
         * is recorded and no event is published.
         *
         */
        message_id?: string;
        /**
         * Every recipient the report is about. One suppression per entry, and
         * one entry that is not an address courier could send to refuses the
         * **whole** report rather than half-applying it.
         *
         */
        to?: Array<string>;
        /**
         * Present on `email.bounced` only.
         */
        bounce?: {
            /**
             * `Permanent` stops the send (RFC 5321 §5.1.1). The other three are
             * temporary and courier records **nothing** about them — including
             * `Undetermined`, which is a *known* value meaning "the provider
             * does not know", and is deliberately read as soft: being told
             * there was a bounce is not being told the mailbox is gone. A value
             * outside this list is a `422`, so a provider that adds one is
             * visible rather than silently soft.
             *
             */
            type?: 'Permanent' | 'Transient' | 'Temporary' | 'Undetermined';
            subType?: string;
            message?: string;
            /**
             * The receiving server's own SMTP replies. Kept because "5.1.1
             * does not exist" is the sentence an operator actually needs, and
             * it lands in courier's logs rather than in the suppression row.
             *
             */
            diagnosticCode?: Array<string>;
        };
    };
};

/**
 * Every notification type courier sends. A type outside this list is a 422
 * naming `preferences[0].notification_type`, because a preference for
 * something courier will never send is a setting page that lies to the user.
 *
 */
export type NotificationType = 'welcome' | 'password_reset' | 'team_invitation';

export type NotificationPreference = {
    notification_type: NotificationType;
    /**
     * Whether courier will send this type to this user by email. Defaults
     * to true: silence is not consent.
     *
     */
    email_enabled: boolean;
    /**
     * Stored and returned so the answer is complete, but nothing sends push
     * — a `true` here does not mean courier will send a push.
     *
     */
    push_enabled: boolean;
};

export type NotificationPreferences = {
    /**
     * The user these preferences are for, as the path named them.
     */
    user_id: string;
    /**
     * Every notification type, always all of them and never a subset: a
     * settings page should not have to guess what it has not been told.
     *
     */
    preferences: Array<NotificationPreference>;
};

/**
 * `disabled` is two things wearing one column: the customer turned it off,
 * or courier's circuit breaker tripped. `disabled_reason` tells them apart,
 * and is courier's to clear.
 *
 */
export type WebhookEndpointStatus = 'enabled' | 'disabled';

export type WebhookEndpoint = {
    id: string;
    /**
     * The owning account. Always the caller's.
     */
    account_id: string;
    url: string;
    description?: string;
    status: WebhookEndpointStatus;
    /**
     * Failures since the last success. At the circuit threshold courier
     * disables the endpoint and records why.
     *
     */
    consecutive_failures: number;
    /**
     * Why delivery stopped, when courier is the one who stopped it. Null for
     * an endpoint the customer disabled, and null again once they re-enable
     * one courier had tripped.
     *
     */
    disabled_reason?: string;
};

export type WebhookEndpointPage = {
    data: Array<WebhookEndpoint>;
    page: {
        has_more: boolean;
        /**
         * Null on the last page.
         */
        next_cursor: string;
    };
};

/**
 * RFC 9457, with courier's extensions. Every non-2xx.
 */
export type Problem = {
    /**
     * `https://errors.cafaye.com/<code>`. The machine-readable contract.
     */
    type: string;
    title: string;
    status: number;
    /**
     * Specific to this occurrence. Not parsed by clients.
     */
    detail: string;
    /**
     * The path the request was made to.
     */
    instance?: string;
    /**
     * The last segment of `type`, in snake_case.
     */
    code: string;
    /**
     * Matches the `X-Trace-Id` response header. Support starts here.
     */
    trace_id: string;
    /**
     * Present only on a 422.
     */
    errors?: Array<{
        /**
         * The path in the *request*, which is what the caller can fix.
         */
        field: string;
        code: 'invalid_format' | 'taken' | 'blocked_scheme' | 'blocked_host' | 'blocked_address' | 'dns_failure' | 'unknown_field' | 'required' | 'unknown_notification_type' | 'notification_preferences_disabled' | 'unsupported_event' | 'unknown_bounce_type' | 'invalid_recipient';
        /**
         * Why this one field was refused, when courier has something to add
         * to `code` — a bad `limit` reads "is not a positive integer"
         * rather than only `invalid_format`. Present on some entries and
         * not on others, so a client must not require it.
         *
         */
        detail?: string;
    }>;
};

/**
 * The delivery's own id. It is part of the signed base string
 * (`msg_id.timestamp.payload`), so it cannot contain a full stop — a dot
 * would let a sender append fields to a string the receiver treats as
 * verified.
 *
 * courier does **not** use it as an idempotency key, and the operation's
 * description says why: one delivery can name many recipients, and keying on
 * the header would collapse a broadcast into one suppression.
 *
 */
export type SvixId = string;

/**
 * When the delivery was signed, as a bare integer of seconds since the epoch.
 * It must be a bare integer: the receiver builds the base string from the
 * header's own bytes, so a lenient parse would verify one string and act on
 * another.
 *
 * It is also courier's **replay window**. A signature outside ±300 seconds is
 * refused even when it is otherwise correct, which is the other half of
 * replay protection — the unique index handles a replay *inside* the window,
 * and the window handles one outside it.
 *
 */
export type SvixTimestamp = number;

/**
 * The signature, as `v1,<base64 HMAC-SHA256>` over
 * `svix-id.svix-timestamp.body`.
 *
 * **Space-delimited, and that is not incidental**: a producer rotating its key
 * sends the current and the previous signature together, and an unrecognised
 * identifier in the list is skipped rather than refused so it cannot stop the
 * `v1` entry beside it from being found. So courier's key rotation needs no
 * downtime and no coordination beyond the provider-side change.
 *
 * The comparison is constant-time. A verifier that is merely correct is not
 * enough — the scheme's own guidance is that failing to compare in constant
 * time "can expose consumers to timing-attacks and turn them into signing
 * oracles".
 *
 * The `webhook-` prefixed spellings are accepted as well, because the scheme
 * says headers "should be prefixed with `webhook-`" and Svix sends `svix-`
 * unless an account is white-labelled.
 *
 */
export type SvixSignature = string;

/**
 * A uuid from identity. courier does not own users and holds no foreign key
 * to them, so this is checked for *shape* and nothing else: a non-uuid is a
 * 422 before the body is looked at, and a well-formed id courier has never
 * seen is a 200 with the defaults.
 *
 */
export type UserId = string;

/**
 * The endpoint's uuid.
 */
export type EndpointId = string;

/**
 * Page size. Defaults to 25, capped at 100.
 */
export type Limit = number;

/**
 * The opaque cursor from a previous page's `page.next_cursor`. Clients must
 * not parse it; courier's encoding may change without notice. A cursor
 * courier did not issue is a 422.
 *
 */
export type Cursor = string;

/**
 * A uuid the client chooses, which makes a retry of this request free.
 *
 * Send it, and a retry with the **same** key and the **same** body returns
 * the first response byte for byte with `Idempotency-Replayed: true` — for
 * `createWebhookEndpoint` that includes the signing secret, which exists in
 * exactly one response and cannot be re-derived. Without it a caller that
 * timed out cannot know whether the first attempt landed, and retrying a
 * webhook registration produces a second destination courier will sign for.
 *
 * Three cases, and a client can tell them apart by `code`:
 *
 * | you sent | you get | `code` |
 * | --- | --- | --- |
 * | same key, same body, already answered | the first response, with `Idempotency-Replayed: true` | — |
 * | same key, different body | 409 | `idempotency_key_reused` |
 * | same key, same body, first attempt still running | 409 | `conflict`; retry the same request shortly |
 *
 * Omitting the header is not an error: the request is processed normally,
 * and a retry without a key is the client's own problem. A key that is not a
 * uuid is a 422 — the header is a uuid because an unbounded string in a
 * unique index is a cost every write pays.
 *
 * The key is scoped to the `(account, endpoint, key)` triple, and `endpoint`
 * is the **concrete** path, so the same key used to test two different
 * endpoints is two different keys. Retention is 24 hours, after which the
 * key behaves as though it had never been used. Only a 2xx is stored, so a
 * request that failed leaves the key free to use again immediately.
 *
 */
export type IdempotencyKey = string;

/**
 * `true`, and **only** on a response that is a stored replay of an earlier
 * request rather than the answer to the one in front of courier. A client
 * that receives it knows the mutation happened exactly once. Absent on every
 * first response, and absent on every request sent without a key.
 *
 */
export type IdempotencyReplayed = 'true';

export type ReceiveResendReportData = {
    body: ResendReport;
    headers: {
        /**
         * The delivery's own id. It is part of the signed base string
         * (`msg_id.timestamp.payload`), so it cannot contain a full stop — a dot
         * would let a sender append fields to a string the receiver treats as
         * verified.
         *
         * courier does **not** use it as an idempotency key, and the operation's
         * description says why: one delivery can name many recipients, and keying on
         * the header would collapse a broadcast into one suppression.
         *
         */
        'svix-id': string;
        /**
         * When the delivery was signed, as a bare integer of seconds since the epoch.
         * It must be a bare integer: the receiver builds the base string from the
         * header's own bytes, so a lenient parse would verify one string and act on
         * another.
         *
         * It is also courier's **replay window**. A signature outside ±300 seconds is
         * refused even when it is otherwise correct, which is the other half of
         * replay protection — the unique index handles a replay *inside* the window,
         * and the window handles one outside it.
         *
         */
        'svix-timestamp': number;
        /**
         * The signature, as `v1,<base64 HMAC-SHA256>` over
         * `svix-id.svix-timestamp.body`.
         *
         * **Space-delimited, and that is not incidental**: a producer rotating its key
         * sends the current and the previous signature together, and an unrecognised
         * identifier in the list is skipped rather than refused so it cannot stop the
         * `v1` entry beside it from being found. So courier's key rotation needs no
         * downtime and no coordination beyond the provider-side change.
         *
         * The comparison is constant-time. A verifier that is merely correct is not
         * enough — the scheme's own guidance is that failing to compare in constant
         * time "can expose consumers to timing-attacks and turn them into signing
         * oracles".
         *
         * The `webhook-` prefixed spellings are accepted as well, because the scheme
         * says headers "should be prefixed with `webhook-`" and Svix sends `svix-`
         * unless an account is white-labelled.
         *
         */
        'svix-signature': string;
    };
    path?: never;
    query?: never;
    url: '/inbound/resend';
};

export type ReceiveResendReportErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     * **On `receiveResendReport` this response is reachable only with a valid
     * signature**, and that is the security property rather than a limitation: the
     * signature is verified before the body is read, and the endpoint's parser is
     * deliberately skipped for that route, so an unsigned malformed body is a
     * `401` and is told nothing about whether courier could have read it. This
     * response is also what a body **larger than courier will read** gets — 1 MiB,
     * a bound that exists because the route is unauthenticated and an unbounded
     * read is a denial of service handed to whoever finds the URL, while every
     * documented provider report is a few kilobytes.
     *
     */
    400: Problem;
    /**
     * The request did not carry a valid **provider signature**, so courier did not
     * read it and **recorded nothing**. This is `receiveResendReport`'s 401, and
     * it is a response of its own rather than the `Unauthorized` every other
     * operation shares, because the two mean different things: that one is "no
     * bearer token", this one is "not from the provider".
     *
     * **The signature is checked before the body is parsed, and nothing upstream
     * decodes it either** — this operation's body is deliberately left unparsed by
     * the endpoint's `Plug.Parsers`, so the bytes that arrive are the bytes that
     * were signed. Two consequences a client should read twice:
     *
     * * **a forged request is told nothing about its payload.** An unsigned
     * request carrying malformed JSON gets this, not a `400`. A `400` would
     * confirm that courier decoded a body nobody authenticated;
     * * **a correctly-signed request carrying malformed JSON gets a `400`
     * instead.** This response is reachable *with* a valid signature, and the
     * body's `400` is reachable only that way.
     *
     * The `detail` names courier's own reason and **never repeats a value from the
     * request** — an echoed signature, id or timestamp is an oracle telling a
     * forger which part to fix. The specific reason is in courier's logs under the
     * same `trace_id`.
     *
     * **It is not courier's misconfiguration.** A courier that holds no signing
     * secret, or one it cannot decode, answers `500` instead: a route answering
     * 401 to its own misconfiguration is indistinguishable from one under attack,
     * and the operator's first question would be the wrong one. See the
     * operation's description.
     *
     */
    401: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The request **was** authentic and courier **did** read it, and it will not
     * act on it — an event type courier has not read, a bounce type outside the
     * documented vocabulary, a field the report needs and does not carry, or an
     * address that is not an address courier could send to.
     *
     * A `422` and not a `200` is the whole decision. A `200` would be courier
     * claiming it did something with a report it could not read, which is the
     * silence `Courier.Inbound.Resend` refuses: a provider that adds an event type
     * should produce a log line, not nothing. A `422` tells the provider courier
     * understood the request and will not act on it.
     *
     * A `422` and not a `400` is core's own line — 400 is for malformed syntax
     * there is no field to name for, and this report is well-formed. The body that
     * is not JSON at all is a `400` instead, and only a **signed** one can reach
     * it.
     *
     * `errors[].code` says which refusal, and `errors[].field` is named as the
     * provider's own documentation spells it (`bounce`, `to`, `type`, …) rather
     * than as a path into courier's envelope: the sender wrote `bounce`, not
     * `data.bounce`, and a field a sender cannot find in the body it sent is not a
     * field it can fix.
     *
     * **No value from the payload is echoed.** In particular a rejected address is
     * not quoted back — it is in courier's logs, and the response says only that
     * one of the addresses is not one courier could send to. The suppression table
     * has no `account_id` and is not exposed through any route, so an address in a
     * response body would be a way to query mailboxes courier holds.
     *
     */
    422: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
    /**
     * courier read the report and **could not write it**. The transaction unwound,
     * so nothing is half-recorded: no suppression without its event, and no event
     * about a mailbox courier does not hold.
     *
     * `503` and not `500`, and the same argument `sendMessage`'s `503` makes:
     * courier is fine and its database is not, which is the whole difference
     * between a provider retrying and a provider filing a bug against courier.
     *
     * **The retry is safe and it is the designed path, not a fallback.** The
     * deduplication is a unique index, so a redelivery of a report courier already
     * holds is answered `200` with `data.duplicates` above zero and writes
     * nothing. A provider that receives this should retry the same bytes.
     *
     */
    503: Problem;
};

export type ReceiveResendReportError = ReceiveResendReportErrors[keyof ReceiveResendReportErrors];

export type ReceiveResendReportResponses = {
    /**
     * The report was read; the counts say what courier did with it
     */
    200: {
        data: InboundReportCounts;
    };
};

export type ReceiveResendReportResponse = ReceiveResendReportResponses[keyof ReceiveResendReportResponses];

export type SendMessageData = {
    body: SendMessageRequest;
    headers?: {
        /**
         * A uuid the client chooses, which makes a retry of this request free.
         *
         * Send it, and a retry with the **same** key and the **same** body returns
         * the first response byte for byte with `Idempotency-Replayed: true` — for
         * `createWebhookEndpoint` that includes the signing secret, which exists in
         * exactly one response and cannot be re-derived. Without it a caller that
         * timed out cannot know whether the first attempt landed, and retrying a
         * webhook registration produces a second destination courier will sign for.
         *
         * Three cases, and a client can tell them apart by `code`:
         *
         * | you sent | you get | `code` |
         * | --- | --- | --- |
         * | same key, same body, already answered | the first response, with `Idempotency-Replayed: true` | — |
         * | same key, different body | 409 | `idempotency_key_reused` |
         * | same key, same body, first attempt still running | 409 | `conflict`; retry the same request shortly |
         *
         * Omitting the header is not an error: the request is processed normally,
         * and a retry without a key is the client's own problem. A key that is not a
         * uuid is a 422 — the header is a uuid because an unbounded string in a
         * unique index is a cost every write pays.
         *
         * The key is scoped to the `(account, endpoint, key)` triple, and `endpoint`
         * is the **concrete** path, so the same key used to test two different
         * endpoints is two different keys. Retention is 24 hours, after which the
         * key behaves as though it had never been used. Only a 2xx is stored, so a
         * request that failed leaves the key free to use again immediately.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/messages';
};

export type SendMessageErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     * **On `receiveResendReport` this response is reachable only with a valid
     * signature**, and that is the security property rather than a limitation: the
     * signature is verified before the body is read, and the endpoint's parser is
     * deliberately skipped for that route, so an unsigned malformed body is a
     * `401` and is told nothing about whether courier could have read it. This
     * response is also what a body **larger than courier will read** gets — 1 MiB,
     * a bound that exists because the route is unauthenticated and an unbounded
     * read is a denial of service handed to whoever finds the URL, while every
     * documented provider report is a few kilobytes.
     *
     */
    400: Problem;
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The recipient's mailbox cannot be written to, and courier will not write
     * to it. **A 409 and not a 422**, because this is not a property of the
     * request: a hard bounce (RFC 5321 §5.1.1, permanent failure) and a spam
     * complaint (RFC 2142 §5, an abuse report) are facts about a *mailbox*,
     * recorded by a provider and not chosen by the caller. 409 `conflict` is
     * core's own code for a request colliding with the current state of a
     * resource, and it is the status that tells a generated client **not to
     * retry**.
     *
     * The suppression list is not exposed through any route, so this response is
     * the only place the fact surfaces, and it is shaped accordingly: it does
     * **not** echo the address, and it carries no `errors[]`, because core
     * reserves that for 422 and this is not a field failure. The two states are
     * described in `detail` in words only — an operator's response to each is
     * different (a pile of `undeliverable` is list hygiene, a pile of complaints
     * is a content and sender-reputation problem), and a machine-readable code
     * here would turn this response into the one place a caller could probe the
     * list.
     *
     * `email_suppressions` carries no `account_id` by design, so this is a fact
     * about a mailbox rather than about another tenant's data, and it is the same
     * posture the send path takes when it answers "no mail went out" rather than
     * "here is a list".
     *
     */
    409: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     * On `sendMessage` this is also where a **declined preference** is answered,
     * with `errors[0].code` `notification_preferences_disabled` and
     * `errors[0].field` `type`. That is the opposite status from a suppressed
     * mailbox, and deliberately so: a decline is visible through
     * `GET /v1/notification_preferences/{user_id}` and changeable through the
     * `PUT` beside it, so telling the caller to change something is the accurate
     * answer — and `errors[]`, which core reserves for 422 and nothing else, is
     * where a client can read that without parsing prose.
     *
     */
    422: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
    /**
     * The mail provider did not accept the message, or courier is not
     * configured to deliver at all. **503 and not 500**, because courier is fine
     * and its dependency is not — which is the whole difference between a
     * generated client retrying and a generated client filing a bug against
     * courier.
     *
     * Two causes, and a caller cannot tell them apart and does not need to:
     *
     * * **the provider refused** — a relay that returned an error, a credential
     * it rejected, a socket that would not open;
     * * **courier cannot deliver** — `COURIER_MAIL_ADAPTER` names an adapter
     * that never opens a socket, or names none.
     *
     * **The retry is safe in both cases**: nothing was sent, and no outbox row
     * was written, so nothing claims a delivery that did not happen. A failed
     * request also *releases* its `Idempotency-Key` rather than storing the
     * failure, so retrying with the same key is not locked out for 24 hours.
     *
     */
    503: Problem;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * The provider accepted the message for delivery
     */
    200: {
        data: SendMessageResult;
    };
};

export type SendMessageResponse = SendMessageResponses[keyof SendMessageResponses];

export type GetNotificationPreferencesData = {
    body?: never;
    path: {
        /**
         * A uuid from identity. courier does not own users and holds no foreign key
         * to them, so this is checked for *shape* and nothing else: a non-uuid is a
         * 422 before the body is looked at, and a well-formed id courier has never
         * seen is a 200 with the defaults.
         *
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/notification_preferences/{user_id}';
};

export type GetNotificationPreferencesErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * The preferences for this user id exist and belong to another account.
     *
     * Not a 403, for the reason the webhook `NotFound` above gives: a 403 would
     * tell a caller that this user id has preferences at all, which is the only
     * fact this 404 exists to withhold.
     *
     * It is deliberately **narrow**. A user nobody has written preferences for is
     * a `200` with the defaults on both operations, because courier holds no
     * foreign key to identity's users and cannot tell an account's user from one
     * that does not exist. This response means "there is something here and it is
     * not yours", and only a stored row can make it true.
     *
     */
    404: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     * On `sendMessage` this is also where a **declined preference** is answered,
     * with `errors[0].code` `notification_preferences_disabled` and
     * `errors[0].field` `type`. That is the opposite status from a suppressed
     * mailbox, and deliberately so: a decline is visible through
     * `GET /v1/notification_preferences/{user_id}` and changeable through the
     * `PUT` beside it, so telling the caller to change something is the accurate
     * answer — and `errors[]`, which core reserves for 422 and nothing else, is
     * where a client can read that without parsing prose.
     *
     */
    422: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type GetNotificationPreferencesError = GetNotificationPreferencesErrors[keyof GetNotificationPreferencesErrors];

export type GetNotificationPreferencesResponses = {
    /**
     * Every notification type, with this user's answers
     */
    200: {
        data: NotificationPreferences;
    };
};

export type GetNotificationPreferencesResponse = GetNotificationPreferencesResponses[keyof GetNotificationPreferencesResponses];

export type UpdateNotificationPreferencesData = {
    body: {
        /**
         * The entries to store. A type or channel not named here is left
         * alone, so a client that knows about one setting can send one
         * entry without overwriting the rest.
         *
         */
        preferences: Array<{
            notification_type: NotificationType;
            email_enabled?: boolean;
            /**
             * Stored and returned because the API is the user's
             * settings, but nothing sends push, so a `true` here does
             * not mean courier will send a push.
             *
             */
            push_enabled?: boolean;
        }>;
    };
    path: {
        /**
         * A uuid from identity. courier does not own users and holds no foreign key
         * to them, so this is checked for *shape* and nothing else: a non-uuid is a
         * 422 before the body is looked at, and a well-formed id courier has never
         * seen is a 200 with the defaults.
         *
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/notification_preferences/{user_id}';
};

export type UpdateNotificationPreferencesErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     * **On `receiveResendReport` this response is reachable only with a valid
     * signature**, and that is the security property rather than a limitation: the
     * signature is verified before the body is read, and the endpoint's parser is
     * deliberately skipped for that route, so an unsigned malformed body is a
     * `401` and is told nothing about whether courier could have read it. This
     * response is also what a body **larger than courier will read** gets — 1 MiB,
     * a bound that exists because the route is unauthenticated and an unbounded
     * read is a denial of service handed to whoever finds the URL, while every
     * documented provider report is a few kilobytes.
     *
     */
    400: Problem;
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * The preferences for this user id exist and belong to another account.
     *
     * Not a 403, for the reason the webhook `NotFound` above gives: a 403 would
     * tell a caller that this user id has preferences at all, which is the only
     * fact this 404 exists to withhold.
     *
     * It is deliberately **narrow**. A user nobody has written preferences for is
     * a `200` with the defaults on both operations, because courier holds no
     * foreign key to identity's users and cannot tell an account's user from one
     * that does not exist. This response means "there is something here and it is
     * not yours", and only a stored row can make it true.
     *
     */
    404: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     * On `sendMessage` this is also where a **declined preference** is answered,
     * with `errors[0].code` `notification_preferences_disabled` and
     * `errors[0].field` `type`. That is the opposite status from a suppressed
     * mailbox, and deliberately so: a decline is visible through
     * `GET /v1/notification_preferences/{user_id}` and changeable through the
     * `PUT` beside it, so telling the caller to change something is the accurate
     * answer — and `errors[]`, which core reserves for 422 and nothing else, is
     * where a client can read that without parsing prose.
     *
     */
    422: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type UpdateNotificationPreferencesError = UpdateNotificationPreferencesErrors[keyof UpdateNotificationPreferencesErrors];

export type UpdateNotificationPreferencesResponses = {
    /**
     * The stored state, the same shape a `GET` returns
     */
    200: {
        data: NotificationPreferences;
    };
};

export type UpdateNotificationPreferencesResponse = UpdateNotificationPreferencesResponses[keyof UpdateNotificationPreferencesResponses];

export type ListWebhookEndpointsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page size. Defaults to 25, capped at 100.
         */
        limit?: number;
        /**
         * The opaque cursor from a previous page's `page.next_cursor`. Clients must
         * not parse it; courier's encoding may change without notice. A cursor
         * courier did not issue is a 422.
         *
         */
        cursor?: string;
    };
    url: '/v1/webhook_endpoints';
};

export type ListWebhookEndpointsErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     * On `sendMessage` this is also where a **declined preference** is answered,
     * with `errors[0].code` `notification_preferences_disabled` and
     * `errors[0].field` `type`. That is the opposite status from a suppressed
     * mailbox, and deliberately so: a decline is visible through
     * `GET /v1/notification_preferences/{user_id}` and changeable through the
     * `PUT` beside it, so telling the caller to change something is the accurate
     * answer — and `errors[]`, which core reserves for 422 and nothing else, is
     * where a client can read that without parsing prose.
     *
     */
    422: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type ListWebhookEndpointsError = ListWebhookEndpointsErrors[keyof ListWebhookEndpointsErrors];

export type ListWebhookEndpointsResponses = {
    /**
     * One page of endpoints
     */
    200: WebhookEndpointPage;
};

export type ListWebhookEndpointsResponse = ListWebhookEndpointsResponses[keyof ListWebhookEndpointsResponses];

export type CreateWebhookEndpointData = {
    body: {
        /**
         * An absolute http(s) URL. `file:`, `ftp:`, `gopher:`, `data:`
         * and `javascript:` are refused, as are loopback, link-local
         * (including `169.254.169.254`), RFC1918 and unique-local
         * addresses — by literal address *and* by what the host
         * resolves to.
         *
         */
        url: string;
        description?: string;
    };
    headers?: {
        /**
         * A uuid the client chooses, which makes a retry of this request free.
         *
         * Send it, and a retry with the **same** key and the **same** body returns
         * the first response byte for byte with `Idempotency-Replayed: true` — for
         * `createWebhookEndpoint` that includes the signing secret, which exists in
         * exactly one response and cannot be re-derived. Without it a caller that
         * timed out cannot know whether the first attempt landed, and retrying a
         * webhook registration produces a second destination courier will sign for.
         *
         * Three cases, and a client can tell them apart by `code`:
         *
         * | you sent | you get | `code` |
         * | --- | --- | --- |
         * | same key, same body, already answered | the first response, with `Idempotency-Replayed: true` | — |
         * | same key, different body | 409 | `idempotency_key_reused` |
         * | same key, same body, first attempt still running | 409 | `conflict`; retry the same request shortly |
         *
         * Omitting the header is not an error: the request is processed normally,
         * and a retry without a key is the client's own problem. A key that is not a
         * uuid is a 422 — the header is a uuid because an unbounded string in a
         * unique index is a cost every write pays.
         *
         * The key is scoped to the `(account, endpoint, key)` triple, and `endpoint`
         * is the **concrete** path, so the same key used to test two different
         * endpoints is two different keys. Retention is 24 hours, after which the
         * key behaves as though it had never been used. Only a 2xx is stored, so a
         * request that failed leaves the key free to use again immediately.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/webhook_endpoints';
};

export type CreateWebhookEndpointErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     * **On `receiveResendReport` this response is reachable only with a valid
     * signature**, and that is the security property rather than a limitation: the
     * signature is verified before the body is read, and the endpoint's parser is
     * deliberately skipped for that route, so an unsigned malformed body is a
     * `401` and is told nothing about whether courier could have read it. This
     * response is also what a body **larger than courier will read** gets — 1 MiB,
     * a bound that exists because the route is unauthenticated and an unbounded
     * read is a denial of service handed to whoever finds the URL, while every
     * documented provider report is a few kilobytes.
     *
     */
    400: Problem;
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The `Idempotency-Key` was reused with a different body, or its first request is still in flight. The two are distinguished by `code`.
     */
    409: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     * On `sendMessage` this is also where a **declined preference** is answered,
     * with `errors[0].code` `notification_preferences_disabled` and
     * `errors[0].field` `type`. That is the opposite status from a suppressed
     * mailbox, and deliberately so: a decline is visible through
     * `GET /v1/notification_preferences/{user_id}` and changeable through the
     * `PUT` beside it, so telling the caller to change something is the accurate
     * answer — and `errors[]`, which core reserves for 422 and nothing else, is
     * where a client can read that without parsing prose.
     *
     */
    422: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type CreateWebhookEndpointError = CreateWebhookEndpointErrors[keyof CreateWebhookEndpointErrors];

export type CreateWebhookEndpointResponses = {
    /**
     * Registered, with the signing secret
     */
    201: {
        data: WebhookEndpoint & {
            /**
             * The Standard Webhooks signing secret, base64
             * encoded behind the `whsec_` prefix. Shown once.
             *
             * This field deliberately carries NO example value.
             * A secret of this kind is not usefully
             * exemplified — the only real one a caller will
             * ever see is the one this response hands back,
             * and a made-up example in a public specification
             * costs more than it teaches: GitHub's secret
             * scanning matches the `whsec_`-plus-base64 SHAPE
             * rather than the content, this repository is
             * public, and every realistic example value pushed
             * here opened an alert that somebody then had to
             * resolve. Five were opened on 2026-10-01 and all
             * five were documentation or test fixtures.
             *
             * The `pattern` above is the machine-readable
             * contract: `whsec_`, then base64. A conforming
             * secret is 32 random bytes, so it base64-decodes
             * to nothing readable — which is also the quick
             * way to tell a real one from a fixture. The
             * third-party test vector in
             * `test/courier/inbound/signature_test.exs` is
             * svix's own published worked example and is the
             * one intentional literal in this repository; it
             * pins signature verification against a party
             * other than this repository and should not be
             * removed to satisfy a scanner. An alert on any
             * other `whsec_` value that decodes to nothing
             * readable is a real one: stop, rotate, and
             * investigate.
             *
             */
            secret: string;
        };
    };
};

export type CreateWebhookEndpointResponse = CreateWebhookEndpointResponses[keyof CreateWebhookEndpointResponses];

export type DeleteWebhookEndpointData = {
    body?: never;
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}';
};

export type DeleteWebhookEndpointErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     * **On `receiveResendReport` this response is reachable only with a valid
     * signature**, and that is the security property rather than a limitation: the
     * signature is verified before the body is read, and the endpoint's parser is
     * deliberately skipped for that route, so an unsigned malformed body is a
     * `401` and is told nothing about whether courier could have read it. This
     * response is also what a body **larger than courier will read** gets — 1 MiB,
     * a bound that exists because the route is unauthenticated and an unbounded
     * read is a denial of service handed to whoever finds the URL, while every
     * documented provider report is a few kilobytes.
     *
     */
    400: Problem;
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type DeleteWebhookEndpointError = DeleteWebhookEndpointErrors[keyof DeleteWebhookEndpointErrors];

export type DeleteWebhookEndpointResponses = {
    /**
     * Removed. No body.
     */
    204: void;
};

export type DeleteWebhookEndpointResponse = DeleteWebhookEndpointResponses[keyof DeleteWebhookEndpointResponses];

export type GetWebhookEndpointData = {
    body?: never;
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}';
};

export type GetWebhookEndpointErrors = {
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type GetWebhookEndpointError = GetWebhookEndpointErrors[keyof GetWebhookEndpointErrors];

export type GetWebhookEndpointResponses = {
    /**
     * The endpoint
     */
    200: {
        data: WebhookEndpoint;
    };
};

export type GetWebhookEndpointResponse = GetWebhookEndpointResponses[keyof GetWebhookEndpointResponses];

export type UpdateWebhookEndpointData = {
    body: {
        url?: string;
        description?: string;
        status?: WebhookEndpointStatus;
    };
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}';
};

export type UpdateWebhookEndpointErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     * **On `receiveResendReport` this response is reachable only with a valid
     * signature**, and that is the security property rather than a limitation: the
     * signature is verified before the body is read, and the endpoint's parser is
     * deliberately skipped for that route, so an unsigned malformed body is a
     * `401` and is told nothing about whether courier could have read it. This
     * response is also what a body **larger than courier will read** gets — 1 MiB,
     * a bound that exists because the route is unauthenticated and an unbounded
     * read is a denial of service handed to whoever finds the URL, while every
     * documented provider report is a few kilobytes.
     *
     */
    400: Problem;
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The request was well-formed and the thing it asked for is not allowed.
     * `errors[].code` distinguishes a typo from a refused destination.
     *
     * On `sendMessage` this is also where a **declined preference** is answered,
     * with `errors[0].code` `notification_preferences_disabled` and
     * `errors[0].field` `type`. That is the opposite status from a suppressed
     * mailbox, and deliberately so: a decline is visible through
     * `GET /v1/notification_preferences/{user_id}` and changeable through the
     * `PUT` beside it, so telling the caller to change something is the accurate
     * answer — and `errors[]`, which core reserves for 422 and nothing else, is
     * where a client can read that without parsing prose.
     *
     */
    422: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type UpdateWebhookEndpointError = UpdateWebhookEndpointErrors[keyof UpdateWebhookEndpointErrors];

export type UpdateWebhookEndpointResponses = {
    /**
     * The endpoint as it now is
     */
    200: {
        data: WebhookEndpoint;
    };
};

export type UpdateWebhookEndpointResponse = UpdateWebhookEndpointResponses[keyof UpdateWebhookEndpointResponses];

export type TestWebhookEndpointData = {
    body?: never;
    headers?: {
        /**
         * A uuid the client chooses, which makes a retry of this request free.
         *
         * Send it, and a retry with the **same** key and the **same** body returns
         * the first response byte for byte with `Idempotency-Replayed: true` — for
         * `createWebhookEndpoint` that includes the signing secret, which exists in
         * exactly one response and cannot be re-derived. Without it a caller that
         * timed out cannot know whether the first attempt landed, and retrying a
         * webhook registration produces a second destination courier will sign for.
         *
         * Three cases, and a client can tell them apart by `code`:
         *
         * | you sent | you get | `code` |
         * | --- | --- | --- |
         * | same key, same body, already answered | the first response, with `Idempotency-Replayed: true` | — |
         * | same key, different body | 409 | `idempotency_key_reused` |
         * | same key, same body, first attempt still running | 409 | `conflict`; retry the same request shortly |
         *
         * Omitting the header is not an error: the request is processed normally,
         * and a retry without a key is the client's own problem. A key that is not a
         * uuid is a 422 — the header is a uuid because an unbounded string in a
         * unique index is a cost every write pays.
         *
         * The key is scoped to the `(account, endpoint, key)` triple, and `endpoint`
         * is the **concrete** path, so the same key used to test two different
         * endpoints is two different keys. Retention is 24 hours, after which the
         * key behaves as though it had never been used. Only a 2xx is stored, so a
         * request that failed leaves the key free to use again immediately.
         *
         */
        'Idempotency-Key'?: string;
    };
    path: {
        /**
         * The endpoint's uuid.
         */
        id: string;
    };
    query?: never;
    url: '/v1/webhook_endpoints/{id}/test';
};

export type TestWebhookEndpointErrors = {
    /**
     * The body was not the shape courier was sent. This is 400 and not 422
     * because a client could not have known: the request never parsed, so
     * there is no field to name and nothing to correct.
     *
     * **On `receiveResendReport` this response is reachable only with a valid
     * signature**, and that is the security property rather than a limitation: the
     * signature is verified before the body is read, and the endpoint's parser is
     * deliberately skipped for that route, so an unsigned malformed body is a
     * `401` and is told nothing about whether courier could have read it. This
     * response is also what a body **larger than courier will read** gets — 1 MiB,
     * a bound that exists because the route is unauthenticated and an unbounded
     * read is a denial of service handed to whoever finds the URL, while every
     * documented provider report is a few kilobytes.
     *
     */
    400: Problem;
    /**
     * No authenticated caller. courier does not guess an account for an
     * anonymous request.
     *
     * **Not this operation's 401.** `receiveResendReport` authenticates by
     * signature rather than by token, and its 401 means something else — see
     * `SignatureRejected`, which is a response of its own for exactly that reason.
     *
     */
    401: Problem;
    /**
     * No such endpoint, for this account. An endpoint belonging to another
     * account is also a 404: core's conventions forbid a 403 here, because it
     * leaks the existence of a resource the caller cannot see.
     *
     */
    404: Problem;
    /**
     * The request's `Accept` header does not include `application/json`, so
     * Phoenix's `:accepts` plug refused to route it. This is the client naming a
     * media type courier cannot answer, and courier says so with
     * `not_acceptable` rather than with `internal`: an earlier version of courier
     * fell through to the `:internal` default here and reported a client that had
     * asked for `text/html` as courier having failed, which is the one code every
     * generated client retries. Reachable on every operation in this document.
     *
     */
    406: Problem;
    /**
     * The `Idempotency-Key` was reused with a different body, or its first request is still in flight. The two are distinguished by `code`.
     */
    409: Problem;
    /**
     * courier failed and the client did nothing wrong. **Every operation in this
     * document can answer this one**: it is what `Phoenix.Endpoint.RenderErrors`
     * renders for any unhandled raise, including a database that has stopped
     * answering. The envelope is courier's and carries the request's
     * `trace_id`; the cause is in courier's logs under that id and is not
     * repeated to the caller, because these bodies are read by anyone who can
     * reach the service.
     *
     */
    500: Problem;
};

export type TestWebhookEndpointError = TestWebhookEndpointErrors[keyof TestWebhookEndpointErrors];

export type TestWebhookEndpointResponses = {
    /**
     * The ping was sent; `delivered` says whether it was accepted
     */
    200: {
        data: {
            /**
             * Whether the receiver answered 2xx.
             */
            delivered: boolean;
            /**
             * The receiver's status, or null if nothing answered.
             */
            status_code: number;
            /**
             * How long the attempt took.
             */
            duration_ms: number;
        };
    };
};

export type TestWebhookEndpointResponse = TestWebhookEndpointResponses[keyof TestWebhookEndpointResponses];
