/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/darkroom.yaml
//         darkroom, document version 1.0.0,
//         vendored from git@github.com:cafaye/darkroom.git
//         at commit fdb3455b2737bbbb0b978a75171ab5576f91d202
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export { completeUpload, createUpload, createVariant, deleteAsset, getAsset, healthz, listAssets, listVariants, type Options, readyz } from './sdk.gen.js';
export type { Asset, AssetId, AssetKind, AssetList, AssetStatus, AssetVariant, ClientOptions, CompleteUploadData, CompleteUploadError, CompleteUploadErrors, CompleteUploadRequest, CompleteUploadResponse, CompleteUploadResponse2, CompleteUploadResponses, CreateUploadData, CreateUploadError, CreateUploadErrors, CreateUploadRequest, CreateUploadResponse, CreateUploadResponse2, CreateUploadResponses, CreateVariantData, CreateVariantError, CreateVariantErrors, CreateVariantResponse, CreateVariantResponses, DeleteAssetData, DeleteAssetError, DeleteAssetErrors, DeleteAssetResponse, DeleteAssetResponses, GetAssetData, GetAssetError, GetAssetErrors, GetAssetResponse, GetAssetResponses, HealthzData, HealthzResponse, HealthzResponses, IdempotencyKey, ListAssetsData, ListAssetsError, ListAssetsErrors, ListAssetsResponse, ListAssetsResponses, ListVariantsData, ListVariantsError, ListVariantsErrors, ListVariantsResponse, ListVariantsResponses, Page, Probe, Problem, ReadyzData, ReadyzError, ReadyzErrors, ReadyzResponse, ReadyzResponses, VariantList } from './types.gen.js';
