/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/darkroom.yaml
//         darkroom, document version 1.0.0,
//         vendored from git@github.com:cafaye/darkroom.git
//         at commit bcaa2fe381b7f5d5047a3de862612fc2f81ad059
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CompleteUploadData, CompleteUploadErrors, CompleteUploadResponses, CreateUploadData, CreateUploadErrors, CreateUploadResponses, CreateVariantData, CreateVariantErrors, CreateVariantResponses, DeleteAssetData, DeleteAssetErrors, DeleteAssetResponses, GetAssetData, GetAssetErrors, GetAssetResponses, HealthzData, HealthzResponses, ListAssetsData, ListAssetsErrors, ListAssetsResponses, ListVariantsData, ListVariantsErrors, ListVariantsResponses, ReadyzData, ReadyzErrors, ReadyzResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness
 *
 * Unconditional. Never touches the database or object storage: a database
 * outage must not get the process restarted out from under in-flight
 * uploads. That is `/readyz`'s job.
 *
 */
export const healthz = <ThrowOnError extends boolean = false>(options?: Options<HealthzData, ThrowOnError>): RequestResult<HealthzResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Readiness
 *
 * Executes `select 1` against this service's own database. A probe that
 * returns 200 blindly is worse than no probe: it tells the load balancer
 * to send traffic to a process that cannot serve a request.
 *
 * On failure the response names the dependency; the underlying error goes
 * to the log, never to an unauthenticated caller.
 *
 */
export const readyz = <ThrowOnError extends boolean = false>(options?: Options<ReadyzData, ThrowOnError>): RequestResult<ReadyzResponses, ReadyzErrors, ThrowOnError> => (options?.client ?? client).get<ReadyzResponses, ReadyzErrors, ThrowOnError>({ url: '/readyz', ...options });

/**
 * Create an upload and presign its destination
 *
 * Creates a `pending` asset and returns a presigned PUT URL. The bytes do
 * not move yet.
 *
 * The URL is scoped on **three** axes: exactly one storage key, one
 * content type, and one maximum size, and it expires **900 seconds (15
 * minutes)** after it is issued. A URL that permits any key is a URL that
 * permits overwriting another tenant's object.
 *
 * **Idempotent.** Accepts `Idempotency-Key`. A replay with the same key
 * and the same body returns this same response with
 * `Idempotency-Replayed: true` and creates no second asset. The same key
 * with a different body is `409 idempotency_key_reused`.
 *
 * **Duplicates.** If this account already has an asset with this
 * checksum, the existing asset is returned with `201` and
 * `X-Darkroom-Duplicate: true`, with a fresh presigned URL for its key.
 * The one case that is a `409` is a duplicate of an asset that previously
 * **failed** — its checksum was never verified against real bytes, so
 * handing it back would return something unusable.
 *
 */
export const createUpload = <ThrowOnError extends boolean = false>(options: Options<CreateUploadData, ThrowOnError>): RequestResult<CreateUploadResponses, CreateUploadErrors, ThrowOnError> => (options.client ?? client).post<CreateUploadResponses, CreateUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/uploads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify the uploaded object and mark the asset ready
 *
 * Reads the object's metadata, computes the sha256 of what storage
 * actually holds, and compares it to the claimed checksum. On a match the
 * asset becomes `ready` and `darkroom.asset.ready` is written to the
 * outbox **in the same transaction**.
 *
 * On a mismatch the asset becomes `failed` and the answer is `422`. On an
 * absent object it becomes `failed` and the answer is `409`.
 *
 * **Idempotent.** Accepts `Idempotency-Key`. A replay returns the
 * original response and emits no second event.
 *
 */
export const completeUpload = <ThrowOnError extends boolean = false>(options: Options<CompleteUploadData, ThrowOnError>): RequestResult<CompleteUploadResponses, CompleteUploadErrors, ThrowOnError> => (options.client ?? client).post<CompleteUploadResponses, CompleteUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/uploads/{id}/complete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the caller's account's assets
 *
 * Cursor-paginated and scoped to the `account_id` in the caller's token.
 * An asset belonging to another account is simply not in the result, and
 * the total count does not include it either.
 *
 */
export const listAssets = <ThrowOnError extends boolean = false>(options?: Options<ListAssetsData, ThrowOnError>): RequestResult<ListAssetsResponses, ListAssetsErrors, ThrowOnError> => (options?.client ?? client).get<ListAssetsResponses, ListAssetsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/assets',
    ...options
});

/**
 * Delete an asset
 *
 * Removes the row, removes the storage objects — the original **and every
 * variant** — and writes `darkroom.asset.deleted` to the outbox in the
 * same transaction.
 *
 * Objects are deleted before the row commits. A row that says "gone" while
 * a gigabyte of objects survives is a leak nobody will ever find, whereas
 * an object removed just before a rolled-back row is recoverable.
 *
 * Idempotent: a second delete is `404`, not a `500`.
 *
 */
export const deleteAsset = <ThrowOnError extends boolean = false>(options: Options<DeleteAssetData, ThrowOnError>): RequestResult<DeleteAssetResponses, DeleteAssetErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAssetResponses, DeleteAssetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/assets/{id}',
    ...options
});

/**
 * Fetch one asset
 *
 * Scoped to the caller's account. An asset belonging to another account
 * returns `404` with a body **identical** to the one returned for an id
 * that never existed — a `403` would be an asset-id oracle.
 *
 */
export const getAsset = <ThrowOnError extends boolean = false>(options: Options<GetAssetData, ThrowOnError>): RequestResult<GetAssetResponses, GetAssetErrors, ThrowOnError> => (options.client ?? client).get<GetAssetResponses, GetAssetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/assets/{id}',
    ...options
});

/**
 * List an asset's variants
 *
 * Scoped to the caller's account. An asset belonging to another account
 * returns `404`, **not** an empty list — an empty list would be
 * indistinguishable from "this asset has no variants yet", which is an
 * existence oracle with one bit.
 *
 */
export const listVariants = <ThrowOnError extends boolean = false>(options: Options<ListVariantsData, ThrowOnError>): RequestResult<ListVariantsResponses, ListVariantsErrors, ThrowOnError> => (options.client ?? client).get<ListVariantsResponses, ListVariantsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/assets/{id}/variants',
    ...options
});

/**
 * Generate a derived image
 *
 * Decodes the original, bounds it to the kind's box, and re-encodes it.
 * The original row and its object are **never** touched — the variant is a
 * separate row pointing at a separate key.
 *
 * Every variant is JPEG. WebP would be better and is deliberately not
 * used: the `image` crate's WebP encoder is lossless-only, so lossy WebP
 * is a dependency decision for a later packet rather than a silent C
 * dependency here.
 *
 * Re-requesting a kind replaces that variant rather than accumulating
 * rows.
 *
 */
export const createVariant = <ThrowOnError extends boolean = false>(options: Options<CreateVariantData, ThrowOnError>): RequestResult<CreateVariantResponses, CreateVariantErrors, ThrowOnError> => (options.client ?? client).post<CreateVariantResponses, CreateVariantErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/assets/{id}/variants',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
