/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/darkroom.yaml
//         darkroom, document version 1.0.0,
//         vendored from git@github.com:cafaye/darkroom.git
//         at commit fdb3455b2737bbbb0b978a75171ab5576f91d202
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export type ClientOptions = {
    baseUrl: 'https://darkroom.cafaye.com' | 'http://localhost:8080' | (string & {});
};

/**
 * The cafaye error envelope: RFC 9457 plus core's `code` and `trace_id`.
 * Every non-2xx response from this service is this shape.
 *
 */
export type Problem = {
    type: string;
    /**
     * A fixed summary for the code. May be reworded without a version bump.
     */
    title: string;
    status: number;
    /**
     * Specific to this occurrence, never parsed by clients. Never contains
     * an internal error, a host, a role or a query fragment.
     *
     */
    detail: string;
    /**
     * The request path, never including the query string.
     */
    instance: string;
    code: 'unauthorized' | 'forbidden' | 'not_found' | 'conflict' | 'validation_failed' | 'rate_limited' | 'idempotency_key_reused' | 'internal' | 'unavailable';
    /**
     * Always present, always equal to the `X-Trace-Id` header.
     */
    trace_id: string;
    /**
     * Present only on 422.
     */
    errors?: Array<{
        field: string;
        code: string;
    }>;
};

export type Probe = {
    status: 'ok' | 'ready';
};

/**
 * Derived server-side from `content_type`, never client-supplied. A `kind`
 * chooses the decoder, so a client that could set one could route a
 * request through a decoder it should not reach.
 *
 */
export type AssetKind = 'image' | 'audio' | 'video' | 'document';

/**
 * `pending` means a URL was issued and nothing is confirmed. `ready` and
 * `failed` are both terminal.
 *
 */
export type AssetStatus = 'pending' | 'ready' | 'failed';

/**
 * There is deliberately no `storage_key` field. The key is a server-side
 * implementation detail of where the bytes live, and a client that can
 * read it will eventually try to build a URL from it.
 *
 */
export type Asset = {
    id: string;
    /**
     * Taken from the caller's token, never from the request.
     */
    account_id: string;
    /**
     * `sub` — the user who created the upload.
     */
    owner_user_id: string;
    kind: AssetKind;
    original_filename: string;
    content_type: string;
    byte_size: number;
    /**
     * Lowercase sha256 of the bytes **as stored**. Not the client's claim —
     * the claim is verified at complete time and replaced by the computed
     * value.
     *
     */
    checksum: string;
    status: AssetStatus;
    /**
     * Free-form. On a `failed` asset it carries `failure_reason`:
     * `object_absent_at_complete` or `checksum_mismatch`.
     *
     */
    metadata: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
};

export type AssetVariant = {
    id: string;
    asset_id: string;
    account_id: string;
    kind: 'thumbnail' | 'preview' | 'web';
    content_type: string;
    byte_size: number;
    /**
     * The derived image's width. Null for a non-visual variant.
     */
    width?: number | null;
    height?: number | null;
    /**
     * Carries `source_asset_id`, `source_checksum`, and the source's dimensions.
     */
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
};

export type CreateUploadRequest = {
    /**
     * Must not contain a path separator or control characters. It is not
     * used to build any path — the storage key is opaque and server
     * generated.
     *
     */
    filename: string;
    /**
     * An allow-list. Parameters (`; charset=utf-8`) are ignored and the
     * comparison is case-insensitive. An unsupported type is a `422`
     * naming `content_type`.
     *
     */
    content_type: string;
    /**
     * Caps the presigned URL. 1 GiB, deliberately under S3's 5 GiB single
     * PUT limit so that "presigned PUT" never becomes "multipart upload",
     * which would be a second flow with a second set of URLs.
     *
     */
    byte_size: number;
    /**
     * The sha256 the client is about to upload. Required, and validated
     * for shape here so a malformed one is a `422` now rather than a
     * `422` after a gigabyte has been uploaded. It is a **claim**; it is
     * verified against storage at complete time.
     *
     */
    checksum: string;
    [key: string]: unknown;
};

export type CreateUploadResponse = {
    asset: Asset;
    /**
     * Presigned PUT. Scoped to exactly this `storage_key`, this
     * `content_type`, and `byte_size` as a ceiling. Expires in
     * `expires_in_secs`.
     *
     */
    upload_url: string;
    /**
     * The one key this URL may write to. Opaque and server-generated.
     */
    storage_key: string;
    /**
     * 900 seconds (15 minutes). Short on purpose.
     */
    expires_in_secs: number;
    /**
     * The exact `Content-Type` the PUT must send. Storage rejects anything else.
     */
    content_type: string;
    /**
     * Headers the client must send on the PUT.
     */
    headers?: {
        [key: string]: string;
    };
    /**
     * True when this resolved to an asset that already existed.
     */
    duplicate: boolean;
};

export type CompleteUploadRequest = {
    /**
     * The checksum the client claims the stored object has. Checked
     * against what storage actually holds; never trusted.
     *
     */
    checksum: string;
};

export type CompleteUploadResponse = {
    asset: Asset;
};

export type Page = {
    /**
     * Opaque. Null on the last page.
     */
    next_cursor: string | null;
    has_more: boolean;
};

export type AssetList = {
    data: Array<Asset>;
    page: Page;
};

export type VariantList = {
    data: Array<AssetVariant>;
    page: Page;
};

export type AssetId = string;

/**
 * Client-chosen, scoped to `(endpoint, principal, key)`. A replay with the
 * same key and the same body returns the original response; the same key
 * with a different body is `409 idempotency_key_reused`.
 *
 * Requests without the key are processed normally.
 *
 */
export type IdempotencyKey = string;

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    /**
     * The process is alive.
     */
    200: Probe;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type ReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzErrors = {
    /**
     * A dependency is not answering. Body is a Problem.
     */
    503: Problem;
};

export type ReadyzError = ReadyzErrors[keyof ReadyzErrors];

export type ReadyzResponses = {
    /**
     * The service can serve traffic.
     */
    200: Probe;
};

export type ReadyzResponse = ReadyzResponses[keyof ReadyzResponses];

export type CreateUploadData = {
    body: CreateUploadRequest;
    headers?: {
        /**
         * Client-chosen, scoped to `(endpoint, principal, key)`. A replay with the
         * same key and the same body returns the original response; the same key
         * with a different body is `409 idempotency_key_reused`.
         *
         * Requests without the key are processed normally.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/uploads';
};

export type CreateUploadErrors = {
    /**
     * Malformed request syntax.
     */
    400: Problem;
    /**
     * No credential, or one that did not verify.
     */
    401: Problem;
    /**
     * Authenticated, but the token lacks the required scope. Never used for a
     * resource under another account — that is a `404`.
     *
     */
    403: Problem;
    /**
     * The key was reused with a different body, or the duplicate previously failed.
     */
    409: Problem;
    /**
     * The request body exceeded 4096 bytes.
     */
    413: Problem;
    /**
     * Semantically wrong. `errors[]` lists the per-field failures.
     */
    422: Problem;
    /**
     * A dependency is not answering. Safe to retry.
     */
    503: Problem;
};

export type CreateUploadError = CreateUploadErrors[keyof CreateUploadErrors];

export type CreateUploadResponses = {
    /**
     * The asset exists in `pending`, and the URL is ready to use.
     */
    201: CreateUploadResponse;
};

export type CreateUploadResponse2 = CreateUploadResponses[keyof CreateUploadResponses];

export type CompleteUploadData = {
    body: CompleteUploadRequest;
    headers?: {
        /**
         * Client-chosen, scoped to `(endpoint, principal, key)`. A replay with the
         * same key and the same body returns the original response; the same key
         * with a different body is `409 idempotency_key_reused`.
         *
         * Requests without the key are processed normally.
         *
         */
        'Idempotency-Key'?: string;
    };
    path: {
        /**
         * The asset id returned by `POST /v1/uploads`.
         */
        id: string;
    };
    query?: never;
    url: '/v1/uploads/{id}/complete';
};

export type CompleteUploadErrors = {
    /**
     * Malformed request syntax.
     */
    400: Problem;
    /**
     * No credential, or one that did not verify.
     */
    401: Problem;
    /**
     * Authenticated, but the token lacks the required scope. Never used for a
     * resource under another account — that is a `404`.
     *
     */
    403: Problem;
    /**
     * No such asset **in the caller's account**.
     */
    404: Problem;
    /**
     * No object was found at the presigned key, or the upload has already
     * failed. The asset is now `failed`.
     *
     */
    409: Problem;
    /**
     * The claimed checksum does not match the bytes in storage. The asset
     * is now `failed`.
     *
     */
    422: Problem;
    /**
     * A dependency is not answering. Safe to retry.
     */
    503: Problem;
};

export type CompleteUploadError = CompleteUploadErrors[keyof CompleteUploadErrors];

export type CompleteUploadResponses = {
    /**
     * The bytes are in storage and the checksum matched.
     */
    200: CompleteUploadResponse;
};

export type CompleteUploadResponse2 = CompleteUploadResponses[keyof CompleteUploadResponses];

export type ListAssetsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Defaults to 25, capped at 100. A larger request is clamped, not rejected.
         */
        limit?: number;
        /**
         * Opaque base64url. Clients must not parse it.
         */
        cursor?: string;
        order?: 'asc' | 'desc';
    };
    url: '/v1/assets';
};

export type ListAssetsErrors = {
    /**
     * Malformed request syntax.
     */
    400: Problem;
    /**
     * No credential, or one that did not verify.
     */
    401: Problem;
    /**
     * Authenticated, but the token lacks the required scope. Never used for a
     * resource under another account — that is a `404`.
     *
     */
    403: Problem;
    /**
     * Semantically wrong. `errors[]` lists the per-field failures.
     */
    422: Problem;
    /**
     * A dependency is not answering. Safe to retry.
     */
    503: Problem;
};

export type ListAssetsError = ListAssetsErrors[keyof ListAssetsErrors];

export type ListAssetsResponses = {
    /**
     * One page. `data` is always an array, empty rather than absent.
     */
    200: AssetList;
};

export type ListAssetsResponse = ListAssetsResponses[keyof ListAssetsResponses];

export type DeleteAssetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/assets/{id}';
};

export type DeleteAssetErrors = {
    /**
     * No credential, or one that did not verify.
     */
    401: Problem;
    /**
     * Authenticated, but the token lacks the required scope. Never used for a
     * resource under another account — that is a `404`.
     *
     */
    403: Problem;
    /**
     * No such asset **in the caller's account**.
     */
    404: Problem;
    /**
     * A dependency is not answering. Safe to retry.
     */
    503: Problem;
};

export type DeleteAssetError = DeleteAssetErrors[keyof DeleteAssetErrors];

export type DeleteAssetResponses = {
    /**
     * Deleted. The storage objects are gone.
     */
    204: void;
};

export type DeleteAssetResponse = DeleteAssetResponses[keyof DeleteAssetResponses];

export type GetAssetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/assets/{id}';
};

export type GetAssetErrors = {
    /**
     * No credential, or one that did not verify.
     */
    401: Problem;
    /**
     * Authenticated, but the token lacks the required scope. Never used for a
     * resource under another account — that is a `404`.
     *
     */
    403: Problem;
    /**
     * No such asset **in the caller's account**.
     */
    404: Problem;
    /**
     * A dependency is not answering. Safe to retry.
     */
    503: Problem;
};

export type GetAssetError = GetAssetErrors[keyof GetAssetErrors];

export type GetAssetResponses = {
    /**
     * The asset.
     */
    200: {
        asset: Asset;
    };
};

export type GetAssetResponse = GetAssetResponses[keyof GetAssetResponses];

export type ListVariantsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/assets/{id}/variants';
};

export type ListVariantsErrors = {
    /**
     * No credential, or one that did not verify.
     */
    401: Problem;
    /**
     * Authenticated, but the token lacks the required scope. Never used for a
     * resource under another account — that is a `404`.
     *
     */
    403: Problem;
    /**
     * No such asset **in the caller's account**.
     */
    404: Problem;
    /**
     * A dependency is not answering. Safe to retry.
     */
    503: Problem;
};

export type ListVariantsError = ListVariantsErrors[keyof ListVariantsErrors];

export type ListVariantsResponses = {
    /**
     * The asset's variants.
     */
    200: VariantList;
};

export type ListVariantsResponse = ListVariantsResponses[keyof ListVariantsResponses];

export type CreateVariantData = {
    body: {
        /**
         * * `thumbnail` — longest edge bounded to 256px.
         * * `preview` — longest edge bounded to 1024px.
         * * `web` — re-encoded at original dimensions; converts
         * without resizing.
         *
         * Never upscales: a 100px image asked for as a 256px thumbnail
         * stays 100px.
         *
         */
        kind: 'thumbnail' | 'preview' | 'web';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/assets/{id}/variants';
};

export type CreateVariantErrors = {
    /**
     * Malformed request syntax.
     */
    400: Problem;
    /**
     * No credential, or one that did not verify.
     */
    401: Problem;
    /**
     * Authenticated, but the token lacks the required scope. Never used for a
     * resource under another account — that is a `404`.
     *
     */
    403: Problem;
    /**
     * No such asset **in the caller's account**.
     */
    404: Problem;
    /**
     * The asset is not `ready`, is not an image, or the stored bytes are
     * not a readable image of the declared type.
     *
     */
    422: Problem;
    /**
     * A dependency is not answering. Safe to retry.
     */
    503: Problem;
};

export type CreateVariantError = CreateVariantErrors[keyof CreateVariantErrors];

export type CreateVariantResponses = {
    /**
     * The variant exists and is readable.
     */
    201: {
        variant: AssetVariant;
    };
};

export type CreateVariantResponse = CreateVariantResponses[keyof CreateVariantResponses];
