/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/muse.yaml
//         muse, document version 1.0.0,
//         vendored from git@github.com:cafaye/muse.git
//         at commit 5056ffa22c33b3ddd502331bd38fe83a392dca2b
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { type Client, type ClientOptions, type Config, createClient, createConfig } from './client/index.js';
import type { ClientOptions as ClientOptions2 } from './types.gen.js';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (override?: Config<ClientOptions & T>) => Config<Required<ClientOptions> & T>;

export const client: Client = createClient(createConfig<ClientOptions2>({ baseUrl: 'https://muse.cafaye.com' }));
