/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/muse.yaml
//         muse, document version 1.1.0,
//         vendored from git@github.com:cafaye/muse.git
//         at commit 53b6ebb1947eeb1ff90a4cfaff75897f358dc2e9
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export { type Options, routeCompletion } from './sdk.gen.js';
export type { Choice, ClientOptions, FieldError, Message, Problem, Role, RouteCompletionData, RouteCompletionError, RouteCompletionErrors, RouteCompletionResponse, RouteCompletionResponses, RouteRequest, RouteResponse, Usage } from './types.gen.js';
