/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/muse.yaml
//         muse, document version 1.1.0,
//         vendored from git@github.com:cafaye/muse.git
//         at commit 53b6ebb1947eeb1ff90a4cfaff75897f358dc2e9
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { RouteCompletionData, RouteCompletionErrors, RouteCompletionResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Route a chat completion
 *
 * Serves a completion from the first candidate that succeeds for the named
 * route, in the order `config/routes.yaml` lists them. A transient failure is
 * retried with exponential backoff; a permanent one advances immediately. If
 * every candidate fails, the whole chain is reported in one 503.
 *
 * The caller does not choose a provider. That is what makes the fallback chain
 * possible, and it is why a request cannot be pinned to a vendor.
 *
 */
export const routeCompletion = <ThrowOnError extends boolean = false>(options: Options<RouteCompletionData, ThrowOnError>): RequestResult<RouteCompletionResponses, RouteCompletionErrors, ThrowOnError> => (options.client ?? client).post<RouteCompletionResponses, RouteCompletionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/route',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
