/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/muse.yaml
//         muse, document version 1.0.0,
//         vendored from git@github.com:cafaye/muse.git
//         at commit 5056ffa22c33b3ddd502331bd38fe83a392dca2b
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export type ClientOptions = {
    baseUrl: 'https://muse.cafaye.com' | 'http://localhost:8000' | (string & {});
};

/**
 * OpenAI's set, which is a superset of what the vendors need.
 */
export type Role = 'system' | 'user' | 'assistant';

export type Message = {
    role: Role;
    /**
     * The message text. Must not be empty: an empty message is never what a
     * caller meant, and accepting it turns a client bug into a billed response
     * with no content.
     *
     */
    content: string;
};

export type RouteRequest = {
    /**
     * A route name from this service's `config/routes.yaml` — currently `fast`
     * and `smart`. Not a vendor model id: which vendor serves it is this
     * service's decision, and letting a caller name one would defeat the
     * fallback chain.
     *
     */
    model: string;
    /**
     * The conversation, oldest message first. Order is significant.
     */
    messages: Array<Message>;
    /**
     * A cap on the response. Omitted means the provider's default. A null is
     * not sent to the provider at all — some vendors reject it.
     *
     */
    max_tokens?: number;
    /**
     * Sampling temperature, passed through unchanged.
     */
    temperature?: number;
};

export type Choice = {
    /**
     * Always 0. `n > 1` is not supported in this version.
     */
    index: 0;
    message: {
        role: 'assistant';
        content: string;
    };
    /**
     * Why the model stopped. `stop` means it finished; `length` means it was
     * cut off at `max_tokens`. A caller that cannot tell those apart will treat
     * a truncated answer as a complete one.
     *
     */
    finish_reason: string;
};

export type Usage = {
    prompt_tokens: number;
    completion_tokens: number;
    /**
     * The sum of the two, computed by this service rather than reported, so a provider that reports them inconsistently cannot make the three disagree.
     */
    total_tokens: number;
};

export type RouteResponse = {
    /**
     * This service's identifier for the completion. Not the provider's own id:
     * a caller's fallback chain produces one id for one request, whatever
     * vendor ended up serving it.
     *
     */
    id: string;
    object: 'chat.completion';
    /**
     * Unix seconds, for compatibility with OpenAI-shaped clients.
     */
    created: number;
    /**
     * The vendor's model id that actually served the request.
     */
    model: string;
    /**
     * The vendor that served it. Present so an operator can reconcile against a
     * provider's invoice; a caller does not need it to make a decision, because
     * the next request may be served by a different one.
     *
     */
    provider: string;
    /**
     * The route that was used — the name the caller asked for. Distinct from
     * `model`, and it stays meaningful when a fallback changes vendor.
     *
     */
    route: string;
    choices: [
        Choice
    ];
    usage: Usage;
    /**
     * The cost of this completion in micro-dollars (1 USD = 1,000,000 micros).
     * An integer, never a float: a float that rounds differently on two machines
     * is a reconciliation bug nobody can reproduce. This is the same value the
     * `muse.tokens.consumed` event carries.
     *
     */
    cost_micros: number;
    /**
     * Matches the `X-Trace-Id` response header.
     */
    trace_id: string;
};

export type FieldError = {
    /**
     * Dotted path to the offending field, e.g. `messages.0.role`.
     */
    field: string;
    /**
     * The validator's code for this failure.
     */
    code: string;
};

/**
 * RFC 9457 problem details, with cafaye's extensions.
 */
export type Problem = {
    /**
     * Stable, machine-readable: `https://errors.cafaye.com/<code>`. The last
     * segment is always the same slug as `code`.
     *
     */
    type: string;
    /**
     * A fixed human-readable summary for the code. It may be reworded without a
     * version bump, so do not parse it.
     *
     */
    title: string;
    /**
     * The HTTP status code, repeated in the body for a log.
     */
    status: number;
    /**
     * Specific to this occurrence, and not parsed by clients. For a 503 it names
     * each provider that was tried, the error class, and the attempt count.
     *
     */
    detail: string;
    /**
     * The path that was requested.
     */
    instance: string;
    /**
     * cafaye's reserved error code. The enum is the subset this service
     * returns; the full reserved list includes codes a gateway returns instead.
     *
     */
    code: 'unauthorized' | 'forbidden' | 'not_found' | 'conflict' | 'validation_failed' | 'rate_limited' | 'internal' | 'unavailable';
    /**
     * Always present, and always equal to the `X-Trace-Id` header.
     */
    trace_id: string;
    /**
     * Per-field failures. Present only on a 422.
     */
    errors?: Array<FieldError>;
};

export type RouteCompletionData = {
    body: RouteRequest;
    headers?: {
        /**
         * W3C trace context to continue. When present and well formed, muse joins
         * that trace and propagates the context to the provider. When absent or
         * malformed, muse starts a new trace — a broken correlation header is never
         * an error, because it must not be able to fail a customer's request.
         *
         */
        traceparent?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/route';
};

export type RouteCompletionErrors = {
    /**
     * No bearer credential was supplied.
     */
    401: Problem;
    /**
     * No route is configured for the requested model.
     */
    404: Problem;
    /**
     * The path exists but not for this method. A completion costs money, so it is POST-only and there is nothing safe to serve on a GET.
     */
    405: Problem;
    /**
     * The request body is not a valid route request. `errors[]` lists each
     * offending field.
     *
     * A malformed JSON body is also a 422 rather than a 400: cafaye's
     * `validation_failed` code is a documented 422, and a 400 carrying it would
     * be a code whose status disagrees with the reserved list.
     *
     */
    422: Problem;
    /**
     * muse failed. The body carries no detail beyond the code and the trace id;
     * the log line does. This includes a failure to record the completion's
     * usage, which is deliberately not swallowed — the completion was paid for
     * and returning it without its metered record would lose the spend.
     *
     */
    500: Problem;
    /**
     * Every candidate for the route failed. `detail` names each provider, the
     * error class, and how many attempts it took.
     *
     * This is `unavailable` rather than `internal` because muse is up and the
     * models are not — the one case where retrying the same request is
     * reasonable.
     *
     */
    503: Problem;
};

export type RouteCompletionError = RouteCompletionErrors[keyof RouteCompletionErrors];

export type RouteCompletionResponses = {
    /**
     * A completion. One `muse.tokens.consumed` event was emitted.
     */
    200: RouteResponse;
};

export type RouteCompletionResponse = RouteCompletionResponses[keyof RouteCompletionResponses];
