/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/identity.yaml
//         identity, document version 1.2.0,
//         vendored from git@github.com:cafaye/identity.git
//         at commit 35c2576ede65ad3bc7daf3696fb77c0b0ffa54a3
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CompleteSecondFactorData, CompleteSecondFactorErrors, CompleteSecondFactorResponses, ConfirmMfaEnrollmentData, ConfirmMfaEnrollmentErrors, ConfirmMfaEnrollmentResponses, CreateSessionData, CreateSessionErrors, CreateSessionResponses, DeleteSessionData, DeleteSessionErrors, DeleteSessionResponses, DisableMfaData, DisableMfaErrors, DisableMfaResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetMfaStatusData, GetMfaStatusErrors, GetMfaStatusResponses, GetOidcClientData, GetOidcClientErrors, GetOidcClientResponses, ListOidcClientsData, ListOidcClientsErrors, ListOidcClientsResponses, LivenessData, LivenessResponses, ReadinessData, ReadinessErrors, ReadinessResponses, RegenerateMfaRecoveryCodesData, RegenerateMfaRecoveryCodesErrors, RegenerateMfaRecoveryCodesResponses, RegisterOidcClientData, RegisterOidcClientErrors, RegisterOidcClientResponses, RegisterUserData, RegisterUserErrors, RegisterUserResponses, RevokeOidcClientData, RevokeOidcClientErrors, RevokeOidcClientResponses, StartMfaEnrollmentData, StartMfaEnrollmentErrors, StartMfaEnrollmentResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Register an account
 *
 * Creates a user and, in the same database transaction, records an
 * `identity.user.created` event. Either both exist or neither does: a user
 * that exists without its event would never be announced, and an event
 * without its user would announce a registration that did not happen.
 *
 * Does not create a session. Sign in separately with `POST /v1/session`.
 *
 * This is the only endpoint that reveals whether an address is already
 * registered, and it answers 409. Everywhere else, "no such account" and
 * "wrong password" are indistinguishable.
 *
 */
export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>): RequestResult<RegisterUserResponses, RegisterUserErrors, ThrowOnError> => (options.client ?? client).post<RegisterUserResponses, RegisterUserErrors, ThrowOnError>({
    url: '/v1/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Log out
 *
 * Revokes the session the presented credential names, and clears the
 * session cookie. The token stops working on both surfaces immediately: a
 * `GET /v1/me` with the revoked token is a 401 on the cookie and on the
 * bearer header alike.
 *
 * Other sessions for the same account are unaffected. "Sign out everywhere"
 * is a different operation and is not in this packet.
 *
 * A token that resolves to nothing is a 401, and the cookie is cleared
 * anyway. A stale cookie is the common case — the session expired hours ago
 * and the browser kept it — and leaving it in place means the user clicks
 * "sign out" again and nothing appears to happen.
 *
 */
export const deleteSession = <ThrowOnError extends boolean = false>(options?: Options<DeleteSessionData, ThrowOnError>): RequestResult<DeleteSessionResponses, DeleteSessionErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteSessionResponses, DeleteSessionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/session',
    ...options
});

/**
 * Log in
 *
 * Verifies an email and password and starts a session.
 *
 * Five consecutive wrong passwords for one address lock that account for
 * fifteen minutes. A locked account is refused with 423 and a `Retry-After`
 * header before the password is checked at all, so it cannot be probed; the
 * rejected attempt does not extend the window. A successful login clears the
 * count.
 *
 * An unknown address and a wrong password produce the same 401 body and take
 * comparable time: the unknown-address path performs the same argon2id
 * verification against a digest nothing can match. This is deliberate and is
 * the reason a login endpoint does not enumerate accounts.
 *
 * Login does not accept an `Idempotency-Key`. A login is not safely
 * repeatable — retrying it mints another session rather than returning the
 * first one — so honouring the header would be a lie. See "Known gaps".
 *
 * **AN ACCOUNT WITH A SECOND FACTOR GETS 202 AND NO SESSION.** The password
 * is correct and the authentication is not finished, which is what 202
 * means. The `202` body carries **no `token` key at all** — not an empty
 * one — so a client that reads `token` finds nothing and is unambiguous
 * about it. The `challenge` in that body is the token for
 * `POST /v1/session/mfa`, and it authenticates nothing until a code is
 * presented against it.
 *
 * Five consecutive wrong CODES lock the second factor for fifteen minutes,
 * with `423` and `Retry-After`, and that counter is **separate from the
 * password's**: five TOTP guesses have not spent five password guesses, and
 * five wrong passwords have not moved the second factor's.
 *
 */
export const createSession = <ThrowOnError extends boolean = false>(options: Options<CreateSessionData, ThrowOnError>): RequestResult<CreateSessionResponses, CreateSessionErrors, ThrowOnError> => (options.client ?? client).post<CreateSessionResponses, CreateSessionErrors, ThrowOnError>({
    url: '/v1/session',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Answer a second factor and start the session
 *
 * The second half of a login for an account with a second factor, and **the
 * only route in this service that turns a second factor into a session**.
 *
 * The session is created inside the same transaction that consumes the
 * challenge, so a challenge cannot be answered twice and a code cannot buy two
 * sessions.
 *
 * **The challenge is accepted in the cookie or in the body**, and both are
 * supported on purpose: cafaye's conventions say "no cookies for API traffic",
 * and `POST /v1/session` returns the session token in the body as well as in
 * the cookie precisely so a non-browser client has a way in. The explicit body
 * value wins when both are present, for the reason `GET /v1/me` prefers the
 * `Authorization` header over the cookie.
 *
 * A code is accepted within **one step either side** of the current one, so a
 * TOTP code is live for 90 seconds rather than 30. Zero skew would refuse any
 * code typed near a step boundary, which is when a user is most likely to be
 * reading digits off a screen, and a second factor with a visible failure rate
 * gets turned off rather than retried. Two steps or more would be ninety more
 * seconds during which a phished code still works.
 *
 * **A code cannot be accepted twice.** Replay is the standard attack against
 * TOTP, and this service records the exact steps consumed: a code already used
 * is refused for the whole window, and refusing it costs nothing to the user
 * beyond the next 30-second period.
 *
 * Five consecutive wrong codes lock the second factor for fifteen minutes, and
 * that counter is **separate from the password's**.
 *
 */
export const completeSecondFactor = <ThrowOnError extends boolean = false>(options: Options<CompleteSecondFactorData, ThrowOnError>): RequestResult<CompleteSecondFactorResponses, CompleteSecondFactorErrors, ThrowOnError> => (options.client ?? client).post<CompleteSecondFactorResponses, CompleteSecondFactorErrors, ThrowOnError>({
    url: '/v1/session/mfa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Turn the second factor off
 *
 * Requires a second factor, and a password is **not** accepted: there is no
 * route to this operation without one. Re-authentication for a destructive
 * security action is the whole reason it exists, and a user whose phone is
 * elsewhere must use a recovery code — which is why recovery codes exist.
 *
 * Revokes **every session the user holds**, and emits `identity.mfa.disabled`.
 * A user who turns MFA off has very often had it turned off *for* them, and
 * every session in existence was minted under a two-factor policy.
 *
 * The caller's own session is revoked by this call, so a browser is left
 * signed out. That is the honest outcome rather than an exception.
 *
 */
export const disableMfa = <ThrowOnError extends boolean = false>(options: Options<DisableMfaData, ThrowOnError>): RequestResult<DisableMfaResponses, DisableMfaErrors, ThrowOnError> => (options.client ?? client).delete<DisableMfaResponses, DisableMfaErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/mfa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Whether the caller has a second factor
 *
 * Returns whether this account has a confirmed second factor, when it was
 * enrolled, and how many recovery codes are left.
 *
 * `recovery_codes_remaining` is here so a client can say "2 left — print a new
 * set" while there are still two. A user with zero recovery codes and a lost
 * phone is a support ticket, and the honest thing is to say so beforehand.
 *
 * A `200` with `{"enabled": false}` and **not** a 404 when there is no
 * credential: the question has an answer for every signed-in user, and a
 * settings page should not have to distinguish "you have none" from "this is
 * not your account".
 *
 */
export const getMfaStatus = <ThrowOnError extends boolean = false>(options?: Options<GetMfaStatusData, ThrowOnError>): RequestResult<GetMfaStatusResponses, GetMfaStatusErrors, ThrowOnError> => (options?.client ?? client).get<GetMfaStatusResponses, GetMfaStatusErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/mfa',
    ...options
});

/**
 * Generate a TOTP secret
 *
 * Generates a secret with `crypto/rand`, stores it **unconfirmed**, and returns
 * it once with its `otpauth://` provisioning URI.
 *
 * `secret` and `provisioning_uri` are returned here and **never again**: there
 * is no endpoint that re-reads them, so a client that loses this response
 * starts a new enrollment, which mints a new secret. The reasoning is the one
 * an OIDC `client_secret` follows: a secret this service can produce again is a
 * secret this service is storing, and a stored TOTP secret is a second factor
 * for whoever reads the database.
 *
 * **A pending enrollment is not MFA.** It expires in ten minutes, the login
 * path reads only confirmed rows, and no session is issued until
 * `/confirm`. A stored-but-never-confirmed secret is exactly the state that
 * locks somebody out of their own account.
 *
 * On an account that **already** has a credential this starts a **rotation**,
 * and `code` is then required. The existing secret stays live until the
 * replacement is confirmed, so an abandoned rotation costs nothing; on
 * confirmation the old credential is deleted, which is how its codes stop being
 * accepted.
 *
 */
export const startMfaEnrollment = <ThrowOnError extends boolean = false>(options: Options<StartMfaEnrollmentData, ThrowOnError>): RequestResult<StartMfaEnrollmentResponses, StartMfaEnrollmentErrors, ThrowOnError> => (options.client ?? client).post<StartMfaEnrollmentResponses, StartMfaEnrollmentErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/mfa/enrollments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Prove you can produce a code, and make MFA live
 *
 * Verifies a code against the pending secret and, on success, makes MFA live in
 * one transaction: confirm the pending row, delete the credential it replaced
 * if any, write ten recovery codes, revoke every session the user holds, and
 * announce `identity.mfa.enabled`.
 *
 * **Every session is revoked, including the caller's own.** A session minted
 * under a one-factor policy was minted on a password alone, and leaving it
 * alive means the attacker holding it does not have to solve the new problem.
 *
 * The recovery codes are returned here and **never again** — no endpoint
 * re-reads them and no column stores them, only a SHA-256 digest per code.
 *
 */
export const confirmMfaEnrollment = <ThrowOnError extends boolean = false>(options: Options<ConfirmMfaEnrollmentData, ThrowOnError>): RequestResult<ConfirmMfaEnrollmentResponses, ConfirmMfaEnrollmentErrors, ThrowOnError> => (options.client ?? client).post<ConfirmMfaEnrollmentResponses, ConfirmMfaEnrollmentErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/mfa/enrollments/{enrollmentId}/confirm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Issue a new set of recovery codes
 *
 * Deletes the old set and writes the new one **in one transaction**, and
 * requires a second factor: handing out ten fresh codes is handing out ten
 * fresh ways into the account.
 *
 * The atomicity is the requirement. A partial write leaves a user with two
 * live sets, which is a second recovery path through codes nobody audited and
 * nobody will ever see in a log.
 *
 */
export const regenerateMfaRecoveryCodes = <ThrowOnError extends boolean = false>(options: Options<RegenerateMfaRecoveryCodesData, ThrowOnError>): RequestResult<RegenerateMfaRecoveryCodesResponses, RegenerateMfaRecoveryCodesErrors, ThrowOnError> => (options.client ?? client).post<RegenerateMfaRecoveryCodesResponses, RegenerateMfaRecoveryCodesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/mfa/recovery-codes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The authenticated user
 *
 * Resolves the presented credential and returns the account it belongs to.
 *
 * A cookie and a bearer token are both accepted. When both are present the
 * `Authorization` header wins: a client holding both has said which it means,
 * and answering from the cookie would make the result depend on invisible
 * browser state.
 *
 * A missing, unknown, expired or revoked token are one 401 with one body. So
 * is a token whose account has been deleted.
 *
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/me',
    ...options
});

/**
 * List an account's OpenID Connect clients
 *
 * Every registration this account owns, newest first. An account with none
 * answers `[]` and not `null`.
 *
 * A bare array rather than core's `data` + `page` wrapper, and the omission
 * is deliberate: this list is a handful of rows, and a cursor over four of
 * them is a wrapper a client has to unwrap to render a settings page. The
 * first account that wants a hundred products gets the wrapper then.
 *
 */
export const listOidcClients = <ThrowOnError extends boolean = false>(options: Options<ListOidcClientsData, ThrowOnError>): RequestResult<ListOidcClientsResponses, ListOidcClientsErrors, ThrowOnError> => (options.client ?? client).get<ListOidcClientsResponses, ListOidcClientsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/accounts/{account_id}/oidc-clients',
    ...options
});

/**
 * Register an OpenID Connect client
 *
 * Registers a relying party: the credential a product presents at the token
 * endpoint when it runs an authorization-code flow against this service.
 *
 * **Owner only.** Adding a client is adding a new way for code to arrive in
 * this product and get a token back out, so a member of the account is 403
 * and a non-member is 404.
 *
 * `client_id` and `client_secret` are minted here and returned here, and
 * `client_secret` is returned **once**. It is never stored — only its
 * SHA-256 is — and there is no endpoint that re-reads it. A caller that
 * loses it registers again, which is the rule a session token, an
 * invitation token and a password already follow.
 *
 * `redirect_uris` is matched EXACTLY. No prefix, no glob, no pattern of
 * any kind: `https://app.example.com.evil.com/cb` is not a match for a
 * registered `https://app.example.com/cb`, and a prefix comparison would
 * make this service an open redirector for every product registered here.
 * Plain `http` is accepted only on loopback, so a product can develop
 * against a local stack without the registration ever accepting a
 * plain-http origin.
 *
 * `scopes` is intersected with what this provider implements
 * (`openid email profile accounts`) and must include `openid`. `grant_types`
 * must be `authorization_code`: this service issues no refresh token, has
 * no service identity for client credentials, and has no consent screen for
 * an implicit flow, so registering any of them is refused at 422 with the
 * field named rather than discovered at 3am.
 *
 */
export const registerOidcClient = <ThrowOnError extends boolean = false>(options: Options<RegisterOidcClientData, ThrowOnError>): RequestResult<RegisterOidcClientResponses, RegisterOidcClientErrors, ThrowOnError> => (options.client ?? client).post<RegisterOidcClientResponses, RegisterOidcClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/accounts/{account_id}/oidc-clients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke an OpenID Connect client
 *
 * Stops honouring the registration. The row is kept rather than deleted — an
 * audit of which credentials existed is worth more than a tidier table, and
 * `revoked_at` is what makes the difference readable afterwards.
 *
 * The revocation is real rather than advisory: every access token issued
 * against this registration is revoked in the same transaction, because a
 * token is a signed JWT that a verifier on the edge will keep accepting
 * until its `exp` and revoking the registration does not by itself stop one.
 * A token minted before the revocation therefore fails at userinfo
 * immediately, not fifteen minutes later.
 *
 * 204 rather than the revoked row, matching every other `DELETE` in this
 * service. The `identity.oidc_client.revoked` event is where a consumer
 * learns what happened.
 *
 */
export const revokeOidcClient = <ThrowOnError extends boolean = false>(options: Options<RevokeOidcClientData, ThrowOnError>): RequestResult<RevokeOidcClientResponses, RevokeOidcClientErrors, ThrowOnError> => (options.client ?? client).delete<RevokeOidcClientResponses, RevokeOidcClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/accounts/{account_id}/oidc-clients/{client_id}',
    ...options
});

/**
 * Read an OpenID Connect client
 *
 * One registration. `client_secret` and the stored digest are both absent
 * and will stay absent: the secret exists once, in the 201.
 *
 */
export const getOidcClient = <ThrowOnError extends boolean = false>(options: Options<GetOidcClientData, ThrowOnError>): RequestResult<GetOidcClientResponses, GetOidcClientErrors, ThrowOnError> => (options.client ?? client).get<GetOidcClientResponses, GetOidcClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/accounts/{account_id}/oidc-clients/{client_id}',
    ...options
});

/**
 * Liveness
 *
 * Answers whether this process is running. It never touches a dependency, so
 * a database outage cannot get the process restarted out from under
 * in-flight work.
 *
 */
export const liveness = <ThrowOnError extends boolean = false>(options?: Options<LivenessData, ThrowOnError>): RequestResult<LivenessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<LivenessResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Readiness
 *
 * Answers whether this process can serve traffic, by probing each named
 * dependency. `deps` lists what was probed, `"none"` when there is nothing to
 * probe.
 *
 * A failing dependency is named but not described: the underlying error goes
 * to the log, because an unauthenticated request must not be a way to learn
 * that a database host is at a particular address.
 *
 */
export const readiness = <ThrowOnError extends boolean = false>(options?: Options<ReadinessData, ThrowOnError>): RequestResult<ReadinessResponses, ReadinessErrors, ThrowOnError> => (options?.client ?? client).get<ReadinessResponses, ReadinessErrors, ThrowOnError>({ url: '/readyz', ...options });
