/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/identity.yaml
//         identity, document version 1.2.0,
//         vendored from git@github.com:cafaye/identity.git
//         at commit 35c2576ede65ad3bc7daf3696fb77c0b0ffa54a3
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export type ClientOptions = {
    baseUrl: 'https://identity.cafaye.com' | 'http://localhost:8080' | (string & {});
};

/**
 * The public projection of an account. Exactly two fields, always: there is
 * no password digest, no lockout state and no timestamp here, and adding one
 * is a contract change.
 *
 */
export type User = {
    /**
     * The account's identifier, and the `subject` of its events.
     */
    id: string;
    /**
     * Always lower case. Registration normalizes before storing.
     */
    email: string;
};

export type RegisterRequest = {
    /**
     * Normalized to lower case and trimmed before storage and before comparison.
     */
    email: string;
    /**
     * At least 8 characters, hashed with argon2id. There is no composition
     * rule: requiring a mix of character classes reliably produces
     * "Password1!" and reliably rejects passphrases, and length is the
     * property that tracks entropy.
     *
     * The upper bound is a DoS control, not a policy. argon2id's cost is
     * fixed in memory but its input is not, so without it an unauthenticated
     * caller chooses the size of every login's hashing work.
     *
     */
    password: string;
};

export type LoginRequest = {
    email: string;
    /**
     * The minimum length is 1 here, not 8. A login is not a registration:
     * refusing to check a short password would be a way to learn which
     * passwords are in use, and an account may predate any rule. The upper
     * bound still applies, because it bounds the hashing work.
     *
     */
    password: string;
};

export type Session = {
    /**
     * 256 bits from crypto/rand, base64url without padding. Only its
     * SHA-256 is stored; a database dump yields no usable credential.
     *
     */
    token: string;
    /**
     * RFC3339 UTC. Judged against the service's clock, not the database's.
     */
    expires_at: string;
};

/**
 * One OpenID Connect registration. `client_secret` and `secret_digest` are
 * both absent and always will be: the secret exists once, in the 201, and
 * the digest is what the row holds.
 *
 */
export type OidcClient = {
    /**
     * The row's identifier, and the `subject` of its events. NOT the
     * `client_id` the product presents — those are different values and
     * conflating them is how a consumer ends up correlating on something it
     * cannot look up.
     *
     */
    id: string;
    /**
     * The public, protocol-visible handle: 32 random bytes, base64url without
     * padding. Unguessable rather than merely unique, because it is half of
     * the credential pair on the token endpoint.
     *
     */
    client_id: string;
    /**
     * What the login page calls the product. Required, because a login page
     * that cannot name the application asking for a password is the setup
     * for a credential-phishing page on this service's own domain.
     *
     */
    name: string;
    /**
     * The allow-list, matched EXACTLY. No prefix, no glob, no pattern. A
     * registered URI may be `https`, or `http` on loopback only; a fragment
     * and a wildcard are both refused. Sorted, and deduplicated.
     *
     */
    redirect_uris: Array<string>;
    /**
     * Always `authorization_code` today. This service issues no refresh
     * token, has no service identity for client credentials, and has no
     * consent screen for an implicit flow.
     *
     */
    grant_types: Array<'authorization_code'>;
    /**
     * A subset of what this provider implements, intersected with what the
     * provider supports, and always including `openid`. A client that did
     * not register a scope cannot be granted it by asking at the authorize
     * endpoint.
     *
     */
    scopes: Array<'openid' | 'email' | 'profile' | 'accounts'>;
    created_at: string;
    /**
     * Absent while the registration is live. A revoked registration is kept
     * rather than deleted, and this is what makes the difference readable
     * afterwards.
     *
     */
    revoked_at?: string;
};

export type RegisteredOidcClient = OidcClient & {
    /**
     * 32 random bytes, base64url, returned in this 201 and never again.
     * Only its SHA-256 is stored, so a dump of the registrations table is
     * not a set of credentials. Losing it means registering again.
     *
     */
    client_secret: string;
};

export type RegisterOidcClientRequest = {
    name: string;
    redirect_uris: Array<string>;
    grant_types: Array<'authorization_code'>;
    /**
     * Names outside this set are DROPPED rather than refused, and this is the
     * one place that is true: a product registering itself asks for what it
     * would like and the operator curates what it gets. The authorization
     * endpoint, where a caller asks for a token right now, refuses.
     *
     */
    scopes: Array<'openid' | 'email' | 'profile' | 'accounts'>;
};

/**
 * The 202 from `POST /v1/session`: a correct password, an unfinished
 * authentication, and nothing else.
 *
 * There is no `token` property here and adding one would be the bug this
 * document exists to prevent. The `challenge` is what `POST /v1/session/mfa`
 * is answered with, and it is worthless on its own.
 *
 */
export type MfaChallenge = {
    /**
     * Always `true` in this body. It is here so a client that keys off a
     * field rather than the status code has one to key off, and a client
     * that keys off the 202 does not need to read it.
     *
     */
    mfa_required: boolean;
    /**
     * 256 bits from crypto/rand, base64url without padding, presented to
     * `POST /v1/session/mfa` as `challenge` or as the
     * `__Host-mfa-challenge` cookie. Single-use and short-lived: the
     * challenge row is deleted in the same transaction that creates the
     * session, so it cannot be answered twice.
     *
     * Only its SHA-256 is stored, so a database dump yields no usable
     * challenge.
     *
     */
    challenge: string;
    /**
     * Ten minutes, judged against the service's clock. Shorter than the
     * fifteen-minute factor lockout, deliberately: a lockout outlives its
     * own challenge, so a user who trips it can answer a fresh code against
     * a fresh challenge as soon as the window ends rather than waiting for
     * the stuck challenge to expire.
     *
     */
    expires_at: string;
};

/**
 * Whether the caller has a second factor.
 *
 * A `200` with `enabled: false`, not a 404, when there is none: the question
 * has an answer for every signed-in user, and a settings page should not
 * have to distinguish "you have none" from "this is not your account".
 *
 */
export type MfaStatus = {
    enabled: boolean;
    /**
     * Absent when `enabled` is false. `"totp"` and "no method yet" are
     * different answers, which is why this is `omitempty` rather than an
     * empty string.
     *
     */
    method?: 'totp';
    /**
     * When the credential was confirmed. Absent when `enabled` is false.
     */
    enrolled_at?: string;
    /**
     * How many unused recovery codes are left. Absent when `enabled` is
     * false.
     *
     * It is here so a client can say "2 left — print a new set" while there
     * are still two. A user with zero codes and a lost phone is a support
     * ticket, and the honest thing is to say so beforehand.
     *
     */
    recovery_codes_remaining?: number;
};

/**
 * The body of every route that changes or relies on an existing second
 * factor.
 *
 * **One field, not `code` and `recovery_code`.** The consequence of getting
 * this wrong is identical either way, and two fields would let a client put
 * a recovery code in the TOTP field and be told the code was malformed rather
 * than not accepted, which is a worse error to act on. This service decides
 * which shape it is and then answers the same way for both.
 *
 */
export type FactorRequest = {
    /**
     * A six-digit TOTP code, or a recovery code in the form
     * `XXXX-XXXX-XXXX-XXXX`. Surrounding whitespace is ignored; nothing else
     * is.
     *
     * A code is not echoed back in any response, and never appears in a log
     * line or a problem body.
     *
     */
    code: string;
};

/**
 * The second half of a login. `challenge` is optional here and required in
 * effect — omitting it entirely, with no challenge cookie either, is a 401.
 *
 */
export type CompleteSecondFactorRequest = {
    /**
     * The challenge from the 202. **Optional, because the
     * `__Host-mfa-challenge` cookie is accepted instead** — the cookie is the
     * browser's route and this field is the API client's, exactly as
     * `POST /v1/session` returns the session token in the body as well as in
     * the cookie so a non-browser client has a way in.
     *
     * When both are present the body wins. A client holding both has said
     * which one it means, and answering from ambient browser state would
     * make the result depend on invisible cookies.
     *
     */
    challenge?: string;
    /**
     * A six-digit TOTP code, or a recovery code. Same shapes as `FactorRequest.code`.
     */
    code: string;
};

export type StartEnrollmentRequest = {
    /**
     * Required **only** when this account already has a credential, where
     * the request is a rotation.
     *
     * The service decides which case it is from the rows, so sending a code
     * for a first enrollment is not wrong, only redundant — which is why
     * this is optional in the schema and required in prose. Refusing the
     * redundant one would be a 422 that teaches a client nothing.
     *
     */
    code?: string;
};

/**
 * A pending TOTP enrollment, and the only response in this document that
 * contains a TOTP secret.
 *
 * **The secret is here and nowhere else.** There is no endpoint that
 * re-reads it, so a client that loses this body starts a new enrollment,
 * which mints a new secret. The reasoning is the one an OIDC
 * `client_secret` follows: a secret this service can produce again is a
 * secret this service is storing, and a stored TOTP secret is a second
 * factor for whoever reads the database.
 *
 * Nothing here is a session, and nothing here is MFA. A pending enrollment
 * is unread by the login path, so until `/confirm` is called this account
 * has no second factor.
 *
 */
export type StartedEnrollment = {
    /**
     * The id to confirm. It is the pending row's own id, and another user's,
     * an expired one's and an already-confirmed one's are all 404 — so it is
     * not a way to learn which enrollments exist.
     *
     */
    enrollment_id: string;
    /**
     * base32, no padding, 160 bits from crypto/rand. The shared secret for
     * `HMAC-SHA1`, and the half of the factor the phone holds.
     *
     * Stored **encrypted**, not hashed: verifying a code means computing an
     * HMAC with this value, so a hash would be useless. At rest it is
     * AES-256-GCM ciphertext under `MFA_ENCRYPTION_KEY`, with the user's id
     * as additional authenticated data.
     *
     */
    secret: string;
    /**
     * An `otpauth://totp/…` URI, which is what a QR code encodes. Contains
     * `secret`, so it is not shareable and not cacheable.
     *
     */
    provisioning_uri: string;
    method: 'totp';
    /**
     * The code length. Fixed, and 6 because that is what authenticator apps display.
     */
    digits: 6;
    /**
     * The step, 30 seconds. Returned rather than assumed so a client can
     * render a countdown without hard-coding it.
     *
     */
    period_seconds: 30;
    /**
     * `SHA1`, and not a preference: it is the only HMAC every authenticator
     * app implements. A user whose app rejected SHA1 has no app.
     *
     */
    algorithm: 'SHA1';
    /**
     * Ten minutes. An unconfirmed enrollment is deleted after this, because
     * a stored-but-never-confirmed secret is exactly the state that locks
     * somebody out of their own account.
     *
     */
    expires_at: string;
    /**
     * `true` when this enrollment is replacing an existing credential.
     *
     * The old secret is **still live** until this one is confirmed, so an
     * abandoned rotation costs nothing and the user is not left with a dead
     * phone. `replaced` is what lets a client say so out loud rather than
     * leave them to discover it.
     *
     */
    replaced: boolean;
};

export type ConfirmEnrollmentRequest = {
    /**
     * A six-digit code computed from this enrollment's `secret`.
     *
     * Required always, and an absent one is the only 422 on this surface:
     * the code is required rather than wrong, and telling those apart saves
     * a user staring at a six-digit box wondering what they did.
     *
     * Wrong, already spent, malformed, and produced by a secret this
     * rotation has already replaced are all the same 401. They are four
     * different facts and a client that can tell them apart learns which to
     * keep trying.
     *
     */
    code: string;
};

/**
 * MFA is live, and here are the recovery codes, once.
 *
 * **Every session this account holds was revoked to produce this response**,
 * including the caller's. A session minted under a one-factor policy was
 * minted on a password alone, and leaving it alive means whoever holds it
 * does not have to solve the new problem.
 *
 * The response is therefore `200` and not `204`: there is real content, and
 * that content exists exactly once.
 *
 */
export type ConfirmedEnrollment = {
    enabled: true;
    method: 'totp';
    enrolled_at: string;
    /**
     * Ten codes, 80 bits each, and **never readable again**: no endpoint
     * re-reads them and no column stores them, only a SHA-256 digest per
     * code. Each is accepted exactly once and is destroyed by use.
     *
     * 80 bits is a floor, not a style choice. A six-digit TOTP code is 20
     * bits and is only safe because it changes every 30 seconds and cannot
     * be retried; a recovery code does not change, so a short one would be
     * guessable at leisure.
     *
     */
    recovery_codes: [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
    ];
    /**
     * `true` when this confirmation replaced a credential. The old one is
     * deleted by this call, which is what makes its codes stop being
     * accepted — the old phone stops working at the moment of confirmation,
     * not at the moment the rotation started.
     *
     */
    replaced_existing_secret: boolean;
};

/**
 * A fresh set of recovery codes. The old set is destroyed by this call, in
 * the same transaction that writes the new one.
 *
 * A partial write would leave a user with two live sets, which is a second
 * recovery path through codes nobody audited and nobody will ever see in a
 * log. That is the requirement this route exists to satisfy.
 *
 */
export type RecoveryCodesResponse = {
    /**
     * The new set, returned once and never again. Same 80-bit value as
     * `ConfirmedEnrollment.recovery_codes`, and the same one-shot guarantee.
     *
     */
    recovery_codes: [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
    ];
    issued_at: string;
    /**
     * Always 10. It is the count of the set just issued rather than a read
     * back from storage, because a client rendering "you now have N codes"
     * wants N and not a round trip to learn it.
     *
     */
    recovery_codes_remaining: 10;
};

/**
 * The cafaye error envelope: RFC 9457 plus core's `code` and `trace_id`.
 * Every non-2xx response from this service is this shape. No service invents
 * its own error body.
 *
 */
export type Problem = {
    /**
     * A stable `https://errors.cafaye.com/<code>` URI — the machine-readable contract.
     */
    type: string;
    /**
     * A fixed human-readable summary for the code. May be reworded without a version bump.
     */
    title: string;
    /**
     * The HTTP status, repeated in the body.
     */
    status: number;
    /**
     * Specific to this occurrence and not parsed by clients. Never contains
     * an internal error, a host, a role or a query fragment: those go to the
     * log under the same `trace_id`.
     *
     */
    detail: string;
    /**
     * The request path. Never includes the query string, which can carry an address.
     */
    instance: string;
    /**
     * The last segment of `type`, in snake_case.
     */
    code: 'unauthorized' | 'forbidden' | 'not_found' | 'conflict' | 'validation_failed' | 'rate_limited' | 'idempotency_key_reused' | 'internal' | 'unavailable' | 'account_locked' | 'method_not_allowed' | 'invalid_json' | 'payload_too_large' | 'service_unavailable';
    /**
     * Always present, always equal to the `X-Trace-Id` response header.
     */
    trace_id: string;
    /**
     * Per-field failures. Present only on 422.
     */
    errors?: Array<FieldError>;
};

export type FieldError = {
    /**
     * The request field that failed.
     */
    field: string;
    /**
     * A stable slug, safe to switch on. `required`, `invalid_format`,
     * `too_short`, `too_long`.
     *
     */
    code: string;
};

export type Health = {
    status: 'ok' | 'unavailable';
    /**
     * The dependencies probed, comma separated, or `none`. Present on `/readyz` only.
     */
    deps?: string;
};

/**
 * The account. A caller who is not a member of it gets 404 and never 403,
 * because a 403 would confirm the account exists to somebody guessing ids.
 *
 */
export type AccountId = string;

export type RegisterUserData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type RegisterUserErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * An account already exists for that address.
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * The account was created.
     */
    201: User;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type DeleteSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/session';
};

export type DeleteSessionErrors = {
    /**
     * No usable credential, or one that no longer resolves.
     */
    401: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * The session was revoked and the cookie cleared.
     */
    204: void;
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type CreateSessionData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/v1/session';
};

export type CreateSessionErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The credentials were refused. The body is identical whether the
     * address is unregistered or the password is wrong, and says nothing
     * about which.
     *
     */
    401: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The account is locked after too many consecutive failures. The
     * `Retry-After` header and the `detail` both carry the remaining window
     * in whole seconds, rounded up.
     *
     * The window is deliberately **not** an entry in `errors[]`: core scopes
     * that array to 422 and to fields of the request, and `retry_after` is
     * not one.
     *
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type CreateSessionError = CreateSessionErrors[keyof CreateSessionErrors];

export type CreateSessionResponses = {
    /**
     * The credentials were correct and a session now exists. The same token
     * is in the body and in the cookie.
     *
     */
    200: Session;
    /**
     * The password was correct and this account has a second factor. **No
     * session exists** and no session cookie is set.
     *
     * The `challenge` is a one-time credential for `POST /v1/session/mfa`,
     * valid for ten minutes and single-use. It is also set as the
     * `__Host-mfa-challenge` cookie, which is the browser's copy and carries
     * the same value.
     *
     * There is no `token` field in this schema, and that is deliberate: a
     * client that looks for one must handle its absence rather than treat an
     * empty string as a value.
     *
     */
    202: MfaChallenge;
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type CompleteSecondFactorData = {
    body: CompleteSecondFactorRequest;
    path?: never;
    query?: never;
    url: '/v1/session/mfa';
};

export type CompleteSecondFactorErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The factor was refused, or no challenge was presented. The body is the
     * same for a wrong code, a recovery code that was already spent, a TOTP
     * code whose step has been used, and a value that is neither shape: five
     * different facts, and an attacker who can tell them apart learns which to
     * keep trying.
     *
     */
    401: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked after too many consecutive failures. The
     * `Retry-After` header carries the remaining window in whole seconds.
     *
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
    /**
     * This deployment cannot verify a second factor, because
     * `MFA_ENCRYPTION_KEY` is not configured. It is a 503 and not a 404 on
     * purpose: a 404 would say the service has never heard of MFA, and a
     * client that believed that would be free to treat the absence of a
     * challenge as the absence of a requirement.
     *
     */
    503: Problem;
};

export type CompleteSecondFactorError = CompleteSecondFactorErrors[keyof CompleteSecondFactorErrors];

export type CompleteSecondFactorResponses = {
    /**
     * The second factor was accepted and a session now exists. The same token
     * is in the body and in the cookie, and the challenge cookie is cleared.
     *
     */
    200: Session;
};

export type CompleteSecondFactorResponse = CompleteSecondFactorResponses[keyof CompleteSecondFactorResponses];

export type DisableMfaData = {
    body: FactorRequest;
    path?: never;
    query?: never;
    url: '/v1/mfa';
};

export type DisableMfaErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * This account has no second factor, so there was nothing to turn off.
     * A 409 rather than a 404: the caller is asking to change something that
     * does not exist, which is a different question from "is this yours".
     *
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked after too many consecutive failures.
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type DisableMfaError = DisableMfaErrors[keyof DisableMfaErrors];

export type DisableMfaResponses = {
    /**
     * MFA is off, every session is revoked, and the cookie is cleared.
     */
    204: void;
};

export type DisableMfaResponse = DisableMfaResponses[keyof DisableMfaResponses];

export type GetMfaStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/mfa';
};

export type GetMfaStatusErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type GetMfaStatusError = GetMfaStatusErrors[keyof GetMfaStatusErrors];

export type GetMfaStatusResponses = {
    /**
     * The caller's second-factor status.
     */
    200: MfaStatus;
};

export type GetMfaStatusResponse = GetMfaStatusResponses[keyof GetMfaStatusResponses];

export type StartMfaEnrollmentData = {
    body: StartEnrollmentRequest;
    path?: never;
    query?: never;
    url: '/v1/mfa/enrollments';
};

export type StartMfaEnrollmentErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked, so a rotation cannot be authorised.
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type StartMfaEnrollmentError = StartMfaEnrollmentErrors[keyof StartMfaEnrollmentErrors];

export type StartMfaEnrollmentResponses = {
    /**
     * A pending enrollment, and its one-time values.
     */
    201: StartedEnrollment;
};

export type StartMfaEnrollmentResponse = StartMfaEnrollmentResponses[keyof StartMfaEnrollmentResponses];

export type ConfirmMfaEnrollmentData = {
    body: ConfirmEnrollmentRequest;
    path: {
        /**
         * The pending enrollment's own id. Another user's, an expired one's, and
         * one that has already been confirmed are all `404`, so the id is not a
         * way to learn which enrollments exist.
         *
         */
        enrollmentId: string;
    };
    query?: never;
    url: '/v1/mfa/enrollments/{enrollmentId}/confirm';
};

export type ConfirmMfaEnrollmentErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The code was refused. One sentence for every way it can fail: wrong,
     * already spent, malformed, or produced by a secret this rotation has
     * already replaced.
     *
     */
    401: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ConfirmMfaEnrollmentError = ConfirmMfaEnrollmentErrors[keyof ConfirmMfaEnrollmentErrors];

export type ConfirmMfaEnrollmentResponses = {
    /**
     * MFA is live, and the recovery codes are returned once.
     */
    200: ConfirmedEnrollment;
};

export type ConfirmMfaEnrollmentResponse = ConfirmMfaEnrollmentResponses[keyof ConfirmMfaEnrollmentResponses];

export type RegenerateMfaRecoveryCodesData = {
    body: FactorRequest;
    path?: never;
    query?: never;
    url: '/v1/mfa/recovery-codes';
};

export type RegenerateMfaRecoveryCodesErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The factor was refused, or this account has no second factor.
     *
     */
    401: Problem;
    /**
     * This account has no second factor, so there are no codes to replace.
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked after too many consecutive failures.
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RegenerateMfaRecoveryCodesError = RegenerateMfaRecoveryCodesErrors[keyof RegenerateMfaRecoveryCodesErrors];

export type RegenerateMfaRecoveryCodesResponses = {
    /**
     * A new set, returned once, and the count that replaced the old one.
     */
    200: RecoveryCodesResponse;
};

export type RegenerateMfaRecoveryCodesResponse = RegenerateMfaRecoveryCodesResponses[keyof RegenerateMfaRecoveryCodesResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type GetCurrentUserErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * The authenticated user.
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListOidcClientsData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients';
};

export type ListOidcClientsErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ListOidcClientsError = ListOidcClientsErrors[keyof ListOidcClientsErrors];

export type ListOidcClientsResponses = {
    /**
     * The account's registrations.
     */
    200: Array<OidcClient>;
};

export type ListOidcClientsResponse = ListOidcClientsResponses[keyof ListOidcClientsResponses];

export type RegisterOidcClientData = {
    body: RegisterOidcClientRequest;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients';
};

export type RegisterOidcClientErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RegisterOidcClientError = RegisterOidcClientErrors[keyof RegisterOidcClientErrors];

export type RegisterOidcClientResponses = {
    /**
     * The registration, and its secret.
     */
    201: RegisteredOidcClient;
};

export type RegisterOidcClientResponse = RegisterOidcClientResponses[keyof RegisterOidcClientResponses];

export type RevokeOidcClientData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
        /**
         * The registration's row id — not the `client_id` the product presents.
         * The row id is what the revocation event's `subject` is, and what the
         * other three routes name.
         *
         */
        client_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients/{client_id}';
};

export type RevokeOidcClientErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The registration is already revoked. A 204 either way would leave an
     * operator who clicked twice believing they had just destroyed a second
     * credential.
     *
     */
    409: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RevokeOidcClientError = RevokeOidcClientErrors[keyof RevokeOidcClientErrors];

export type RevokeOidcClientResponses = {
    /**
     * The registration is revoked. No body.
     */
    204: void;
};

export type RevokeOidcClientResponse = RevokeOidcClientResponses[keyof RevokeOidcClientResponses];

export type GetOidcClientData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
        /**
         * The registration's row id — not the `client_id` the product presents.
         * The row id is what the revocation event's `subject` is, and what the
         * other three routes name.
         *
         */
        client_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients/{client_id}';
};

export type GetOidcClientErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type GetOidcClientError = GetOidcClientErrors[keyof GetOidcClientErrors];

export type GetOidcClientResponses = {
    /**
     * The registration.
     */
    200: OidcClient;
};

export type GetOidcClientResponse = GetOidcClientResponses[keyof GetOidcClientResponses];

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type LivenessResponses = {
    /**
     * The process is running.
     */
    200: Health;
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadinessErrors = {
    /**
     * At least one dependency did not answer.
     *
     * This is the one non-2xx response in the service that is not a problem
     * document, and it is a known conflict rather than an oversight. See
     * "Known gaps", item 4.
     *
     */
    503: Health;
};

export type ReadinessError = ReadinessErrors[keyof ReadinessErrors];

export type ReadinessResponses = {
    /**
     * Every dependency answered.
     */
    200: Health;
};

export type ReadinessResponse = ReadinessResponses[keyof ReadinessResponses];
