/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/identity.yaml
//         identity, document version 1.5.0,
//         vendored from git@github.com:cafaye/identity.git
//         at commit 793977bef9728eeeb37fc1c450c935f17bc2e63b
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export type ClientOptions = {
    baseUrl: 'https://identity.cafaye.com' | 'http://localhost:8080' | (string & {});
};

/**
 * A scoped API token as the settings page sees it.
 *
 * **There is no `token` field here, and that is not an omission.** The
 * plaintext exists exactly once, in the `201` from
 * `POST /v1/accounts/{account_id}/api-keys`; there is no column holding it and
 * no endpoint that re-reads one. `IssuedAPIKey` below is the only shape with
 * that field, and it embeds this one — so the list handler cannot reach it even
 * by accident.
 *
 * Nor is there a `token_digest`. It is of no use to a client, and echoing the
 * row's most sensitive column into a browser's network log would be a cost
 * with no benefit. A token is identified by its `name` or its `id`, and never
 * by a piece of itself — that is a rule for the logs this service writes as
 * much as for this response.
 *
 */
export type ApiKey = {
    /**
     * The row's own id. This is what a revoke names and what a test uses to
     * identify a credential.
     *
     */
    id: string;
    /**
     * What a human calls this in a list. Required, because an operator revokes
     * by what they can read; a token nobody can tell apart from another is one
     * nobody remembers to revoke.
     *
     */
    name: string;
    account_id: string;
    /**
     * The user who minted it, and the only subject it ever has. A credential
     * is minted BY the caller FOR the caller's own account.
     *
     */
    user_id: string;
    /**
     * The granted capabilities. An **array** here and not the
     * space-separated string of the claim document: this is a REST list, and
     * the claim form is the wire shape for something a resource server parses
     * out of a token. They are the same set.
     *
     */
    scopes: Array<ApiKeyScope>;
    expires_at: string;
    created_at: string;
    /**
     * Absent when the token has never been presented. `omitempty` is doing
     * real work: "never used" and "used at the epoch" are different answers
     * and only the first is true.
     *
     * Accurate to within five minutes, deliberately. A CI token at a thousand
     * requests a second must not put a thousand UPDATEs a second on one row,
     * and a single row's lock is a queue.
     *
     */
    last_used_at?: string;
    revoked_at?: string;
    /**
     * Why it was withdrawn, when an operator gave a reason. Either a sentence
     * somebody typed, or the closed value `membership removed` that
     * `accounts.Service.RemoveMember` writes.
     *
     */
    revoke_reason?: string;
};

/**
 * One of four names, in core's `resource:action` shape. The set is closed and
 * adding one is a code change rather than a migration, which is why a token
 * holding a name this build does not know is refused at the point of use
 * rather than being treated as "and so anything goes".
 *
 */
export type ApiKeyScope = 'accounts:read' | 'accounts:write' | 'accounts:delete' | 'oidc_clients:write';

export type IssuedApiKey = ApiKey & {
    /**
     * The credential: `cafaye_` plus 43 base64url characters. Shown once,
     * here, and unrecoverable afterwards — not because an endpoint is
     * missing but because the row holds a SHA-256 of a 256-bit value.
     * A caller that loses it mints another.
     *
     * The prefix is a feature and the feature is recognition: a secret
     * that leaks into a CI log, a shell history or a support ticket is
     * recognised as a cafaye credential by its first seven characters,
     * which turns "somebody has to work out which of these strings is
     * working" into a grep.
     *
     */
    token: string;
};

/**
 * **Both fields are required, and neither is optional.** `confirm` is the
 * whole of the difference between this route and the single-revocation route,
 * and an array with no confirmation is exactly the request that revokes every
 * pending invitation by accident.
 *
 * An unknown field is a 422, so a client misspelling `confirm` is told rather
 * than proceeding.
 *
 */
export type BulkInvitationRevocation = {
    /**
     * The pending invitations to revoke, as row ids. **At most 50** — a larger
     * request is a 422 rather than a truncation, because a request naming a
     * thousand invitations that silently revoked the first fifty is the outage
     * this route exists to make harder.
     *
     * Ids that are already revoked, already accepted, or belong to another
     * account are not an error: they change no rows and are not counted in
     * `revoked`. That is why the response reports both counts.
     *
     */
    invitation_ids: Array<string>;
    /**
     * Must be `true`. `false` is the same answer as absent — a 422 naming
     * `confirm` — so a client cannot learn from the response which value it
     * sent.
     *
     */
    confirm: true;
};

/**
 * `requested` is what the request named and `revoked` is what the database
 * changed, and they are frequently different. Both are reported rather than
 * reconciled, because a client that cannot tell "you asked for four and four
 * went" from "you asked for four and two went" would report a completed task
 * over an incident.
 *
 */
export type BulkRevocationResult = {
    /**
     * How many invitation ids the request named, after de-duplication.
     */
    requested: number;
    /**
     * How many pending invitations the database actually changed. **This is
     * also the number in the audit record** — the one the mutation reported,
     * not the length of the request.
     *
     */
    revoked: number;
};

/**
 * One bounded page of the account's admin audit trail, newest first.
 *
 */
export type AuditLogPage = {
    /**
     * Present and empty when there is nothing, rather than omitted: "no
     * entries" and "the server left the field out" are different answers and
     * a client that has to tell them apart will eventually get it wrong.
     *
     */
    entries: Array<AuditLogEntry>;
    /**
     * The opaque cursor for the following page, **absent on the last page**.
     *
     * It encodes the last row's `(occurred_at, id)` pair together and is
     * passed back verbatim in `before`. It is not an offset, and it is not a
     * bare timestamp: a timestamp-only cursor drops every record sharing the
     * boundary instant, and this service's clock is a timestamp rather than a
     * sequence, so two admin actions in the same second is the normal case.
     *
     */
    next?: string;
};

/**
 * One admin action.
 *
 * **There is no field here that could hold a credential, and that is
 * structural rather than a convention.** `actor_user_id` and `actor_key_id`
 * are row ids. The api key's digest is a field on the struct a handler holds,
 * and an audit log is exactly where a careless `fmt.Sprintf("%+v", …)` of it
 * would end up — so a test walks the types that reach this table and fails if
 * any of them grows a field that could hold a value.
 *
 * An operator copies this response into an incident ticket, and a response
 * shape with a `token` field is one somebody will eventually populate.
 *
 */
export type AuditLogEntry = {
    /**
     * The record's own id.
     */
    id: string;
    /**
     * What was done, from a closed set validated in Go rather than by a
     * schema CHECK — a closed vocabulary is a code fact, and putting it in
     * the schema would make adding an action a migration.
     *
     * The two names are distinct because the two are different events: one
     * invitation revoked is a decision about a person, and a hundred at once
     * is a decision about the account. Collapsing them would lose the answer
     * an operator is asking for — "was that one, or was that all of them".
     *
     */
    action: 'invitation.revoked' | 'invitations.revoked';
    /**
     * The human the acting token was minted for.
     */
    actor_user_id: string;
    /**
     * **Which** token acted — the row's id, never its value. "Somebody in the
     * account" is not an answer an incident review can use, and this is the id
     * an operator revokes by.
     *
     */
    actor_key_id: string;
    /**
     * A short label for what was acted on: an invitation id for the single
     * route, `invitation-revocations` for the bulk one. A label and not a
     * list, so one record stays one record however large the request was.
     *
     */
    target: string;
    /**
     * How many rows the action changed — the number the mutation reported, not
     * the length of the request. `0` on the bulk route means every named
     * invitation was already in a non-revocable state, and the response's
     * `revoked` count says so too.
     *
     */
    affected: number;
    /**
     * The request's trace id, which is also the `X-Trace-Id` response header
     * and the `trace_id` in the problem document if the action failed. This
     * joins an audit record to a log line without either carrying a timestamp
     * comparison. Never a credential.
     *
     */
    trace_id: string;
    /**
     * When the action happened, from the service's clock.
     */
    occurred_at: string;
};

/**
 * **The account and the user are not here.** They come from the path and the
 * session, and a body carrying `account_id` or `user_id` is a 422 — because a
 * body that could carry them is a body where they are ambiguous.
 *
 */
export type MintApiKeyRequest = {
    /**
     * Trimmed, and refused if it holds a control character: a name lands in a
     * log line, a settings page and an incident report, and one carrying a
     * newline is three lines where somebody wrote one.
     *
     */
    name: string;
    /**
     * Required, and refused rather than defaulted. A token with no scopes is a
     * session that never expires, and it arrives as "the client did not send
     * the field" — which is exactly how the dangerous case looks.
     *
     * An unsupported scope is a 422 naming the field, not a silent drop: a CI
     * job that asked for `accounts:admin` and silently received
     * `accounts:read` runs for a week and fails on the write it was written
     * to do.
     *
     */
    scopes: Array<ApiKeyScope>;
    /**
     * **Seconds from now**, the same name and shape RFC 6749's token response
     * uses. Omit it for the 90-day default. `0` and negative values are 422:
     * a permanent credential is not something this build offers, and the
     * ceiling is 365 days.
     *
     */
    expires_in?: number;
};

/**
 * Optional in the strongest sense — a `DELETE` with no body at all is a
 * revoke, because "revoke this" with no explanation is the common request and
 * refusing it for want of a JSON document would be a 400 on a DELETE that needs
 * nothing else.
 *
 */
export type RevokeApiKeyRequest = {
    reason?: string;
};

/**
 * The **credential**, not an id. An id would be an enumeration oracle over
 * somebody else's credentials, and a value is only useful to somebody who
 * already holds it.
 *
 */
export type IntrospectRequest = {
    /**
     * The presented value, prefix and all.
     */
    token: string;
};

/**
 * RFC 7662's shape. When `active` is false this object is **exactly**
 * `{"active": false}` and carries nothing else — a `sub` on an inactive
 * document is a user id handed to whoever asked, and a refusal that differs
 * per reason is an oracle for whether a leaked value was live.
 *
 */
export type IntrospectionResponse = {
    active: boolean;
    /**
     * The **user** the token names. It is not the tenancy key, and nothing in
     * this document falls back to it.
     *
     */
    sub?: string;
    /**
     * The tenancy boundary, and **required** on an active document. core's
     * rule is that every query is scoped by `account_id` from the token and
     * never from the request body; a token with no account cannot be used
     * against any account and is answered `{"active": false}`.
     *
     */
    account_id?: string;
    /**
     * The capability set as a **space-separated string** — core's required
     * claim name.
     *
     */
    scopes?: string;
    /**
     * An **exact mirror of `scopes`**, and the name `guard` reads. Both are
     * emitted because the fleet has not agreed on one (MD7, open) and
     * answering it here would mean rotating every credential already in a
     * customer's hand. Whichever name wins, the other is a one-line removal
     * and no credential has to be reissued. **Two names is not a contract.**
     *
     */
    scope?: string;
    /**
     * The credential's row id, which is what a consumer correlates on.
     */
    jti?: string;
    /**
     * What a human would call this credential.
     */
    name?: string;
    /**
     * The owner's **live** membership role, read at the instant of the claim
     * rather than snapshotted at issue.
     *
     * It is here for an operator reading the response, and it is **not** an
     * authorization input: core's rule is that services check scopes and ask
     * identity, and a role in a claim is a role a service might start
     * branching on.
     *
     */
    role?: string;
    iat?: number;
    exp?: number;
    last_used_at?: number;
};

/**
 * The public projection of an account. Exactly two fields, always: there is
 * no password digest, no lockout state and no timestamp here, and adding one
 * is a contract change.
 *
 */
export type User = {
    /**
     * The account's identifier, and the `subject` of its events.
     */
    id: string;
    /**
     * Always lower case. Registration normalizes before storing.
     */
    email: string;
};

export type RegisterRequest = {
    /**
     * Normalized to lower case and trimmed before storage and before comparison.
     */
    email: string;
    /**
     * At least 8 characters, hashed with argon2id. There is no composition
     * rule: requiring a mix of character classes reliably produces
     * "Password1!" and reliably rejects passphrases, and length is the
     * property that tracks entropy.
     *
     * The upper bound is a DoS control, not a policy. argon2id's cost is
     * fixed in memory but its input is not, so without it an unauthenticated
     * caller chooses the size of every login's hashing work.
     *
     */
    password: string;
};

export type LoginRequest = {
    email: string;
    /**
     * The minimum length is 1 here, not 8. A login is not a registration:
     * refusing to check a short password would be a way to learn which
     * passwords are in use, and an account may predate any rule. The upper
     * bound still applies, because it bounds the hashing work.
     *
     */
    password: string;
};

export type Session = {
    /**
     * 256 bits from crypto/rand, base64url without padding. Only its
     * SHA-256 is stored; a database dump yields no usable credential.
     *
     */
    token: string;
    /**
     * RFC3339 UTC. Judged against the service's clock, not the database's.
     */
    expires_at: string;
};

/**
 * One OpenID Connect registration. `client_secret` and `secret_digest` are
 * both absent and always will be: the secret exists once, in the 201, and
 * the digest is what the row holds.
 *
 */
export type OidcClient = {
    /**
     * The row's identifier, and the `subject` of its events. NOT the
     * `client_id` the product presents — those are different values and
     * conflating them is how a consumer ends up correlating on something it
     * cannot look up.
     *
     */
    id: string;
    /**
     * The public, protocol-visible handle: 32 random bytes, base64url without
     * padding. Unguessable rather than merely unique, because it is half of
     * the credential pair on the token endpoint.
     *
     */
    client_id: string;
    /**
     * What the login page calls the product. Required, because a login page
     * that cannot name the application asking for a password is the setup
     * for a credential-phishing page on this service's own domain.
     *
     */
    name: string;
    /**
     * The allow-list, matched EXACTLY. No prefix, no glob, no pattern. A
     * registered URI may be `https`, or `http` on loopback only; a fragment
     * and a wildcard are both refused. Sorted, and deduplicated.
     *
     */
    redirect_uris: Array<string>;
    /**
     * Always `authorization_code` today. This service issues no refresh
     * token, has no service identity for client credentials, and has no
     * consent screen for an implicit flow.
     *
     */
    grant_types: Array<'authorization_code'>;
    /**
     * A subset of what this provider implements, intersected with what the
     * provider supports, and always including `openid`. A client that did
     * not register a scope cannot be granted it by asking at the authorize
     * endpoint.
     *
     */
    scopes: Array<'openid' | 'email' | 'profile' | 'accounts'>;
    created_at: string;
    /**
     * Absent while the registration is live. A revoked registration is kept
     * rather than deleted, and this is what makes the difference readable
     * afterwards.
     *
     */
    revoked_at?: string;
};

export type RegisteredOidcClient = OidcClient & {
    /**
     * 32 random bytes, base64url, returned in this 201 and never again.
     * Only its SHA-256 is stored, so a dump of the registrations table is
     * not a set of credentials. Losing it means registering again.
     *
     */
    client_secret: string;
};

export type RegisterOidcClientRequest = {
    name: string;
    redirect_uris: Array<string>;
    grant_types: Array<'authorization_code'>;
    /**
     * Names outside this set are DROPPED rather than refused, and this is the
     * one place that is true: a product registering itself asks for what it
     * would like and the operator curates what it gets. The authorization
     * endpoint, where a caller asks for a token right now, refuses.
     *
     */
    scopes: Array<'openid' | 'email' | 'profile' | 'accounts'>;
};

/**
 * The 202 from `POST /v1/session`: a correct password, an unfinished
 * authentication, and nothing else.
 *
 * There is no `token` property here and adding one would be the bug this
 * document exists to prevent. The `challenge` is what `POST /v1/session/mfa`
 * is answered with, and it is worthless on its own.
 *
 */
export type MfaChallenge = {
    /**
     * Always `true` in this body. It is here so a client that keys off a
     * field rather than the status code has one to key off, and a client
     * that keys off the 202 does not need to read it.
     *
     */
    mfa_required: boolean;
    /**
     * 256 bits from crypto/rand, base64url without padding, presented to
     * `POST /v1/session/mfa` as `challenge` or as the
     * `__Host-mfa-challenge` cookie. Single-use and short-lived: the
     * challenge row is deleted in the same transaction that creates the
     * session, so it cannot be answered twice.
     *
     * Only its SHA-256 is stored, so a database dump yields no usable
     * challenge.
     *
     */
    challenge: string;
    /**
     * Ten minutes, judged against the service's clock. Shorter than the
     * fifteen-minute factor lockout, deliberately: a lockout outlives its
     * own challenge, so a user who trips it can answer a fresh code against
     * a fresh challenge as soon as the window ends rather than waiting for
     * the stuck challenge to expire.
     *
     */
    expires_at: string;
};

/**
 * Whether the caller has a second factor.
 *
 * A `200` with `enabled: false`, not a 404, when there is none: the question
 * has an answer for every signed-in user, and a settings page should not
 * have to distinguish "you have none" from "this is not your account".
 *
 */
export type MfaStatus = {
    enabled: boolean;
    /**
     * Absent when `enabled` is false. `"totp"` and "no method yet" are
     * different answers, which is why this is `omitempty` rather than an
     * empty string.
     *
     */
    method?: 'totp';
    /**
     * When the credential was confirmed. Absent when `enabled` is false.
     */
    enrolled_at?: string;
    /**
     * How many unused recovery codes are left. Absent when `enabled` is
     * false.
     *
     * It is here so a client can say "2 left — print a new set" while there
     * are still two. A user with zero codes and a lost phone is a support
     * ticket, and the honest thing is to say so beforehand.
     *
     */
    recovery_codes_remaining?: number;
};

/**
 * The body of every route that changes or relies on an existing second
 * factor.
 *
 * **One field, not `code` and `recovery_code`.** The consequence of getting
 * this wrong is identical either way, and two fields would let a client put
 * a recovery code in the TOTP field and be told the code was malformed rather
 * than not accepted, which is a worse error to act on. This service decides
 * which shape it is and then answers the same way for both.
 *
 */
export type FactorRequest = {
    /**
     * A six-digit TOTP code, or a recovery code in the form
     * `XXXX-XXXX-XXXX-XXXX`. Surrounding whitespace is ignored; nothing else
     * is.
     *
     * A code is not echoed back in any response, and never appears in a log
     * line or a problem body.
     *
     */
    code: string;
};

/**
 * The second half of a login. `challenge` is optional here and required in
 * effect — omitting it entirely, with no challenge cookie either, is a 401.
 *
 */
export type CompleteSecondFactorRequest = {
    /**
     * The challenge from the 202. **Optional, because the
     * `__Host-mfa-challenge` cookie is accepted instead** — the cookie is the
     * browser's route and this field is the API client's, exactly as
     * `POST /v1/session` returns the session token in the body as well as in
     * the cookie so a non-browser client has a way in.
     *
     * When both are present the body wins. A client holding both has said
     * which one it means, and answering from ambient browser state would
     * make the result depend on invisible cookies.
     *
     */
    challenge?: string;
    /**
     * A six-digit TOTP code, or a recovery code. Same shapes as `FactorRequest.code`.
     */
    code: string;
};

export type StartEnrollmentRequest = {
    /**
     * Required **only** when this account already has a credential, where
     * the request is a rotation.
     *
     * The service decides which case it is from the rows, so sending a code
     * for a first enrollment is not wrong, only redundant — which is why
     * this is optional in the schema and required in prose. Refusing the
     * redundant one would be a 422 that teaches a client nothing.
     *
     */
    code?: string;
};

/**
 * A pending TOTP enrollment, and the only response in this document that
 * contains a TOTP secret.
 *
 * **The secret is here and nowhere else.** There is no endpoint that
 * re-reads it, so a client that loses this body starts a new enrollment,
 * which mints a new secret. The reasoning is the one an OIDC
 * `client_secret` follows: a secret this service can produce again is a
 * secret this service is storing, and a stored TOTP secret is a second
 * factor for whoever reads the database.
 *
 * Nothing here is a session, and nothing here is MFA. A pending enrollment
 * is unread by the login path, so until `/confirm` is called this account
 * has no second factor.
 *
 */
export type StartedEnrollment = {
    /**
     * The id to confirm. It is the pending row's own id, and another user's,
     * an expired one's and an already-confirmed one's are all 404 — so it is
     * not a way to learn which enrollments exist.
     *
     */
    enrollment_id: string;
    /**
     * base32, no padding, 160 bits from crypto/rand. The shared secret for
     * `HMAC-SHA1`, and the half of the factor the phone holds.
     *
     * Stored **encrypted**, not hashed: verifying a code means computing an
     * HMAC with this value, so a hash would be useless. At rest it is
     * AES-256-GCM ciphertext under `MFA_ENCRYPTION_KEY`, with the user's id
     * as additional authenticated data.
     *
     */
    secret: string;
    /**
     * An `otpauth://totp/…` URI, which is what a QR code encodes. Contains
     * `secret`, so it is not shareable and not cacheable.
     *
     */
    provisioning_uri: string;
    method: 'totp';
    /**
     * The code length. Fixed, and 6 because that is what authenticator apps display.
     */
    digits: 6;
    /**
     * The step, 30 seconds. Returned rather than assumed so a client can
     * render a countdown without hard-coding it.
     *
     */
    period_seconds: 30;
    /**
     * `SHA1`, and not a preference: it is the only HMAC every authenticator
     * app implements. A user whose app rejected SHA1 has no app.
     *
     */
    algorithm: 'SHA1';
    /**
     * Ten minutes. An unconfirmed enrollment is deleted after this, because
     * a stored-but-never-confirmed secret is exactly the state that locks
     * somebody out of their own account.
     *
     */
    expires_at: string;
    /**
     * `true` when this enrollment is replacing an existing credential.
     *
     * The old secret is **still live** until this one is confirmed, so an
     * abandoned rotation costs nothing and the user is not left with a dead
     * phone. `replaced` is what lets a client say so out loud rather than
     * leave them to discover it.
     *
     */
    replaced: boolean;
};

export type ConfirmEnrollmentRequest = {
    /**
     * A six-digit code computed from this enrollment's `secret`.
     *
     * Required always, and an absent one is the only 422 on this surface:
     * the code is required rather than wrong, and telling those apart saves
     * a user staring at a six-digit box wondering what they did.
     *
     * Wrong, already spent, malformed, and produced by a secret this
     * rotation has already replaced are all the same 401. They are four
     * different facts and a client that can tell them apart learns which to
     * keep trying.
     *
     */
    code: string;
};

/**
 * MFA is live, and here are the recovery codes, once.
 *
 * **Every session this account holds was revoked to produce this response**,
 * including the caller's. A session minted under a one-factor policy was
 * minted on a password alone, and leaving it alive means whoever holds it
 * does not have to solve the new problem.
 *
 * The response is therefore `200` and not `204`: there is real content, and
 * that content exists exactly once.
 *
 */
export type ConfirmedEnrollment = {
    enabled: true;
    method: 'totp';
    enrolled_at: string;
    /**
     * Ten codes, 80 bits each, and **never readable again**: no endpoint
     * re-reads them and no column stores them, only a SHA-256 digest per
     * code. Each is accepted exactly once and is destroyed by use.
     *
     * 80 bits is a floor, not a style choice. A six-digit TOTP code is 20
     * bits and is only safe because it changes every 30 seconds and cannot
     * be retried; a recovery code does not change, so a short one would be
     * guessable at leisure.
     *
     */
    recovery_codes: [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
    ];
    /**
     * `true` when this confirmation replaced a credential. The old one is
     * deleted by this call, which is what makes its codes stop being
     * accepted — the old phone stops working at the moment of confirmation,
     * not at the moment the rotation started.
     *
     */
    replaced_existing_secret: boolean;
};

/**
 * A fresh set of recovery codes. The old set is destroyed by this call, in
 * the same transaction that writes the new one.
 *
 * A partial write would leave a user with two live sets, which is a second
 * recovery path through codes nobody audited and nobody will ever see in a
 * log. That is the requirement this route exists to satisfy.
 *
 */
export type RecoveryCodesResponse = {
    /**
     * The new set, returned once and never again. Same 80-bit value as
     * `ConfirmedEnrollment.recovery_codes`, and the same one-shot guarantee.
     *
     */
    recovery_codes: [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
    ];
    issued_at: string;
    /**
     * Always 10. It is the count of the set just issued rather than a read
     * back from storage, because a client rendering "you now have N codes"
     * wants N and not a round trip to learn it.
     *
     */
    recovery_codes_remaining: 10;
};

/**
 * An address to look an account up by, on the three routes that start a
 * flow.
 *
 * **It is never the address that gets proved or moved.** On
 * `requestEmailVerification` it identifies the account whose *stored* address
 * is proved, and on `requestEmailChange` it is the address being moved TO.
 * A token that verified whatever address this field carried would be a
 * registration of somebody else's inbox.
 *
 */
export type RecoveryEmailRequest = {
    /**
     * Normalized to lower case and trimmed before comparison.
     */
    email: string;
};

/**
 * A single-use token from an emailed link. It is one field on purpose, and
 * the three routes that take it do not all accept the same set: a shared type
 * with an optional `password` would invite a client to send a password to a
 * verification endpoint, where it would be ignored — and "ignored" is a worse
 * answer than "refused", because a caller that believed the field was
 * accepted would not know to retry.
 *
 * **The token is the credential.** These routes are anonymous, so the only
 * thing being authenticated is the value in this field.
 *
 */
export type RecoveryTokenRequest = {
    /**
     * 256 bits from crypto/rand, base64url without padding. Only its SHA-256
     * is stored, so a database dump yields no usable credential.
     *
     * 43 characters, and the length is load-bearing on the client side rather
     * than incidental: it is what tells a caller the value is complete before
     * it is pasted into a URL.
     *
     */
    token: string;
};

export type ConfirmPasswordResetRequest = {
    /**
     * The token from the emailed link. See `RecoveryTokenRequest`.
     */
    token: string;
    /**
     * The same rules and the same argon2id hashing a registration uses, and
     * enforced identically. A new password is not an excuse to accept one
     * that registration would have refused.
     *
     * The upper bound is a DoS control on an unauthenticated route: argon2id's
     * cost is fixed in memory but its input is not, so without it a caller
     * with no session chooses the size of the hashing work.
     *
     */
    password: string;
};

/**
 * The body of every route that has been asked to send a message.
 *
 * **Exactly one field, with one value, ever.** That is the whole of the
 * account-enumeration defence on `requestPasswordReset`,
 * `requestEmailVerification` and `confirmEmailChangeCurrentAddress`: a
 * registered address, an unregistered one and an address inside the cooldown
 * all get these same bytes. Adding an `expires_at`, an `email` or a `sent`
 * boolean here would reinstate an oracle without touching a test, so the
 * handler's type is a constant for the same reason.
 *
 */
export type Accepted = {
    status: 'accepted';
};

/**
 * Whether one address is proved, as `GET /v1/email-verification` reports it.
 *
 * The boolean and the timestamp say the same thing in two shapes and both are
 * present because a client needs one and not the other: a boolean for a
 * conditional render, an instant for "verified on". The timestamp is
 * **absent** rather than null when the address was never verified — "never
 * verified" and "verified at the epoch" are different answers and only the
 * first is true.
 *
 */
export type VerificationStatus = {
    /**
     * The address on the account. Always lower case.
     */
    email: string;
    /**
     * False both for an address that was never proved AND for one that was
     * proved and then moved — a changed address lands unverified.
     *
     */
    email_verified: boolean;
    /**
     * RFC3339 UTC, absent when `email_verified` is false. Judged against the
     * service's clock, not the database's.
     *
     */
    email_verified_at?: string;
};

/**
 * The state of a two-sided address change.
 *
 * **Both addresses are named** and neither is secret: `current_email` is the
 * address the account has now and `new_email` is the one that was typed. What
 * it does not carry is a token, a digest or a row id — this flow is addressed
 * by its tokens, and there is no id in it for a client to hold.
 *
 * On the `200` from `confirmEmailChangeNewAddress` the move has completed, so
 * `current_email` and `new_email` are the same value, `expires_at` is absent,
 * and `email_verified` is present and **false**.
 *
 */
export type EmailChange = {
    current_email: string;
    new_email: string;
    /**
     * The deadline for the change. 24 hours from the request, and **both
     * halves share it** rather than each getting its own clock — a change
     * cannot be kept alive indefinitely by confirming the first half over and
     * over. Absent once the move has completed.
     *
     */
    expires_at?: string;
    /**
     * Present only on the `200` from `confirmEmailChangeNewAddress`, where it
     * is always false. An email change CLEARS the verification, so a client
     * that reads this has to prompt for a fresh one rather than assuming the
     * address it just moved to is proved.
     *
     */
    email_verified?: boolean;
};

/**
 * The cafaye error envelope: RFC 9457 plus core's `code` and `trace_id`.
 * Every non-2xx response from this service is this shape. No service invents
 * its own error body.
 *
 */
export type Problem = {
    /**
     * A stable `https://errors.cafaye.com/<code>` URI — the machine-readable contract.
     */
    type: string;
    /**
     * A fixed human-readable summary for the code. May be reworded without a version bump.
     */
    title: string;
    /**
     * The HTTP status, repeated in the body.
     */
    status: number;
    /**
     * Specific to this occurrence and not parsed by clients. Never contains
     * an internal error, a host, a role or a query fragment: those go to the
     * log under the same `trace_id`.
     *
     */
    detail: string;
    /**
     * The request path. Never includes the query string, which can carry an address.
     */
    instance: string;
    /**
     * The last segment of `type`, in snake_case.
     */
    code: 'unauthorized' | 'forbidden' | 'not_found' | 'conflict' | 'validation_failed' | 'rate_limited' | 'idempotency_key_reused' | 'internal' | 'unavailable' | 'account_locked' | 'method_not_allowed' | 'invalid_json' | 'payload_too_large' | 'service_unavailable';
    /**
     * Always present, always equal to the `X-Trace-Id` response header.
     */
    trace_id: string;
    /**
     * Per-field failures. Present only on 422.
     */
    errors?: Array<FieldError>;
};

export type FieldError = {
    /**
     * The request field that failed.
     */
    field: string;
    /**
     * A stable slug, safe to switch on. `required`, `invalid_format`,
     * `too_short`, `too_long`.
     *
     */
    code: string;
};

export type Health = {
    status: 'ok' | 'unavailable';
    /**
     * The dependencies probed, comma separated, or `none`. Present on `/readyz` only.
     */
    deps?: string;
};

/**
 * The account. A caller who is not a member of it gets 404 and never 403,
 * because a 403 would confirm the account exists to somebody guessing ids.
 *
 */
export type AccountId = string;

export type RegisterUserData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type RegisterUserErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * An account already exists for that address.
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * The account was created.
     */
    201: User;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type DeleteSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/session';
};

export type DeleteSessionErrors = {
    /**
     * No usable credential, or one that no longer resolves.
     */
    401: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * The session was revoked and the cookie cleared.
     */
    204: void;
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type CreateSessionData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/v1/session';
};

export type CreateSessionErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The credentials were refused. The body is identical whether the
     * address is unregistered or the password is wrong, and says nothing
     * about which.
     *
     */
    401: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The account is locked after too many consecutive failures. The
     * `Retry-After` header and the `detail` both carry the remaining window
     * in whole seconds, rounded up.
     *
     * The window is deliberately **not** an entry in `errors[]`: core scopes
     * that array to 422 and to fields of the request, and `retry_after` is
     * not one.
     *
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type CreateSessionError = CreateSessionErrors[keyof CreateSessionErrors];

export type CreateSessionResponses = {
    /**
     * The credentials were correct and a session now exists. The same token
     * is in the body and in the cookie.
     *
     */
    200: Session;
    /**
     * The password was correct and this account has a second factor. **No
     * session exists** and no session cookie is set.
     *
     * The `challenge` is a one-time credential for `POST /v1/session/mfa`,
     * valid for ten minutes and single-use. It is also set as the
     * `__Host-mfa-challenge` cookie, which is the browser's copy and carries
     * the same value.
     *
     * There is no `token` field in this schema, and that is deliberate: a
     * client that looks for one must handle its absence rather than treat an
     * empty string as a value.
     *
     */
    202: MfaChallenge;
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type CompleteSecondFactorData = {
    body: CompleteSecondFactorRequest;
    path?: never;
    query?: never;
    url: '/v1/session/mfa';
};

export type CompleteSecondFactorErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The factor was refused, or no challenge was presented. The body is the
     * same for a wrong code, a recovery code that was already spent, a TOTP
     * code whose step has been used, and a value that is neither shape: five
     * different facts, and an attacker who can tell them apart learns which to
     * keep trying.
     *
     */
    401: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked after too many consecutive failures. The
     * `Retry-After` header carries the remaining window in whole seconds.
     *
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
    /**
     * This deployment cannot verify a second factor, because
     * `MFA_ENCRYPTION_KEY` is not configured. It is a 503 and not a 404 on
     * purpose: a 404 would say the service has never heard of MFA, and a
     * client that believed that would be free to treat the absence of a
     * challenge as the absence of a requirement.
     *
     */
    503: Problem;
};

export type CompleteSecondFactorError = CompleteSecondFactorErrors[keyof CompleteSecondFactorErrors];

export type CompleteSecondFactorResponses = {
    /**
     * The second factor was accepted and a session now exists. The same token
     * is in the body and in the cookie, and the challenge cookie is cleared.
     *
     */
    200: Session;
};

export type CompleteSecondFactorResponse = CompleteSecondFactorResponses[keyof CompleteSecondFactorResponses];

export type DisableMfaData = {
    body: FactorRequest;
    path?: never;
    query?: never;
    url: '/v1/mfa';
};

export type DisableMfaErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * This account has no second factor, so there was nothing to turn off.
     * A 409 rather than a 404: the caller is asking to change something that
     * does not exist, which is a different question from "is this yours".
     *
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked after too many consecutive failures.
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type DisableMfaError = DisableMfaErrors[keyof DisableMfaErrors];

export type DisableMfaResponses = {
    /**
     * MFA is off, every session is revoked, and the cookie is cleared.
     */
    204: void;
};

export type DisableMfaResponse = DisableMfaResponses[keyof DisableMfaResponses];

export type GetMfaStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/mfa';
};

export type GetMfaStatusErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type GetMfaStatusError = GetMfaStatusErrors[keyof GetMfaStatusErrors];

export type GetMfaStatusResponses = {
    /**
     * The caller's second-factor status.
     */
    200: MfaStatus;
};

export type GetMfaStatusResponse = GetMfaStatusResponses[keyof GetMfaStatusResponses];

export type StartMfaEnrollmentData = {
    body: StartEnrollmentRequest;
    path?: never;
    query?: never;
    url: '/v1/mfa/enrollments';
};

export type StartMfaEnrollmentErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked, so a rotation cannot be authorised.
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type StartMfaEnrollmentError = StartMfaEnrollmentErrors[keyof StartMfaEnrollmentErrors];

export type StartMfaEnrollmentResponses = {
    /**
     * A pending enrollment, and its one-time values.
     */
    201: StartedEnrollment;
};

export type StartMfaEnrollmentResponse = StartMfaEnrollmentResponses[keyof StartMfaEnrollmentResponses];

export type ConfirmMfaEnrollmentData = {
    body: ConfirmEnrollmentRequest;
    path: {
        /**
         * The pending enrollment's own id. Another user's, an expired one's, and
         * one that has already been confirmed are all `404`, so the id is not a
         * way to learn which enrollments exist.
         *
         */
        enrollmentId: string;
    };
    query?: never;
    url: '/v1/mfa/enrollments/{enrollmentId}/confirm';
};

export type ConfirmMfaEnrollmentErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The code was refused. One sentence for every way it can fail: wrong,
     * already spent, malformed, or produced by a secret this rotation has
     * already replaced.
     *
     */
    401: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ConfirmMfaEnrollmentError = ConfirmMfaEnrollmentErrors[keyof ConfirmMfaEnrollmentErrors];

export type ConfirmMfaEnrollmentResponses = {
    /**
     * MFA is live, and the recovery codes are returned once.
     */
    200: ConfirmedEnrollment;
};

export type ConfirmMfaEnrollmentResponse = ConfirmMfaEnrollmentResponses[keyof ConfirmMfaEnrollmentResponses];

export type RegenerateMfaRecoveryCodesData = {
    body: FactorRequest;
    path?: never;
    query?: never;
    url: '/v1/mfa/recovery-codes';
};

export type RegenerateMfaRecoveryCodesErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The factor was refused, or this account has no second factor.
     *
     */
    401: Problem;
    /**
     * This account has no second factor, so there are no codes to replace.
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The second factor is locked after too many consecutive failures.
     */
    423: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RegenerateMfaRecoveryCodesError = RegenerateMfaRecoveryCodesErrors[keyof RegenerateMfaRecoveryCodesErrors];

export type RegenerateMfaRecoveryCodesResponses = {
    /**
     * A new set, returned once, and the count that replaced the old one.
     */
    200: RecoveryCodesResponse;
};

export type RegenerateMfaRecoveryCodesResponse = RegenerateMfaRecoveryCodesResponses[keyof RegenerateMfaRecoveryCodesResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type GetCurrentUserErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * The authenticated user.
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type RequestPasswordResetData = {
    body: RecoveryEmailRequest;
    path?: never;
    query?: never;
    url: '/v1/password-resets';
};

export type RequestPasswordResetErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
    /**
     * This deployment has no mail delivery path, so it cannot send that link.
     *
     * A 503 and not a 500, because the caller can act on it: a product that sees
     * this knows not to render "check your inbox", which is the whole reason it
     * is not an opaque server error. And a 503 and not a 404, for the same reason
     * `POST /v1/session/mfa` answers 503 — a 404 would say this service has never
     * heard of password recovery, which is the one answer that is both false and
     * useless.
     *
     * **It is checked before the address is looked up**, so a deployment that
     * cannot send refuses a request for a registered address and one for an
     * unregistered one in the same place. Without that ordering "503 against 202"
     * would be an account-existence oracle, and it would be the most expensive one
     * in this service to discover.
     *
     */
    503: Problem;
};

export type RequestPasswordResetError = RequestPasswordResetErrors[keyof RequestPasswordResetErrors];

export type RequestPasswordResetResponses = {
    /**
     * Accepted. Identical for every address.
     */
    202: Accepted;
};

export type RequestPasswordResetResponse = RequestPasswordResetResponses[keyof RequestPasswordResetResponses];

export type ConfirmPasswordResetData = {
    body: ConfirmPasswordResetRequest;
    path?: never;
    query?: never;
    url: '/v1/password-resets/confirm';
};

export type ConfirmPasswordResetErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No live token matches — it never existed, expired, was spent, or belongs to another flow.
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ConfirmPasswordResetError = ConfirmPasswordResetErrors[keyof ConfirmPasswordResetErrors];

export type ConfirmPasswordResetResponses = {
    /**
     * The password changed and every session and access token was revoked.
     * No body.
     *
     */
    204: void;
};

export type ConfirmPasswordResetResponse = ConfirmPasswordResetResponses[keyof ConfirmPasswordResetResponses];

export type RequestEmailVerificationData = {
    body: RecoveryEmailRequest;
    path?: never;
    query?: never;
    url: '/v1/email-verifications';
};

export type RequestEmailVerificationErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * This account's address is already verified, so there is nothing to prove.
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
    /**
     * This deployment has no mail delivery path, so it cannot send that link.
     *
     * A 503 and not a 500, because the caller can act on it: a product that sees
     * this knows not to render "check your inbox", which is the whole reason it
     * is not an opaque server error. And a 503 and not a 404, for the same reason
     * `POST /v1/session/mfa` answers 503 — a 404 would say this service has never
     * heard of password recovery, which is the one answer that is both false and
     * useless.
     *
     * **It is checked before the address is looked up**, so a deployment that
     * cannot send refuses a request for a registered address and one for an
     * unregistered one in the same place. Without that ordering "503 against 202"
     * would be an account-existence oracle, and it would be the most expensive one
     * in this service to discover.
     *
     */
    503: Problem;
};

export type RequestEmailVerificationError = RequestEmailVerificationErrors[keyof RequestEmailVerificationErrors];

export type RequestEmailVerificationResponses = {
    /**
     * Accepted. Identical for every address.
     */
    202: Accepted;
};

export type RequestEmailVerificationResponse = RequestEmailVerificationResponses[keyof RequestEmailVerificationResponses];

export type ConfirmEmailVerificationData = {
    body: RecoveryTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/email-verifications/confirm';
};

export type ConfirmEmailVerificationErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No live token matches — it never existed, expired, was spent, or belongs to another flow.
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ConfirmEmailVerificationError = ConfirmEmailVerificationErrors[keyof ConfirmEmailVerificationErrors];

export type ConfirmEmailVerificationResponses = {
    /**
     * The address is now marked verified. No body.
     */
    204: void;
};

export type ConfirmEmailVerificationResponse = ConfirmEmailVerificationResponses[keyof ConfirmEmailVerificationResponses];

export type GetEmailVerificationStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/email-verification';
};

export type GetEmailVerificationStatusErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type GetEmailVerificationStatusError = GetEmailVerificationStatusErrors[keyof GetEmailVerificationStatusErrors];

export type GetEmailVerificationStatusResponses = {
    /**
     * The caller's verification state.
     */
    200: VerificationStatus;
};

export type GetEmailVerificationStatusResponse = GetEmailVerificationStatusResponses[keyof GetEmailVerificationStatusResponses];

export type RequestEmailChangeData = {
    body: RecoveryEmailRequest;
    path?: never;
    query?: never;
    url: '/v1/email-changes';
};

export type RequestEmailChangeErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * An account already exists for the new address.
     */
    409: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
    /**
     * This deployment has no mail delivery path, so it cannot send that link.
     *
     * A 503 and not a 500, because the caller can act on it: a product that sees
     * this knows not to render "check your inbox", which is the whole reason it
     * is not an opaque server error. And a 503 and not a 404, for the same reason
     * `POST /v1/session/mfa` answers 503 — a 404 would say this service has never
     * heard of password recovery, which is the one answer that is both false and
     * useless.
     *
     * **It is checked before the address is looked up**, so a deployment that
     * cannot send refuses a request for a registered address and one for an
     * unregistered one in the same place. Without that ordering "503 against 202"
     * would be an account-existence oracle, and it would be the most expensive one
     * in this service to discover.
     *
     */
    503: Problem;
};

export type RequestEmailChangeError = RequestEmailChangeErrors[keyof RequestEmailChangeErrors];

export type RequestEmailChangeResponses = {
    /**
     * The change is recorded and the first link is on its way to the current address.
     */
    201: EmailChange;
};

export type RequestEmailChangeResponse = RequestEmailChangeResponses[keyof RequestEmailChangeResponses];

export type ConfirmEmailChangeCurrentAddressData = {
    body: RecoveryTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/email-changes/current-address';
};

export type ConfirmEmailChangeCurrentAddressErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No live first-half token matches.
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
    /**
     * This deployment has no mail delivery path, so it cannot send that link.
     *
     * A 503 and not a 500, because the caller can act on it: a product that sees
     * this knows not to render "check your inbox", which is the whole reason it
     * is not an opaque server error. And a 503 and not a 404, for the same reason
     * `POST /v1/session/mfa` answers 503 — a 404 would say this service has never
     * heard of password recovery, which is the one answer that is both false and
     * useless.
     *
     * **It is checked before the address is looked up**, so a deployment that
     * cannot send refuses a request for a registered address and one for an
     * unregistered one in the same place. Without that ordering "503 against 202"
     * would be an account-existence oracle, and it would be the most expensive one
     * in this service to discover.
     *
     */
    503: Problem;
};

export type ConfirmEmailChangeCurrentAddressError = ConfirmEmailChangeCurrentAddressErrors[keyof ConfirmEmailChangeCurrentAddressErrors];

export type ConfirmEmailChangeCurrentAddressResponses = {
    /**
     * The current address is confirmed and the second link is on its way.
     */
    202: Accepted;
};

export type ConfirmEmailChangeCurrentAddressResponse = ConfirmEmailChangeCurrentAddressResponses[keyof ConfirmEmailChangeCurrentAddressResponses];

export type ConfirmEmailChangeNewAddressData = {
    body: RecoveryTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/email-changes/new-address';
};

export type ConfirmEmailChangeNewAddressErrors = {
    /**
     * The body is not a JSON object this endpoint accepts.
     */
    400: Problem;
    /**
     * No live second-half token matches.
     */
    404: Problem;
    /**
     * The body is larger than the 4096 bytes this endpoint accepts.
     */
    413: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ConfirmEmailChangeNewAddressError = ConfirmEmailChangeNewAddressErrors[keyof ConfirmEmailChangeNewAddressErrors];

export type ConfirmEmailChangeNewAddressResponses = {
    /**
     * The address moved and every session and access token was revoked.
     */
    200: EmailChange;
};

export type ConfirmEmailChangeNewAddressResponse = ConfirmEmailChangeNewAddressResponses[keyof ConfirmEmailChangeNewAddressResponses];

export type ListOidcClientsData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients';
};

export type ListOidcClientsErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ListOidcClientsError = ListOidcClientsErrors[keyof ListOidcClientsErrors];

export type ListOidcClientsResponses = {
    /**
     * The account's registrations.
     */
    200: Array<OidcClient>;
};

export type ListOidcClientsResponse = ListOidcClientsResponses[keyof ListOidcClientsResponses];

export type RegisterOidcClientData = {
    body: RegisterOidcClientRequest;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients';
};

export type RegisterOidcClientErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RegisterOidcClientError = RegisterOidcClientErrors[keyof RegisterOidcClientErrors];

export type RegisterOidcClientResponses = {
    /**
     * The registration, and its secret.
     */
    201: RegisteredOidcClient;
};

export type RegisterOidcClientResponse = RegisterOidcClientResponses[keyof RegisterOidcClientResponses];

export type RevokeOidcClientData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
        /**
         * The registration's row id — not the `client_id` the product presents.
         * The row id is what the revocation event's `subject` is, and what the
         * other three routes name.
         *
         */
        client_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients/{client_id}';
};

export type RevokeOidcClientErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The registration is already revoked. A 204 either way would leave an
     * operator who clicked twice believing they had just destroyed a second
     * credential.
     *
     */
    409: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RevokeOidcClientError = RevokeOidcClientErrors[keyof RevokeOidcClientErrors];

export type RevokeOidcClientResponses = {
    /**
     * The registration is revoked. No body.
     */
    204: void;
};

export type RevokeOidcClientResponse = RevokeOidcClientResponses[keyof RevokeOidcClientResponses];

export type GetOidcClientData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
        /**
         * The registration's row id — not the `client_id` the product presents.
         * The row id is what the revocation event's `subject` is, and what the
         * other three routes name.
         *
         */
        client_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/oidc-clients/{client_id}';
};

export type GetOidcClientErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type GetOidcClientError = GetOidcClientErrors[keyof GetOidcClientErrors];

export type GetOidcClientResponses = {
    /**
     * The registration.
     */
    200: OidcClient;
};

export type GetOidcClientResponse = GetOidcClientResponses[keyof GetOidcClientResponses];

export type ListApiKeysData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/api-keys';
};

export type ListApiKeysErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * The account's credentials.
     */
    200: Array<ApiKey>;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type MintApiKeyData = {
    body: MintApiKeyRequest;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/api-keys';
};

export type MintApiKeyErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * This account already has a live token with that name.
     */
    409: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type MintApiKeyError = MintApiKeyErrors[keyof MintApiKeyErrors];

export type MintApiKeyResponses = {
    /**
     * The credential, and its secret. `token` is the only place it appears.
     *
     */
    201: IssuedApiKey;
};

export type MintApiKeyResponse = MintApiKeyResponses[keyof MintApiKeyResponses];

export type RevokeApiKeyData = {
    body?: RevokeApiKeyRequest;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
        /**
         * The credential's row id. A malformed one, one in another account and one
         * that never existed are all `404` — the same answer, so an id is not a way
         * to learn which credentials exist.
         *
         */
        key_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/api-keys/{key_id}';
};

export type RevokeApiKeyErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The credential was already revoked.
     */
    409: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RevokeApiKeyError = RevokeApiKeyErrors[keyof RevokeApiKeyErrors];

export type RevokeApiKeyResponses = {
    /**
     * The credential no longer works.
     */
    204: void;
};

export type RevokeApiKeyResponse = RevokeApiKeyResponses[keyof RevokeApiKeyResponses];

export type ListAccountAuditLogData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: {
        /**
         * Rows to return. Defaults to 25; refused above 100. `0` means the
         * default, so a generated client that sends its zero value still works.
         *
         */
        limit?: number;
        /**
         * The opaque `next` cursor from the previous page. Empty means the
         * newest page.
         *
         */
        before?: string;
    };
    url: '/v1/accounts/{account_id}/admin/audit-log';
};

export type ListAccountAuditLogErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * Not an admin of this account, or the token does not carry
     * `audit_log:read`, or **a browser session was presented** — the admin
     * surface is token-only.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type ListAccountAuditLogError = ListAccountAuditLogErrors[keyof ListAccountAuditLogErrors];

export type ListAccountAuditLogResponses = {
    /**
     * One page of the account's admin audit trail, newest first.
     */
    200: AuditLogPage;
};

export type ListAccountAuditLogResponse = ListAccountAuditLogResponses[keyof ListAccountAuditLogResponses];

export type RevokeAccountInvitationData = {
    body?: never;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
        /**
         * The pending invitation's row id. A malformed one, one in another account,
         * one that never existed and one already redeemed are each answered the way
         * their cause requires, but a caller **cannot tell "no such invitation" from
         * "an invitation in an account you are not in"** — that would be a probe for
         * which invitation ids exist.
         *
         */
        invitation_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/admin/invitations/{invitation_id}';
};

export type RevokeAccountInvitationErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * Not an admin of this account, the token does not carry
     * `account_invitations:write`, or a browser session was presented.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The invitation was already accepted or already revoked.
     */
    409: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RevokeAccountInvitationError = RevokeAccountInvitationErrors[keyof RevokeAccountInvitationErrors];

export type RevokeAccountInvitationResponses = {
    /**
     * The invitation no longer redeems, and an audit record naming the
     * credential that did it exists in the same transaction.
     *
     */
    204: void;
};

export type RevokeAccountInvitationResponse = RevokeAccountInvitationResponses[keyof RevokeAccountInvitationResponses];

export type RevokeAccountInvitationsData = {
    body: BulkInvitationRevocation;
    path: {
        /**
         * The account. A caller who is not a member of it gets 404 and never 403,
         * because a 403 would confirm the account exists to somebody guessing ids.
         *
         */
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/admin/invitation-revocations';
};

export type RevokeAccountInvitationsErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * Not an **owner** of this account, the token does not carry
     * `account_invitations:write`, or a browser session was presented.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type RevokeAccountInvitationsError = RevokeAccountInvitationsErrors[keyof RevokeAccountInvitationsErrors];

export type RevokeAccountInvitationsResponses = {
    /**
     * The batch ran. `revoked` may be smaller than `requested`; both are
     * reported rather than reconciled.
     *
     */
    200: BulkRevocationResult;
};

export type RevokeAccountInvitationsResponse = RevokeAccountInvitationsResponses[keyof RevokeAccountInvitationsResponses];

export type IntrospectApiKeyData = {
    body: IntrospectRequest;
    path?: never;
    query?: never;
    url: '/v1/introspections';
};

export type IntrospectApiKeyErrors = {
    /**
     * No usable credential: none was presented, or it is unknown, expired or
     * revoked. One body for all four.
     *
     */
    401: Problem;
    /**
     * The caller can see the resource and may not act on it. The route's minimum
     * role is higher than theirs.
     *
     * Never used for "you are not a member of this account" — that is 404, so
     * the response cannot confirm that an account id somebody guessed is real.
     *
     */
    403: Problem;
    /**
     * No such resource, or one this caller may not know about. One status and
     * one sentence for both, because a 403 for "not a member" would confirm the
     * account exists to somebody guessing ids.
     *
     */
    404: Problem;
    /**
     * The request was understood and is not acceptable. `errors[]` names the fields.
     */
    422: Problem;
    /**
     * The request could not be completed. The cause is in the service's log
     * under the returned `trace_id` and is never in the response.
     *
     */
    500: Problem;
};

export type IntrospectApiKeyError = IntrospectApiKeyErrors[keyof IntrospectApiKeyErrors];

export type IntrospectApiKeyResponses = {
    /**
     * The claim document, or `{"active": false}` when the token cannot be
     * used.
     *
     */
    200: IntrospectionResponse;
};

export type IntrospectApiKeyResponse = IntrospectApiKeyResponses[keyof IntrospectApiKeyResponses];

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type LivenessResponses = {
    /**
     * The process is running.
     */
    200: Health;
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadinessErrors = {
    /**
     * At least one dependency did not answer.
     *
     * This is the one non-2xx response in the service that is not a problem
     * document, and it is a known conflict rather than an oversight. See
     * "Known gaps", item 4.
     *
     */
    503: Health;
};

export type ReadinessError = ReadinessErrors[keyof ReadinessErrors];

export type ReadinessResponses = {
    /**
     * Every dependency answered.
     */
    200: Health;
};

export type ReadinessResponse = ReadinessResponses[keyof ReadinessResponses];
