/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/billing.yaml
//         billing, document version 1.3.0,
//         vendored from git@github.com:cafaye/billing.git
//         at commit 72519931c18773aacd66ff8dd942a209af10761e
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CancelSubscriptionData, CancelSubscriptionErrors, CancelSubscriptionResponses, ChangeSubscriptionPlanData, ChangeSubscriptionPlanErrors, ChangeSubscriptionPlanResponses, CreateCustomerData, CreateCustomerErrors, CreateCustomerResponses, CreatePlanData, CreatePlanErrors, CreatePlanResponses, CreateSubscriptionCheckoutData, CreateSubscriptionCheckoutErrors, CreateSubscriptionCheckoutResponses, GetCustomerData, GetCustomerErrors, GetCustomerResponses, GetPlanData, GetPlanErrors, GetPlanResponses, GetSubscriptionData, GetSubscriptionEntitlementsData, GetSubscriptionEntitlementsErrors, GetSubscriptionEntitlementsResponses, GetSubscriptionErrors, GetSubscriptionResponses, ListCustomersData, ListCustomersErrors, ListCustomersResponses, ListPlansData, ListPlansErrors, ListPlansResponses, ListSubscriptionsData, ListSubscriptionsErrors, ListSubscriptionsResponses, ReceiveStripeWebhookData, ReceiveStripeWebhookErrors, ReceiveStripeWebhookResponses, UpdateCustomerData, UpdateCustomerErrors, UpdateCustomerResponses, UpdatePlanData, UpdatePlanErrors, UpdatePlanResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List customers
 */
export const listCustomers = <ThrowOnError extends boolean = false>(options?: Options<ListCustomersData, ThrowOnError>): RequestResult<ListCustomersResponses, ListCustomersErrors, ThrowOnError> => (options?.client ?? client).get<ListCustomersResponses, ListCustomersErrors, ThrowOnError>({ url: '/v1/customers', ...options });

/**
 * Create a customer
 *
 * Creates billing's record of an identity user or account. One customer per (owner, processor), and one customer per `processor_customer_id`: a second attempt at either is a 409.
 */
export const createCustomer = <ThrowOnError extends boolean = false>(options: Options<CreateCustomerData, ThrowOnError>): RequestResult<CreateCustomerResponses, CreateCustomerErrors, ThrowOnError> => (options.client ?? client).post<CreateCustomerResponses, CreateCustomerErrors, ThrowOnError>({
    url: '/v1/customers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a customer
 */
export const getCustomer = <ThrowOnError extends boolean = false>(options: Options<GetCustomerData, ThrowOnError>): RequestResult<GetCustomerResponses, GetCustomerErrors, ThrowOnError> => (options.client ?? client).get<GetCustomerResponses, GetCustomerErrors, ThrowOnError>({ url: '/v1/customers/{id}', ...options });

/**
 * Update a customer
 *
 * Partial update. Emits no event: core's event catalog has no `billing.customer.updated` row, and this service does not publish a type the catalog does not list.
 * `processor_customer_id` is unique across customers, so a claim on an identifier another customer already holds is a 409. `owner` and `processor` are not updatable, which leaves this as the one identifier a client can move.
 */
export const updateCustomer = <ThrowOnError extends boolean = false>(options: Options<UpdateCustomerData, ThrowOnError>): RequestResult<UpdateCustomerResponses, UpdateCustomerErrors, ThrowOnError> => (options.client ?? client).patch<UpdateCustomerResponses, UpdateCustomerErrors, ThrowOnError>({
    url: '/v1/customers/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List plans
 */
export const listPlans = <ThrowOnError extends boolean = false>(options?: Options<ListPlansData, ThrowOnError>): RequestResult<ListPlansResponses, ListPlansErrors, ThrowOnError> => (options?.client ?? client).get<ListPlansResponses, ListPlansErrors, ThrowOnError>({ url: '/v1/plans', ...options });

/**
 * Create a plan
 *
 * One plan per `slug`, and one plan per `processor_price_id`. A second attempt at either is a 409, and the body names the field that collided.
 */
export const createPlan = <ThrowOnError extends boolean = false>(options: Options<CreatePlanData, ThrowOnError>): RequestResult<CreatePlanResponses, CreatePlanErrors, ThrowOnError> => (options.client ?? client).post<CreatePlanResponses, CreatePlanErrors, ThrowOnError>({
    url: '/v1/plans',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a plan by slug
 *
 * Read by slug, the handle that appears in a pricing page. A uuid is a 404 here: this operation does not look plans up by id.
 */
export const getPlan = <ThrowOnError extends boolean = false>(options: Options<GetPlanData, ThrowOnError>): RequestResult<GetPlanResponses, GetPlanErrors, ThrowOnError> => (options.client ?? client).get<GetPlanResponses, GetPlanErrors, ThrowOnError>({ url: '/v1/plans/{slug}', ...options });

/**
 * Update a plan
 *
 * Write by uuid, because the slug can be changed by this very request and a mutable handle is not a safe thing to address a mutation by. A slug is a 404 here: this operation does not look plans up by slug. Emits `billing.plan.updated` only when a field actually changed.
 * `slug` and `processor_price_id` are both unique across plans, so a claim on either one another plan already holds is a 409 and nothing is written.
 */
export const updatePlan = <ThrowOnError extends boolean = false>(options: Options<UpdatePlanData, ThrowOnError>): RequestResult<UpdatePlanResponses, UpdatePlanErrors, ThrowOnError> => (options.client ?? client).patch<UpdatePlanResponses, UpdatePlanErrors, ThrowOnError>({
    url: '/v1/plans/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List subscriptions
 *
 * Every subscription, not one account's, because v0 has no token and so no account to scope by. A recorded gap, the same one `GET /v1/customers` has, and closed the same way: when authorization lands this becomes an `account_id` filter read from the token and never from a query parameter.
 */
export const listSubscriptions = <ThrowOnError extends boolean = false>(options?: Options<ListSubscriptionsData, ThrowOnError>): RequestResult<ListSubscriptionsResponses, ListSubscriptionsErrors, ThrowOnError> => (options?.client ?? client).get<ListSubscriptionsResponses, ListSubscriptionsErrors, ThrowOnError>({ url: '/v1/subscriptions', ...options });

/**
 * Start a subscription by creating a Checkout session
 *
 * Creates a payment processor Checkout session for one plan and returns its URL. The caller sends the buyer there; the processor collects the first payment and creates the subscription.
 * **No subscription is created by this request, and the response is not a subscription.** A subscription does not exist until the payment completes, and this service does not invent a row for one that does not — which is why there is no `Location` header either: there is no resource to point at. The row appears when `customer.subscription.created` arrives, and `billing.subscription.started` is published in the same transaction as that row.
 * `customer_id` is in the body because v0 has no token to name the account with, and it is why a customer whose owner is a `User` rather than an `Account` is refused: which account a user belongs to is identity's fact and no event carrying it is in this build's `consumes`.
 * Idempotent on `Idempotency-Key`: the same key with the same body replays the first response rather than creating a second Checkout session, and the same key with a different body is a 409.
 */
export const createSubscriptionCheckout = <ThrowOnError extends boolean = false>(options: Options<CreateSubscriptionCheckoutData, ThrowOnError>): RequestResult<CreateSubscriptionCheckoutResponses, CreateSubscriptionCheckoutErrors, ThrowOnError> => (options.client ?? client).post<CreateSubscriptionCheckoutResponses, CreateSubscriptionCheckoutErrors, ThrowOnError>({
    url: '/v1/subscriptions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a subscription
 */
export const getSubscription = <ThrowOnError extends boolean = false>(options: Options<GetSubscriptionData, ThrowOnError>): RequestResult<GetSubscriptionResponses, GetSubscriptionErrors, ThrowOnError> => (options.client ?? client).get<GetSubscriptionResponses, GetSubscriptionErrors, ThrowOnError>({ url: '/v1/subscriptions/{id}', ...options });

/**
 * Cancel a subscription
 *
 * Asks the payment processor to cancel, and returns. **The subscription is not canceled by this response** — its status changes when `customer.subscription.deleted` arrives and `billing.subscription.canceled` is published. A response claiming the cancellation had happened would be a lie about a state this service does not own.
 * `at_period_end` is required and must be a boolean: the caller chooses, and this service does not inherit a processor's default on its behalf. It is refused as a 422 for a `past_due` subscription, which has no further period to serve — and refusing beats quietly cancelling immediately, which is not what was asked for.
 * A `canceled` or `unpaid` subscription is a 409: the request collides with something that has already happened, or the processor has stopped collecting and will cancel it itself.
 * No refund and no proration is requested. The credit for the unused part of a period is the processor's to compute, and a refund calculated here would be a figure this service did not keep.
 */
export const cancelSubscription = <ThrowOnError extends boolean = false>(options: Options<CancelSubscriptionData, ThrowOnError>): RequestResult<CancelSubscriptionResponses, CancelSubscriptionErrors, ThrowOnError> => (options.client ?? client).post<CancelSubscriptionResponses, CancelSubscriptionErrors, ThrowOnError>({
    url: '/v1/subscriptions/{id}/cancel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Move a subscription to another plan
 *
 * Asks the payment processor to move the subscription, and returns. **The local plan does not change by this response** — it changes when `customer.subscription.updated` arrives and `billing.subscription.updated` is published.
 * The timing rule, which is the point of the endpoint and is decided in one place:
 * * **A more expensive plan takes effect immediately.** The processor bills the
 * difference now (`proration_behavior: always_invoice`). The customer asked
 * for more service, and delivering it at the end of the period would mean
 * they used it for free in between.
 * * **A cheaper or equally priced plan takes effect at the end of the current
 * period**, with nothing carried forward (`proration_behavior: none`). Nobody
 * is refunded for a plan they are already leaving, and no credit is computed
 * here.
 * * **A plan on a different interval, or in a different currency, is refused.**
 * Ten dollars a month against a hundred a year is not a cheaper plan, it is a
 * different unit; comparing them would mean annualising, which is computing
 * money nobody asked for.
 *
 * `plan_change` in the response states which rule applied. It is not state — the subscription's own fields have not moved — and it exists so a client can tell the caller that a downgrade is scheduled rather than applied.
 */
export const changeSubscriptionPlan = <ThrowOnError extends boolean = false>(options: Options<ChangeSubscriptionPlanData, ThrowOnError>): RequestResult<ChangeSubscriptionPlanResponses, ChangeSubscriptionPlanErrors, ThrowOnError> => (options.client ?? client).post<ChangeSubscriptionPlanResponses, ChangeSubscriptionPlanErrors, ThrowOnError>({
    url: '/v1/subscriptions/{id}/change_plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * What this subscription grants, right now
 *
 * The plan's features and limits, and whether this subscription is currently granting them.
 * A `canceled` subscription grants nothing: `features` is `[]` and `limits` is `{}`. A `past_due` or `unpaid` one still grants, because the processor's grace period is a product decision and not this service's to take away.
 */
export const getSubscriptionEntitlements = <ThrowOnError extends boolean = false>(options: Options<GetSubscriptionEntitlementsData, ThrowOnError>): RequestResult<GetSubscriptionEntitlementsResponses, GetSubscriptionEntitlementsErrors, ThrowOnError> => (options.client ?? client).get<GetSubscriptionEntitlementsResponses, GetSubscriptionEntitlementsErrors, ThrowOnError>({ url: '/v1/subscriptions/{id}/entitlements', ...options });

/**
 * Receive one Stripe event
 *
 * Verifies the `Stripe-Signature` header against `STRIPE_WEBHOOK_SECRET` and stores the event before interpreting it. `STRIPE_WEBHOOK_SECRETS`, a comma-separated list, may be set instead during a secret rotation; a signature that verifies under any configured secret is accepted.
 * The response says whether the request was *received*, not whether this service found anything to do. Delivery is at-least-once, so the same event id arrives again — immediately, or a day later — and a replay is a 200 and a lookup rather than a second event. An event type this build has no mapping for, a type it deliberately ignores, and an event whose mapping failed are all 200 with the outcome recorded on the stored row. A 5xx would teach Stripe to retry a decision this service has already made, and would hide a parked row behind a timeout.
 * An unverified body is never stored. `stripe_event_id` is UNIQUE, so a replay cannot produce a second row, and the row is written in the same transaction as the event it produces, so a stored event and the receipt saying it arrived cannot disagree.
 * This endpoint is not token-authenticated and must never grow a token check: a `Bearer` here would be a second, weaker trust path to the same door as the `/v1` API.
 */
export const receiveStripeWebhook = <ThrowOnError extends boolean = false>(options: Options<ReceiveStripeWebhookData, ThrowOnError>): RequestResult<ReceiveStripeWebhookResponses, ReceiveStripeWebhookErrors, ThrowOnError> => (options.client ?? client).post<ReceiveStripeWebhookResponses, ReceiveStripeWebhookErrors, ThrowOnError>({
    url: '/v1/webhooks/stripe',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
