/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/pantry.yaml
//         pantry, document version 1.1.0,
//         vendored from git@github.com:cafaye/pantry.git
//         at commit 123afca1cd63c99d24347c032026e11feb75d3d8
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export { getService, healthz, listServices, type Options, readyz } from './sdk.gen.js';
export type { ClientOptions, Dependency, Exposes, GetServiceData, GetServiceError, GetServiceErrors, GetServiceResponse, GetServiceResponses, Health, HealthzData, HealthzResponse, HealthzResponses, Language, ListServicesData, ListServicesError, ListServicesErrors, ListServicesResponse, ListServicesResponses, Owner, Page, Problem, Readiness, ReadyzData, ReadyzError, ReadyzErrors, ReadyzResponse, ReadyzResponses, Repository, Service, ServiceKind, ServiceList } from './types.gen.js';
