/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/pantry.yaml
//         pantry, document version 1.1.0,
//         vendored from git@github.com:cafaye/pantry.git
//         at commit f009b8e2a968f5b1179bb40ca95270033986b6e3
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { GetServiceData, GetServiceErrors, GetServiceResponses, HealthzData, HealthzResponses, ListServicesData, ListServicesErrors, ListServicesResponses, ReadyzData, ReadyzErrors, ReadyzResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * The official cafaye service registry
 *
 * Returns the registered services, optionally narrowed by `kind`, `language`
 * and `contract`.
 *
 * A filter that matches nothing is `200` with `"data": []`. It is never a
 * `404`: "no service matches" and "there is no such collection" are
 * different answers, and only one of them is true.
 *
 * A filter value outside its vocabulary is a `400` naming the parameter and
 * what was allowed. An empty parameter value (`?kind=`) is a `400` too —
 * it is not the same as not asking for the filter. An unknown parameter is
 * also a `400`, so a client that asks a question this version cannot answer
 * is told rather than quietly given the whole list.
 *
 */
export const listServices = <ThrowOnError extends boolean = false>(options?: Options<ListServicesData, ThrowOnError>): RequestResult<ListServicesResponses, ListServicesErrors, ThrowOnError> => (options?.client ?? client).get<ListServicesResponses, ListServicesErrors, ThrowOnError>({ url: '/v1/services', ...options });

/**
 * One registered service
 *
 * The same object the list wraps, so a client reads one shape rather than
 * two. An unknown name is a `404`; a name that exists but matches a filter
 * is not a `404`, because no filter applies here.
 *
 */
export const getService = <ThrowOnError extends boolean = false>(options: Options<GetServiceData, ThrowOnError>): RequestResult<GetServiceResponses, GetServiceErrors, ThrowOnError> => (options.client ?? client).get<GetServiceResponses, GetServiceErrors, ThrowOnError>({ url: '/v1/services/{name}', ...options });

/**
 * Liveness
 *
 * `200` whenever the process is running — including when the registry did
 * not load. A process that cannot serve is still alive, and an orchestrator
 * that restarts on this would turn a data problem into a crash loop.
 *
 */
export const healthz = <ThrowOnError extends boolean = false>(options?: Options<HealthzData, ThrowOnError>): RequestResult<HealthzResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Readiness
 *
 * `200` only when the registry loaded and every entry validated against
 * core's manifest schema. This is the one probe that knows whether there is
 * anything to serve.
 *
 */
export const readyz = <ThrowOnError extends boolean = false>(options?: Options<ReadyzData, ThrowOnError>): RequestResult<ReadyzResponses, ReadyzErrors, ThrowOnError> => (options?.client ?? client).get<ReadyzResponses, ReadyzErrors, ThrowOnError>({ url: '/readyz', ...options });
