/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/pantry.yaml
//         pantry, document version 1.1.0,
//         vendored from git@github.com:cafaye/pantry.git
//         at commit de476a55940d4ee1de485c12d66ed6963122f628
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { GetServiceData, GetServiceErrors, GetServiceResponses, HealthzData, HealthzResponses, ListServiceRequiredByData, ListServiceRequiredByErrors, ListServiceRequiredByResponses, ListServiceRequirementsData, ListServiceRequirementsErrors, ListServiceRequirementsResponses, ListServicesData, ListServicesErrors, ListServicesResponses, ReadyzData, ReadyzErrors, ReadyzResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * The official cafaye service registry
 *
 * Returns the registered services, optionally narrowed by `kind`, `language`
 * and `contract`.
 *
 * A filter that matches nothing is `200` with `"data": []`. It is never a
 * `404`: "no service matches" and "there is no such collection" are
 * different answers, and only one of them is true.
 *
 * A filter value outside its vocabulary is a `400` naming the parameter and
 * what was allowed. An empty parameter value (`?kind=`) is a `400` too —
 * it is not the same as not asking for the filter. An unknown parameter is
 * also a `400`, so a client that asks a question this version cannot answer
 * is told rather than quietly given the whole list.
 *
 */
export const listServices = <ThrowOnError extends boolean = false>(options?: Options<ListServicesData, ThrowOnError>): RequestResult<ListServicesResponses, ListServicesErrors, ThrowOnError> => (options?.client ?? client).get<ListServicesResponses, ListServicesErrors, ThrowOnError>({ url: '/v1/services', ...options });

/**
 * One registered service
 *
 * The same object the list wraps, so a client reads one shape rather than
 * two. An unknown name is a `404`; a name that exists but matches a filter
 * is not a `404`, because no filter applies here.
 *
 */
export const getService = <ThrowOnError extends boolean = false>(options: Options<GetServiceData, ThrowOnError>): RequestResult<GetServiceResponses, GetServiceErrors, ThrowOnError> => (options.client ?? client).get<GetServiceResponses, GetServiceErrors, ThrowOnError>({ url: '/v1/services/{name}', ...options });

/**
 * What one service needs in order to run
 *
 * The forward direction of the compatibility graph: the services this one
 * declares a `requires` edge to, each with the version range the publisher
 * constrains it to and whether the edge is `required`, `soft` or `dev`.
 *
 * The backward direction — "which services require this one?" — is
 * `GET /v1/services/{name}/required-by`. They are two questions, not one
 * question read from two ends: an operator choosing what to run reads
 * this one, and an operator about to change a service reads that one
 * before deciding the change is safe.
 *
 * **`requires` edges only.** `conflicts_with` is a different question —
 * "what must I NOT run alongside this?" — and answering both under one
 * name is how a caller ends up installing a conflict. It has no
 * operation in this version; when it gets one it will get its own path,
 * because the two answers must never be shape-compatible enough to
 * substitute for each other.
 *
 * An edge appears here only when **both** of its endpoints are visible
 * to the caller, which is a property of the row-level policy the
 * database applies rather than a filter this operation performs: an edge
 * from a published service into a draft is a fact about work in
 * progress, and work in progress is not in the public graph.
 *
 * An unknown name is a `404`. A known service with no `requires` edges
 * is `200` with `"data": []` — a leaf of the graph is an answer, not an
 * absence.
 *
 */
export const listServiceRequirements = <ThrowOnError extends boolean = false>(options: Options<ListServiceRequirementsData, ThrowOnError>): RequestResult<ListServiceRequirementsResponses, ListServiceRequirementsErrors, ThrowOnError> => (options.client ?? client).get<ListServiceRequirementsResponses, ListServiceRequirementsErrors, ThrowOnError>({ url: '/v1/services/{name}/requirements', ...options });

/**
 * What depends on one service
 *
 * The backward direction of the compatibility graph: the services that
 * declare a `requires` edge **to** this one. This is the
 * upgrade-safety question — before changing a service's contract,
 * read this to learn who is reading it.
 *
 * The forward direction — "what do I need to run this?" — is
 * `GET /v1/services/{name}/requirements`.
 *
 * **`requires` edges only**, for the same reason the forward direction
 * gives: `conflicts_with` is a different fact and must not be
 * shape-compatible with this answer.
 *
 * An edge appears here only when **both** of its endpoints are visible
 * to the caller. In this direction that has a consequence worth naming:
 * an edge **from** a draft service is hidden, so a service's public
 * backward graph can grow as work in progress is published. That is
 * the policy's answer rather than this operation's filter, and it is
 * the conservative one — nothing here claims a dependency the caller
 * cannot also read the other side of.
 *
 * An unknown name is a `404`. A service nothing requires is `200` with
 * `"data": []` — most leaf services are in that state, and it is an
 * answer rather than an absence.
 *
 */
export const listServiceRequiredBy = <ThrowOnError extends boolean = false>(options: Options<ListServiceRequiredByData, ThrowOnError>): RequestResult<ListServiceRequiredByResponses, ListServiceRequiredByErrors, ThrowOnError> => (options.client ?? client).get<ListServiceRequiredByResponses, ListServiceRequiredByErrors, ThrowOnError>({ url: '/v1/services/{name}/required-by', ...options });

/**
 * Liveness
 *
 * `200` whenever the process is running — including when the registry did
 * not load. A process that cannot serve is still alive, and an orchestrator
 * that restarts on this would turn a data problem into a crash loop.
 *
 */
export const healthz = <ThrowOnError extends boolean = false>(options?: Options<HealthzData, ThrowOnError>): RequestResult<HealthzResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Readiness
 *
 * `200` only when the registry loaded and every entry validated against
 * core's manifest schema. This is the one probe that knows whether there is
 * anything to serve.
 *
 */
export const readyz = <ThrowOnError extends boolean = false>(options?: Options<ReadyzData, ThrowOnError>): RequestResult<ReadyzResponses, ReadyzErrors, ThrowOnError> => (options?.client ?? client).get<ReadyzResponses, ReadyzErrors, ThrowOnError>({ url: '/readyz', ...options });
