/* eslint-disable */
// Generated by @hey-api/openapi-ts. DO NOT EDIT.
// Source: specs/pantry.yaml
//         pantry, document version 1.1.0,
//         vendored from git@github.com:cafaye/pantry.git
//         at commit f009b8e2a968f5b1179bb40ca95270033986b6e3
// Regenerate: npm run generate
//            test/regeneration.test.mjs proves regeneration is a no-op,
//            and that a hand-edit here is reverted by it.

export type ClientOptions = {
    baseUrl: 'https://pantry.cafaye.com' | 'http://localhost:8080' | (string & {});
};

/**
 * A page of registered services.
 */
export type ServiceList = {
    /**
     * Always an array, empty rather than absent. Sorted by name.
     */
    data: Array<Service>;
    page: Page;
};

/**
 * core's paging envelope.
 */
export type Page = {
    /**
     * Opaque; null on the last page.
     */
    next_cursor: string | null;
    has_more: boolean;
};

/**
 * One registered service: its manifest, plus `kind` and `basePath`.
 *
 * Optional keys are omitted rather than null when the service's manifest
 * omits them — `defaultBranch`, `visibility`, `contact`, `description` and a
 * dependency's `version`/`required`. Two keys are always present and may be
 * null, because null there is a fact rather than an absence: `exposes` is
 * null when the manifest declares no contract surface, and `basePath` is
 * null when the service publishes no OpenAPI document.
 *
 */
export type Service = {
    /**
     * The cafaye namespace name; also the repository name and the event `source`.
     */
    name: string;
    description?: string;
    language: Language;
    kind: ServiceKind;
    /**
     * The service's constraint on the core spec version, in core's four-form grammar.
     */
    core: string;
    /**
     * The `/vN` prefix every contract path in the service's OpenAPI document
     * is under, or null when it publishes no document.
     *
     */
    basePath: string | null;
    /**
     * The service's published surface, or null when it declares none.
     */
    exposes: Exposes | null;
    /**
     * Event types this service subscribes to. Empty rather than absent.
     */
    consumes: Array<string>;
    /**
     * Other cafaye services this one builds on. Empty rather than absent.
     */
    dependencies: Array<Dependency>;
    repository: Repository;
    owner: Owner;
};

export type Exposes = {
    /**
     * Repository-relative path to the service's OpenAPI 3.1 document.
     */
    api: string | null;
    /**
     * Event types this service publishes, as `<service>.<entity>.<action>`.
     */
    events: Array<string>;
};

export type Dependency = {
    name: string;
    /**
     * Constraint on the dependency's own contract version.
     */
    version?: string;
    /**
     * false is a soft dependency — the service runs degraded without it.
     */
    required?: boolean;
};

export type Repository = {
    /**
     * SSH remote. core's schema rejects HTTPS for a cafaye repository.
     */
    url: string;
    defaultBranch?: 'master';
    visibility?: 'public' | 'private';
};

export type Owner = {
    /**
     * The accountable team, not the author.
     */
    team: string;
    contact?: string;
};

/**
 * | manifest says | kind |
 * | --- | --- |
 * | `exposes.api` declared, no `consumes` | `api` |
 * | `exposes.api` declared and `consumes` non-empty | `both` |
 * | no `exposes.api`, some event work | `worker` |
 * | no contract surface, and the repository serves HTTP | `api` |
 * | no contract surface, and the repository is a binary | `cli` |
 * | no contract surface, and it is an installed artifact with no entry point | `cli` |
 *
 * The last three rows are **curated**, not derived, and they are the only
 * two curated values. A manifest that declares no contract surface cannot
 * say which one it is: `guard` (a gateway whose OpenAPI document has not
 * been written yet), `caf` (a binary) and `cafaye-ts` (a package other
 * programs import, which serves nothing and vendors six other
 * repositories' OpenAPI documents into `specs/`) declare the same absence
 * of surface, and `language` names a toolchain rather than a shape.
 *
 * A client that routes or deploys by `kind` should branch on it rather
 * than assume every entry serves HTTP: `cli` is an entry somebody installs
 * and nobody routes to.
 *
 * The third row is a value the vocabulary does not quite have a word for,
 * and the two client libraries in the fleet are currently answered
 * differently — `cafaye-ts` is a `cli` here, and the `cafaye-rb` gem is in
 * the exclusion record rather than in this list. See `DECISIONS.md` D1.
 * Neither answer changes the wire format; it changes who is listed.
 *
 */
export type ServiceKind = 'api' | 'worker' | 'both' | 'cli';

/**
 * core's manifest `language` enum minus `spec`. `spec` is for
 * specification-only repositories — core itself, contract-test fixtures —
 * which are not services and cannot be registered.
 *
 */
export type Language = 'go' | 'ruby' | 'elixir' | 'python' | 'typescript' | 'rust';

export type Health = {
    status: 'ok';
};

export type Readiness = {
    status: 'ok';
    /**
     * How many services are loaded.
     */
    services: number;
};

/**
 * RFC 9457 problem details with core's extensions: a stable
 * `https://errors.cafaye.com/<code>` type, a reserved `code`, and a
 * `trace_id` that always matches the `X-Trace-Id` header. No service
 * invents its own error body, so every non-2xx response — including the
 * framework's own 404 and 405 — is this shape.
 *
 */
export type Problem = {
    type: string;
    /**
     * A fixed human-readable summary for this code; may be reworded without a version bump.
     */
    title: string;
    status: number;
    /**
     * Specific to this occurrence. Clients do not parse it.
     */
    detail: string;
    /**
     * The request path this is about.
     */
    instance: string;
    code: 'not_found' | 'validation_failed' | 'method_not_allowed' | 'unavailable' | 'internal';
    trace_id: string;
    /**
     * Present only on 422. pantry answers 400 rather than 422, so it never sends this.
     */
    errors?: Array<{
        [key: string]: unknown;
    }>;
};

export type ListServicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Narrow to services of one kind. `api` serves HTTP and consumes
         * nothing, `worker` has no declared HTTP surface and does event work,
         * `both` serves HTTP and consumes events, and `cli` is an installed
         * artifact — a binary, or a package other programs import — rather
         * than something brought up and routed to. `api` and `cli` are also
         * the two curated values: an entry whose manifest declares no contract
         * surface is one of those two by a recorded judgement rather than by
         * derivation.
         *
         */
        kind?: ServiceKind;
        /**
         * Narrow to one implementation language. This is core's manifest
         * `language` enum minus `spec`: a specification repository is not a
         * service and cannot be a registry entry, so `?language=spec` is a
         * `400` rather than an empty list.
         *
         */
        language?: Language;
        /**
         * Narrow to services whose own `core` constraint shares a version with
         * this range. The comparison is range intersection, not string
         * equality: `>=0.2.0` matches a service pinned to `^0.2.0`, and
         * `^0.2.0` does not match a service pinned to `^0.1.0` because before
         * 1.0 a caret pins the minor.
         *
         * The grammar is core's four forms and nothing else: `MAJOR.MINOR.PATCH`,
         * `^`, `~` and `>=`. Anything else is a `400`.
         *
         */
        contract?: string;
        /**
         * Page size. Defaults to 25, capped at 100.
         */
        limit?: number;
        /**
         * Opaque base64url cursor from a previous response's
         * `page.next_cursor`. Clients must not parse it and its encoding may
         * change without notice. A cursor this service did not issue is a
         * `400` — never silently page one, which loses rows without saying so.
         *
         */
        cursor?: string;
    };
    url: '/v1/services';
};

export type ListServicesErrors = {
    /**
     * A query parameter outside its vocabulary, or an unusable cursor.
     */
    400: Problem;
    /**
     * The registry did not load, so there is nothing to answer with. A `200`
     * with an empty `data` would be indistinguishable from a platform with
     * no services.
     *
     */
    503: Problem;
};

export type ListServicesError = ListServicesErrors[keyof ListServicesErrors];

export type ListServicesResponses = {
    /**
     * The registry, filtered and paged. `data` is always an array.
     */
    200: ServiceList;
};

export type ListServicesResponse = ListServicesResponses[keyof ListServicesResponses];

export type GetServiceData = {
    body?: never;
    path: {
        /**
         * The cafaye namespace name, which is also the repository name.
         */
        name: string;
    };
    query?: never;
    url: '/v1/services/{name}';
};

export type GetServiceErrors = {
    /**
     * No official cafaye service is registered under that name.
     */
    404: Problem;
    /**
     * The registry did not load.
     */
    503: Problem;
};

export type GetServiceError = GetServiceErrors[keyof GetServiceErrors];

export type GetServiceResponses = {
    /**
     * The service.
     */
    200: Service;
};

export type GetServiceResponse = GetServiceResponses[keyof GetServiceResponses];

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    /**
     * The process is running.
     */
    200: Health;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type ReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzErrors = {
    /**
     * The registry did not load; the detail names what could not be read.
     */
    503: Problem;
};

export type ReadyzError = ReadyzErrors[keyof ReadyzErrors];

export type ReadyzResponses = {
    /**
     * The registry is loaded, and `services` counts it.
     */
    200: Readiness;
};

export type ReadyzResponse = ReadyzResponses[keyof ReadyzResponses];
